{{- if .Values.examQueue.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-queue-deployment
spec:
  replicas: {{ .Values.examQueue.replicaCount }}
  selector:
    matchLabels:
      app: exam-queue
  template:
    metadata:
      labels:
        app: exam-queue
        component: broker
        tier: backend
        environment: {{ .Values.global.environment }}
    spec:
      containers:
      - name: exam-queue
        image: {{ .Values.examQueue.image.repository }}:{{ .Values.examQueue.image.tag }}
        ports:
        - containerPort: {{ .Values.examQueue.service.targetPort }}
        imagePullPolicy: {{ .Values.examQueue.image.pullPolicy }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.examQueue.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        {{- with .Values.examQueue.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.examQueue.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.examQueue.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.examQueue.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
