{{- if .Values.paperDb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: external-paper-db-service
  labels:
    app: paper
    component: api
    tier: database
    environment: {{ .Values.global.environment }}
spec:
  type: ExternalName
  externalName: {{ .Values.paperDb.externalName }}
{{- end }}
