syntax = "proto3";

package proto;

option go_package = "/proto";

message Empty {}

// Question Type enum
enum QuestionType {
  UNKNOWN_QUESTION_TYPE = 0;
  MCQ = 1;
  SUBJECTIVE = 2;
  CODING = 3;
}

// Parameter Type enum for coding-question input-definitions
enum ParameterType {
  UNKNOWN_PARAMETER_TYPE = 0;

  // Primitive
  NUMBER = 1;
  STRING = 2;
  BOOLEAN = 3;

  // Composite
  ARRAY = 4;
}

message CodingQuestionTestCase {
  repeated string inputs = 1;
  string output = 2;
  optional string explanation = 3;
  bool hidden = 4;
  int32 order = 5;
}

message ExamQuestionResponse {
  string question_hash = 1;
  bytes raw_question = 2;
  QuestionType type = 5;
  repeated CodingQuestionTestCase test_cases = 10;
}