syntax = "proto3";

package proto;

option go_package = "/proto";

import "google/protobuf/timestamp.proto";
import "common.proto";

service ExamService {
  // Exam operations
  rpc GetUserExams(Empty) returns (ExamList) {}
  rpc CreateExam(CreateExamRequest) returns (ExamResponse) {}
  rpc UpdateExam(UpdateExamRequest) returns (ExamResponse) {}
  rpc GetExam(ExamRequest) returns (ExamResponse) {}
  rpc CheckExamAccess(ExamRequest) returns (ExamAccessResponse) {}
  rpc GetExamQuestions(ExamRequest) returns (ExamQuestionsResponse) {}
  rpc GetExamCategories(ExamRequest) returns (ExamCategoriesResponse) {}

  // Participant operations
  rpc GetExamParticipants(ExamRequest) returns (ParticipantList) {}
  rpc AddExamParticipant(AddParticipantRequest) returns (ParticipantResponse) {}
  rpc RemoveExamParticipant(RemoveParticipantRequest) returns (Empty) {}
  rpc StartExam(StartExamRequest) returns (Empty) {}
  rpc EndExam(EndExamRequest) returns (Empty) {}
  rpc MarkAsEvaluated(ParticipantRequest) returns (EvaluationStatusResponse) {}
  rpc CheckExamParticipant(CheckParticipantRequest) returns (CheckParticipantResponse) {}
  rpc GetParticipantTiming(GetParticipantTimingRequest) returns (ParticipantTimingResponse) {}

  // Answer operations
  rpc GetParticipantAnswers(ParticipantRequest) returns (AnswerList) {}
  rpc GetAnswer(GetAnswerRequest) returns (AnswerResponse) {}
  rpc UpsertAnswer(UpsertAnswersRequest) returns (UpsertAnswersResponse) {}
  rpc UpdateAnswerForEvaluation(UpdateAnswerRequest) returns (Empty) {}
}

// Exam messages
message ExamRequest {
  int64 exam_id = 1;
}

message CreateExamRequest {
  string title = 1;
  google.protobuf.Timestamp starts_at = 2;
  google.protobuf.Timestamp ends_at = 3;
  int32 max_candidates_count = 4;
  optional string type = 5;
  int64 paper_id = 6;
  int32 duration_minutes = 7;
}

message UpdateExamRequest {
  int64 exam_id = 1;
  optional string title = 2;
  optional google.protobuf.Timestamp starts_at = 3;
  optional google.protobuf.Timestamp ends_at = 4;
  optional string type = 6;
  optional int32 duration_minutes = 7;
}

message ExamResponse {
  int64 id = 1;
  string title = 2;
  google.protobuf.Timestamp starts_at = 3;
  google.protobuf.Timestamp ends_at = 4;
  int64 created_by = 5;
  string type = 6;
  int32 max_candidates_count = 7;
  int64 paper_id = 8;
  ParticipantCount participant_counts = 9;
  int32 duration_minutes = 10;
}

message ExamList {
  repeated ExamResponse exams = 1;
}

message ParticipantCount {
  int32 unattended = 1;
  int32 invited = 2;
  int32 started = 3;
  int32 ended = 4;
}

// Participant messages
message ParticipantRequest {
  int64 participant_id = 1;
}

message ParticipantResponse {
  int64 id = 1;
  int64 user_id = 2;
  int32 status = 6;
  int32 score_awarded = 7;
  optional google.protobuf.Timestamp started_at = 8;
  optional google.protobuf.Timestamp ended_at = 9;
}

message ParticipantList {
  repeated ParticipantResponse participants = 1;
}

// Replace AddParticipantsRequest with AddParticipantRequest
message AddParticipantRequest {
  int64 exam_id = 1;
  int64 user_id = 2;
}

message RemoveParticipantRequest {
  int64 exam_id = 1;
  int64 participant_id = 2;
}

message StartExamRequest {
  int64 exam_id = 1;
  int32 duration_minutes = 2;
}

message EndExamRequest {
  int64 exam_id = 1;
}

message EvaluationStatusResponse {
  int32 unevaluated_count = 1;
}

// Answer messages
message Answer {
  string answer = 1;
  google.protobuf.Timestamp submitted_at = 2;
  int64 question_id = 3;
}

message UpsertAnswersRequest {
  int64 exam_id = 1;
  Answer answer = 2;
}

message UpsertAnswersResponse {
  int64 answer_id = 1;
}

message AnswerResponse {
  int64 id = 1;
  int64 exam_participant_id = 2;
  int64 question_id = 3;
  string answer = 4;
  int32 score_awarded = 5;
  string comments = 6;
}

message AnswerList {
  repeated AnswerResponse answers = 1;
}

message UpdateAnswerRequest {
  int64 answer_id = 1;
  optional int32 new_score = 2;
  optional bool evaluated = 3;
  optional string comments = 4;
}

message GetAnswerRequest {
  int64 answer_id = 1;
}

message ExamAccessResponse {
  ExamAccessType access_type = 1;
  optional int32 participant_status = 2;
}

message CheckParticipantRequest {
  int64 exam_id = 1;
}

message CheckParticipantResponse {
  int32 participant_status = 1;
}

message GetParticipantTimingRequest {
  int64 exam_id = 1;
}

message ParticipantTimingResponse {
  optional google.protobuf.Timestamp started_at = 1;
  optional google.protobuf.Timestamp scheduled_end_time = 2;
}

message ExamQuestion {
  int64 question_id = 1;
}

message ExamQuestionsResponse {
  repeated ExamQuestion questions = 1;
}

message ExamCategory {
  int64 category_id = 1;
}

message ExamCategoriesResponse {
  repeated ExamCategory categories = 1;
}

enum ExamAccessType {
  OWNER = 0;
  PARTICIPANT = 1;
}
