syntax = "proto3";

package proto;

option go_package = "/proto";

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";
import "common.proto";

service Exam {
  // Exam operations
  rpc GetUserExams(google.protobuf.Empty) returns (ExamList) {}
  rpc CreateExam(CreateExamRequest) returns (ExamResponse) {}
  rpc UpdateExam(UpdateExamRequest) returns (ExamResponse) {}
  rpc GetExam(ExamRequest) returns (ExamResponse) {}
  rpc GetExamQuestions(ExamRequest) returns (ExamQuestionsResponse) {}
  rpc GetExamCategories(ExamRequest) returns (ExamCategoriesResponse) {}
  rpc GetExamQuestion(ExamQuestionRequest) returns (ExamQuestionResponse) {}
  rpc GetExamPermission(ExamRequest) returns (ExamPermissionResponse) {}
  rpc DeleteExams(DeleteExamsRequest) returns (google.protobuf.Empty) {}
  rpc GetExamResults(ExamRequest) returns (ExamResultsResponse) {}

  // Participant operations
  rpc GetExamParticipants(ExamRequest) returns (ParticipantList) {}
  rpc AddExamParticipant(AddParticipantRequest) returns (ParticipantResponse) {}
  rpc RemoveExamParticipant(RemoveParticipantRequest)
      returns (google.protobuf.Empty) {}
  rpc StartExam(StartExamRequest) returns (google.protobuf.Empty) {}
  rpc EndExam(EndExamRequest) returns (google.protobuf.Empty) {}
  rpc GetExamParticipant(GetExamParticipantRequest)
      returns (GetExamParticipantResponse) {}
  rpc GetParticipantById(ParticipantRequest) returns (ParticipantResponse) {}

  // Answer operations
  rpc GetParticipantAnswers(ParticipantRequest) returns (AnswerList) {}
  rpc GetAnswerForExam(GetAnswerRequest) returns (AnswerMinimalResponse) {}
  rpc UpsertAnswer(UpsertAnswersRequest) returns (UpsertAnswersResponse) {}

  // Evaluation
  rpc GetAnswerEvaluationData(ParticipantQuestionRequest)
      returns (GetAnswerEvaluationDataResponse) {}
  rpc UpdateAnswerForEvaluation(UpdateAnswerRequest)
      returns (GetAnswerEvaluationDataResponse) {}
  rpc MarkParticipantAsEvaluated(ParticipantRequest)
      returns (EvaluationStatusResponse) {}
  rpc GetAnswerForEvaluation(ParticipantQuestionRequest)
      returns (AnswerMinimalResponse) {}
}

enum ExamType {
  UNKNOWN_EXAM_TYPE = 0;
  LINK = 1;
  INVITE = 2;
}

// Exam messages
message ExamRequest { string exam_hash = 1; }

message CreateExamRequest {
  string title = 1;
  google.protobuf.Timestamp starts_at = 2;
  google.protobuf.Timestamp ends_at = 3;
  int32 max_candidates_count = 4;
  optional ExamType type = 5;
  string paper_hash = 6;
  int32 duration_minutes = 7;
}

message UpdateExamRequest {
  string exam_hash = 1;
  optional string title = 2;
  optional google.protobuf.Timestamp starts_at = 3;
  optional google.protobuf.Timestamp ends_at = 4;
  optional ExamType type = 5;
  optional int32 duration_minutes = 6;
}

message ExamResponse {
  string exam_hash = 1;
  string title = 2;
  google.protobuf.Timestamp starts_at = 3;
  google.protobuf.Timestamp ends_at = 4;
  int64 created_by = 5;
  ExamType type = 6;
  int32 max_candidates_count = 7;
  ParticipantCount participant_counts = 9;
  int32 duration_minutes = 10;
  int32 max_score = 11;
}

message ExamList { repeated ExamResponse exams = 1; }

message ParticipantCount {
  int32 unattended = 1;
  int32 invited = 2;
  int32 started = 3;
  int32 ended = 4;
}

message ExamQuestionRequest {
  string exam_hash = 1;
  string question_hash = 2;
}

// Participant messages
message ParticipantRequest { int64 participant_id = 1; }

message ParticipantResponse {
  int64 participant_id = 1;
  int64 user_id = 2;
  int32 status = 3;
  int32 score_awarded = 4;
  optional google.protobuf.Timestamp started_at = 5;
  optional google.protobuf.Timestamp ended_at = 6;
  optional google.protobuf.Timestamp scheduled_end_time = 7;
}

message ParticipantList { repeated ParticipantResponse participants = 1; }

message AddParticipantRequest {
  string exam_hash = 1;
  int64 user_id = 2;
}

message RemoveParticipantRequest {
  string exam_hash = 1;
  int64 participant_id = 2;
}

message StartExamRequest { string exam_hash = 1; }

message EndExamRequest { string exam_hash = 1; }

message EvaluationStatusResponse { int32 unevaluated_count = 1; }

// Answer messages
message Answer {
  optional bytes answer = 1; // JSON encoded answer, can be nil
  google.protobuf.Timestamp submitted_at = 2;
  string question_hash = 3;
}

message UpsertAnswersRequest {
  string exam_hash = 1;
  Answer answer = 2;
}

message UpsertAnswersResponse {
  int64 answer_id = 1;
  string question_hash = 2;
  optional bytes answer = 3; // JSON encoded answer, can be nil
}

message AnswerResponse {
  int64 answer_id = 1;
  int64 exam_participant_id = 2;
  string question_hash = 3;
  bytes answer = 4; // JSON encoded answer

  // question fields
  int32 order = 5;
  int64 category_id = 6;
  QuestionType question_type = 7;
  int32 max_score = 8;
  bytes question = 9; // JSON encoded question
}

message AnswerList { repeated AnswerResponse answers = 1; }

message UpdateAnswerRequest {
  int64 answer_id = 1;
  optional int32 new_score = 2;
  optional bool evaluated = 3;
}

message GetAnswerRequest {
  string exam_hash = 1;
  string question_hash = 2;
}

message AnswerMinimalResponse {
  int64 answer_id = 1;
  bytes answer = 2; // JSON encoded answer
  string question_hash = 3;
}

message CheckParticipantRequest { string exam_hash = 1; }

message GetExamParticipantRequest { string exam_hash = 1; }

message GetExamParticipantResponse {
  int64 participant_id = 1;
  int32 score_awarded = 2;
  optional google.protobuf.Timestamp started_at = 3;
  optional google.protobuf.Timestamp scheduled_end_time = 4;
}

message ExamQuestion {
  string question_hash = 1;
  int64 category_id = 2;
  int32 order = 3;
  QuestionType type = 4;
  int32 max_score = 5;
}

message ExamQuestionsResponse { repeated ExamQuestion questions = 1; }

message ExamCategory {
  int64 category_id = 1;
  string name = 2;
  int32 order = 3;
}

message ExamCategoriesResponse { repeated ExamCategory categories = 1; }

enum ExamAccessType {
  OWNER = 0;
  PARTICIPANT = 1;
}

message ExamPermissionResponse {
  bool can_read = 1;
  bool can_write = 2;
  bool can_participate = 3;
  bool can_evaluate = 4;
  optional int32 participant_status = 5;
}

message ParticipantQuestionRequest {
  int64 participant_id = 1;
  string question_hash = 2;
}

message GetAnswerEvaluationDataResponse {
  int64 answer_id = 1;
  string question_hash = 2;
  int32 score_awarded = 3;
}

message DeleteExamsRequest { repeated string exam_hashes = 1; }

message ExamResultItem {
  int64 answer_id = 1;
  int32 score_awarded = 2;
}

message ExamResultsResponse { repeated ExamResultItem results = 1; }
