syntax = "proto3";

package proto;

option go_package = "/proto";

import "google/protobuf/empty.proto";
import "common.proto";

service Paper {
  // Paper operations
  rpc GetUserPapers(google.protobuf.Empty) returns (PaperList) {}
  rpc GetPaper(PaperRequest) returns (PaperResponse) {}
  rpc CreatePaper(google.protobuf.Empty) returns (CreatePaperResponse) {}
  rpc UpdatePaper(UpdatePaperRequest) returns (google.protobuf.Empty) {}
  rpc DeletePapers(DeletePapersRequest) returns (google.protobuf.Empty) {}
  rpc GetPaperPermissions(PaperRequest) returns (PaperPermissionsResponse) {}

  // Question operations
  rpc GetPaperQuestions(PaperRequest) returns (QuestionList) {}
  rpc GetPaperQuestion(PaperQuestionRequest) returns (PaperQuestionResponse) {}
  rpc CreatePaperQuestion(CreatePaperQuestionRequest)
      returns (CreatePaperQuestionResponse) {}
  rpc UpdatePaperQuestion(UpdatePaperQuestionRequest)
      returns (UpdatePaperQuestionResponse) {}
  rpc DeletePaperQuestion(PaperQuestionRequest)
      returns (google.protobuf.Empty) {}
  rpc ReorderPaperQuestions(ReorderPaperQuestionsRequest)
      returns (google.protobuf.Empty) {}
  rpc GetPaperBoilerplate(GetPaperBoilerplateRequest)
      returns (BoilerplateResponse) {}
  rpc UpsertPaperTestCases(UpsertPaperTestCasesRequest)
      returns (google.protobuf.Empty) {}

  // Category operations
  rpc GetPaperCategories(PaperRequest) returns (PaperCategoryList) {}
  rpc CreatePaperCategory(PaperRequest)
      returns (PaperCategoryResponse) {}
  rpc UpdatePaperCategory(UpdatePaperCategoryRequest)
      returns (google.protobuf.Empty) {}
  rpc DeletePaperCategory(PaperCategoryRequest)
      returns (google.protobuf.Empty) {}
  rpc ReorderPaperCategories(ReorderPaperCategoriesRequest)
      returns (google.protobuf.Empty) {}

  // Exam operations
  rpc GetPaperQuestionsMeta(PaperRequest) returns (PaperQuestionsMeta) {}
  rpc GetPaperCategoriesMeta(PaperRequest) returns (PaperCategoriesMeta) {}
}

// Paper messages
message PaperRequest { string paper_hash = 1; }

message PaperResponse {
  string paper_hash = 1;
  string title = 2;
  int32 max_score = 3;
  int32 duration_minutes = 4;
  QuestionCount question_counts = 5;
  int64 created_by = 6;
}

message CreatePaperResponse { string paper_hash = 1; }

message PaperList { repeated PaperResponse papers = 1; }

message UpdatePaperRequest {
  string paper_hash = 1;
  optional string title = 2;
  optional int32 duration_minutes = 3;
}

message QuestionCount {
  int32 mcq = 1;
  int32 subjective = 2;
  int32 coding = 3;
}

message DeletePapersRequest { repeated string paper_hashes = 1; }

// Question messages
message PaperQuestionRequest {
  string paper_hash = 1;
  string question_hash = 2;
}

message PaperQuestionResponse {
  string question_hash = 1;
  bytes raw_question = 2;
  int64 category_id = 4;
  QuestionType type = 5;
  string paper_hash = 6;
  int32 max_score = 7;
  repeated CodingQuestionTestCase test_cases = 8;
}

message QuestionList { repeated QuestionMinimal questions = 1; }

message QuestionMinimal {
  string question_hash = 1;
  int64 category_id = 2;
  string paper_hash = 3;
  int32 order = 4;
  bytes raw_question = 5;
}

message PaperQuestionsMeta { repeated PaperQuestionMeta questions = 1; }

message PaperQuestionMeta {
  int64 id = 1;
  int64 category_id = 2;
  int32 order = 3;
  int32 max_score = 4;
}

message CreatePaperQuestionRequest {
  string paper_hash = 1;
  bytes raw_question = 2;
  int64 category_id = 3;
  QuestionType type = 4;
  int32 max_score = 5;
}

message CreatePaperQuestionResponse { string question_hash = 1; }

message UpdatePaperQuestionRequest {
  string paper_hash = 1;
  string question_hash = 2;
  optional QuestionType type = 3;
  optional bytes raw_question = 4;
  optional int32 max_score = 5;
}

message UpdatePaperQuestionResponse { string question_hash = 1; }

message ReorderPaperQuestionsRequest {
  string paper_hash = 1;
  int64 category_id = 2;
  repeated string question_hashes = 3;
}

// Category messages

message PaperCategoryRequest {
  string paper_hash = 1;
  int64 category_id = 2;
}

message PaperCategoryList { repeated PaperCategoryResponse categories = 1; }

message PaperCategoryResponse {
  int64 id = 1;
  string name = 2;
  int32 order = 3;
}

message PaperCategoriesMeta { repeated PaperCategoryMeta categories = 1; }

message PaperCategoryMeta {
  int64 id = 1;
  int32 order = 3;
}

message UpdatePaperCategoryRequest {
  string paper_hash = 1;
  int64 category_id = 2;
  string name = 3;
}

message ReorderPaperCategoriesRequest {
  string paper_hash = 1;
  repeated int64 category_ids = 2;
}

message PaperPermissionsResponse {
  bool can_read = 1;
  bool can_write = 2;
}

message GetPaperBoilerplateRequest {
  string paper_hash = 1;
  string question_hash = 2;
  int32 language_id = 3;
}

message UpsertPaperTestCasesRequest {
  string paper_hash = 1;
  string question_hash = 2;
  repeated UpsertTestCase test_cases = 3;
}