syntax = "proto3";

package proto;

option go_package = "/proto";

message GetUserRequest {
  int32 user_id = 1;
}

message UserProfileResponse {
  int32 id = 1;
  string username = 2;
  string email = 3;
  string first_name = 4;
  string last_name = 5;
}

message UpdateUserRequest {
  int32 user_id = 1;
  optional string username = 2;
  optional string first_name = 3;
  optional string last_name = 4;
}

message UpdateUserResponse {
  UserProfileResponse user = 1;
  map<string, string> not_updated_fields = 2;
}
