{{- if .Values.paper.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: paper-config
  labels:
    app: paper
    component: config
    tier: backend
    environment: {{ .Values.global.environment }}
data:
  GO_ENV: {{ .Values.global.environment }}

  {{- range $key, $value := .Values.paper.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
