{{- if .Values.paper.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paper-deployment
  labels:
    app: paper
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
spec:
  replicas: {{ .Values.paper.replicaCount }}
  selector:
    matchLabels:
      app: paper
      component: api
      tier: backend
      environment: {{ .Values.global.environment }}
  template:
    metadata:
      labels:
        app: paper
        component: api
        tier: backend
        environment: {{ .Values.global.environment }}
    spec:
      {{- if .Values.paperDb.enabled }}
      initContainers:
        - name: wait-for-paper-db
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z external-paper-db-service {{ .Values.paper.config.PAPER_DB_PORT }}; do
                echo "Waiting for PostgreSQL...";
                sleep 4;
              done
      {{- end }}
      containers:
        - name: paper
          image: {{ .Values.paper.image.repository }}:{{ .Values.paper.image.tag }}
          envFrom:
            - configMapRef:
                name: paper-config
            - secretRef:
                name: paper-secret
          ports:
            - containerPort: {{ .Values.paper.service.targetPort }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          {{- with .Values.paper.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.paper.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.paper.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.paper.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
