{{- if .Values.paper.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paper-externalsecret
  labels:
    app: paper
    component: externalsecret
    tier: backend
    environment: {{ .Values.global.environment }}
spec:
  refreshPolicy: Periodic
  refreshInterval: 2h
  secretStoreRef:
    name: {{ .Values.externalSecrets.vault.name }}
    kind: ClusterSecretStore
  target:
    name: paper-secret
    creationPolicy: Owner
  data:
    - secretKey: PAPER_DB_USER
      remoteRef:
        key: paper
        property: db-user
    - secretKey: PAPER_DB_PASS
      remoteRef:
        key: paper
        property: db-pass
    - secretKey: EXAM_API_TOKEN
      remoteRef:
        key: paper
        property: exam-api-token
{{- end }}
