apiVersion: v1
kind: Secret
metadata:
  name: paper-secret
  labels:
    app: paper
    component: secrets
    tier: backend
    environment: development
type: Opaque
stringData:
  PAPER_DB_USER: "postgres"
  PAPER_DB_PASS: "postgres"

  EXAM_API_TOKEN: "very-very-top-secret-exam-api-token"
