{{- if .Values.paper.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: paper-secret
  labels:
    app: paper
    component: secrets
    tier: backend
    environment: {{ .Values.global.environment }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.paper.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
