{{- if .Values.paper.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: paper-service
  labels:
    app: paper
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
spec:
  type: {{ .Values.paper.service.type }}
  ports:
    - port: {{ .Values.paper.service.port }}
      targetPort: {{ .Values.paper.service.targetPort }}
  selector:
    app: paper
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
{{- end }}
