# Base configuration
ARG node_tag=22-alpine
FROM node:${node_tag} AS base
WORKDIR /app

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

COPY package.json pnpm-lock.yaml .npmrc /app/
RUN npm i -g --force corepack && corepack enable

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile --shamefully-hoist

#ARG NUXT_UI_PRO_LICENSE
#ENV NUXT_UI_PRO_LICENSE=$NUXT_UI_PRO_LICENSE

COPY . .

EXPOSE 3000

CMD [ "pnpm", "dev" ]
