services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "3010:80"
      - "3000:443"
    volumes:
      - ./docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${CERT_PATH}:/etc/ssl/certs/cert.pem
      - ${CERT_KEY_PATH}:/etc/ssl/private/key.pem
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - nginx-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  frontend:
    networks:
      - nginx-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  backend:
    depends_on:
      paper:
        condition: service_started
      exam:
        condition: service_started
      engine:
        condition: service_started
    networks:
      - nginx-network
      - backend-network
      - global_auth-network

  paper:
    depends_on:
      papersDb:
        condition: service_healthy
    networks:
      - backend-network
      - paper-network
      - exam-paper-network

  exam:
    depends_on:
      examsDb:
        condition: service_healthy
      commonQueue:
        condition: service_healthy
      paper:
        condition: service_started
    networks:
      - backend-network
      - exam-network
      - exam-paper-network
      - common-queue-network

  engine:
    depends_on:
      paper:
        condition: service_started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/data/engineTmp/tmp:/tmp
    networks:
      - backend-network
      - engine-paper-network

  # A common message queue for all services
  commonQueue:
    image: redis:7-alpine
    container_name: common_queue
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    expose:
      - "6379"
    volumes:
      - ./docker/data/commonQueue/:/data
      - ./docker/conf/commonQueue/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - common-queue-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  papersDb:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_PAPERS}
    volumes:
      - ./docker/data/papersDb:/var/lib/postgresql/data
    networks:
      - paper-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  examsDb:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_EXAMS}
    volumes:
      - ./docker/data/examsDb:/var/lib/postgresql/data
    networks:
      - exam-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  examWorker:
    depends_on:
      commonQueue:
        condition: service_healthy
      examsDb:
        condition: service_healthy
      papersDb:
        condition: service_healthy
    networks:
      - exam-network
      - paper-network
      - common-queue-network

networks:
  global_auth-network:
    external: true
  global_mail-network:
    external: true
  nginx-network:
    name: nginx-network
  backend-network:
    name: backend-network
  common-queue-network:
    name: common-queue-network
  paper-network:
    name: paper-network
  exam-network:
    name: exam-network
  exam-paper-network:
    name: exam-paper-network
  engine-paper-network:
    name: engine-paper-network
