services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "3000:80"
    volumes:
      - ./docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - frontend-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  frontend:
    networks:
      - frontend-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  backend:
    depends_on:
      auth:
        condition: service_started
      paper:
        condition: service_started
      exam:
        condition: service_started
      engine:
        condition: service_started
    networks:
      - frontend-network
      - backend-network

  auth:
    depends_on:
      usersDb:
        condition: service_healthy
      mailQueue:
        condition: service_healthy
    networks:
      - backend-network
      - auth-network

  paper:
    depends_on:
      papersDb:
        condition: service_healthy
    networks:
      - backend-network
      - papers-network

  exam:
    depends_on:
      examsDb:
        condition: service_healthy
      examQueue:
        condition: service_healthy
    networks:
      - backend-network
      - exams-network

  engine:
    depends_on:
      papersDb:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/data/engineTmp/tmp:/tmp
    networks:
      - backend-network
      - engine-network

  mailWorker:
    depends_on:
      mailQueue:
        condition: service_healthy
    networks:
      - mail-network

  sessionsCron:
    depends_on:
      usersDb:
        condition: service_healthy
    networks:
      - auth-network

  mailQueue:
    image: rabbitmq:3-management-alpine
    container_name: mail_queue
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 15s
      timeout: 70s
      retries: 3
    volumes:
     - ./docker/data/mailQueue/:/var/lib/rabbitmq/mnesia/
     - ./docker/conf/mailQueue/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: always
    networks:
      - auth-network
      - mail-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  examQueue:
    volumes:
      - ./docker/data/examQueue/:/data
      - ./docker/conf/examQueue/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - exams-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  usersDb:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_USERS}
    volumes:
      - ./docker/data/usersDb:/var/lib/postgresql/data
    networks:
      - auth-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  papersDb:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_PAPERS}
    volumes:
      - ./docker/data/papersDb:/var/lib/postgresql/data
    networks:
      - papers-network
      - engine-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  examsDb:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_EXAMS}
    volumes:
      - ./docker/data/examsDb:/var/lib/postgresql/data
    networks:
      - exams-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  examWorker:
    depends_on:
      examQueue:
        condition: service_healthy
      examsDb:
        condition: service_healthy
      papersDb:
        condition: service_healthy
    networks:
      - exams-network
      - papers-network

networks:
  frontend-network:
    name: frontend-network
  backend-network:
    name: backend-network
  auth-network:
    name: auth-network
  mail-network:
    name: mail-network
  papers-network:
    name: papers-network
  exams-network:
    name: exams-network
  engine-network:
    name: engine-network
