services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: server
    container_name: server
    env_file:
      - docker/env/server.env
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
      sessionsDb:
        condition: service_healthy
      rabbit:
        condition: service_started
    networks:
      - pariksha-network
    develop:
      watch:
        - action: rebuild
          path: ./server/internal
          target: /app/server/internal
        - action: rebuild
          path: ./server/cmd
          target: /app/server/cmd
        - action: rebuild
          path: ./server/go.mod
        - action: rebuild
          path: ./server/go.sum

  mail:
    build:
      context: .
      dockerfile: ./mail/Dockerfile
    image: worker__mail
    container_name: worker__mail
    env_file:
      - docker/env/mail.env
    depends_on:
      rabbit:
        condition: service_started
    networks:
      - pariksha-network
    develop:
      watch:
        - action: rebuild
          path: ./mail/internal
          target: /app/mail/internal
        - action: rebuild
          path: ./mail/cmd
          target: /app/mail/cmd
        - action: rebuild
          path: ./mail/go.mod
        - action: rebuild
          path: ./mail/go.sum

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    volumes:
     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
     - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: always
    networks:
      - pariksha-network

  db:
    image: postgres:15.10
    restart: always
    container_name: db
    env_file:
      - docker/env/pg.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "5432"
    ports:
      - 6000:5432 # needed for pgAdmin
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data
    networks:
      - pariksha-network

  sessionsDb:
    image: postgres:15.10
    restart: always
    container_name: db__sessions
    env_file:
      - docker/env/sessionsDb.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_SESSIONS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_SESSIONS}"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "5432"
    ports:
      - 6010:5432 # needed for pgAdmin
    volumes:
      - ./docker/data/sessionsDb:/var/lib/postgresql/data
    networks:
      - pariksha-network

networks:
  pariksha-network:
