services:
  server:
    build:
      context: ./backend
      dockerfile: ./server/Dockerfile
    image: pariksha_server
    container_name: server
    env_file:
      - docker/env/server.env
    expose:
      - "4000"
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
      auth:
        condition: service_started
    networks:
      - pariksha-network
    develop:
      watch:
        - action: rebuild
          path: ./backend/server/internal
        - action: rebuild
          path: ./backend/server/cmd
        - action: rebuild
          path: ./backend/common
        - action: rebuild
          path: ./backend/server/go.mod
        - action: rebuild
          path: ./backend/server/go.sum

  auth:
    build:
      context: ./backend
      dockerfile: ./auth/Dockerfile
    image: pariksha_auth_service
    container_name: auth_service
    env_file:
      - docker/env/auth.env
    depends_on:
      db:
        condition: service_healthy
      sessionsDb:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    networks:
      - pariksha-network
    develop:
      watch:
        - action: rebuild
          path: ./backend/auth/internal
        - action: rebuild
          path: ./backend/auth/cmd
        - action: rebuild
          path: ./backend/common
        - action: rebuild
          path: ./auth/go.mod
        - action: rebuild
          path: ./backend/auth/go.sum

  mail:
    build:
      context: ./backend
      dockerfile: ./mail/Dockerfile
    image: pariksha_mail_worker
    container_name: mail_worker
    env_file:
      - docker/env/mail.env
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - pariksha-network
    develop:
      watch:
        - action: rebuild
          path: ./backend/mail/internal
        - action: rebuild
          path: ./backend/mail/cmd
        - action: rebuild
          path: ./backend/common
        - action: rebuild
          path: ./backend/mail/go.mod
        - action: rebuild
          path: ./backend/mail/go.sum

  sessionsCron:
    build:
      context: ./backend
      dockerfile: ./cron/sessions/Dockerfile
    image: pariksha_sessions_cron
    container_name: sessions_cron
    env_file:
      - docker/env/cron-sessions.env
    depends_on:
      sessionsDb:
        condition: service_healthy
    networks:
      - pariksha-network
    develop:
      watch:
        - action: rebuild
          path: ./backend/cron/sessions/internal
        - action: rebuild
          path: ./backend/cron/sessions/cmd
        - action: rebuild
          path: ./backend/common
        - action: rebuild
          path: ./backend/cron/sessions/go.mod
        - action: rebuild
          path: ./backend/cron/sessions/go.sum

  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: rabbit
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 15s
      timeout: 70s
      retries: 3
    volumes:
     - ./docker/data/rabbit/:/var/lib/rabbitmq/mnesia/
     - ./docker/conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: always
    networks:
      - pariksha-network

  db:
    image: postgres:15.10-alpine
    restart: always
    container_name: db
    env_file:
      - docker/env/pg.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "5432"
    ports:
      - 6000:5432 # needed for pgAdmin
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data
    networks:
      - pariksha-network

  sessionsDb:
    image: postgres:15.10-alpine
    restart: always
    container_name: sessions_db
    env_file:
      - docker/env/sessionsDb.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_SESSIONS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_SESSIONS}"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "5432"
    ports:
      - 6010:5432 # needed for pgAdmin
    volumes:
      - ./docker/data/sessionsDb:/var/lib/postgresql/data
    networks:
      - pariksha-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ${FRONTEND_DOCKERFILE}
    image: pariksha_frontend
    container_name: frontend
    env_file:
      - docker/env/frontend.env
    expose:
      - "3000"
    ports:
      - 3000:3000
    volumes:
      - ./frontend/.nuxt:/app/.nuxt
    networks:
      - pariksha-network
    stdin_open: true
    tty: true
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: sync
          path: ./frontend/nuxt.config.ts
          target: /app/nuxt.config.ts
        - action: sync
          path: ./frontend/tailwind.config.ts
          target: /app/tailwind.config.ts
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/package-lock.json

networks:
  pariksha-network:
