services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: server
    container_name: server
    env_file:
      - docker-env/server.env
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
      mail:
        condition: service_started
    networks:
      - pariksha-network
    develop:
      watch:
        - action: rebuild
          path: ./server/internal
          target: /app/server/internal
        - action: rebuild
          path: ./server/cmd
          target: /app/server/cmd
        - action: rebuild
          path: ./server/go.mod
        - action: rebuild
          path: ./server/go.sum

  mail:
    build:
      context: .
      dockerfile: ./mail/Dockerfile
    image: service__mail
    container_name: service__mail
    env_file:
      - docker-env/mail.env
    ports:
      - 4010:4010
    networks:
      - pariksha-network
    develop:
      watch:
        - action: rebuild
          path: ./mail/internal
          target: /app/mail/internal
        - action: rebuild
          path: ./mail/cmd
          target: /app/mail/cmd
        - action: rebuild
          path: ./mail/go.mod
        - action: rebuild
          path: ./mail/go.sum

  db:
    image: postgres:15.10
    restart: always
    container_name: db
    env_file:
      - docker-env/pg.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "5432"
    ports:
      - 6000:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    networks:
      - pariksha-network

volumes:
  pg-data:

networks:
  pariksha-network:
