services:
  mail:
    build:
      context: .
      dockerfile: ./mail/Dockerfile
    image: pariksha_mail_worker
    container_name: mail_worker
    env_file:
      - ./mail/.env
    develop:
      watch:
        - action: rebuild
          path: ./mail/internal
        - action: rebuild
          path: ./mail/cmd
        - action: rebuild
          path: ./backend/common
        - action: rebuild
          path: ./mail/go.mod
        - action: rebuild
          path: ./mail/go.sum
