services:
  mailWorker:
    build:
      context: .
      dockerfile: ./workers/mail/Dockerfile
    image: pariksha_mail_worker
    container_name: mail_worker
    env_file:
      - ./workers/mail/.env
    develop:
      watch:
        - action: rebuild
          path: ./workers/mail/internal
        - action: rebuild
          path: ./workers/mail/cmd
        - action: rebuild
          path: ./common
        - action: rebuild
          path: ./workers/mail/go.mod
        - action: rebuild
          path: ./workers/mail/go.sum
