apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # https://github.com/nuxt/icon?tab=readme-ov-file#icon-customization
          - path: /api/_nuxt_icon/
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  name: entrypoint

          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  name: entrypoint

          # https://github.com/nuxt/nuxt/issues/12003#issuecomment-1397230032
          - path: /_nuxt/hmr/
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  name: entrypoint

          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  name: entrypoint
