worker_processes 1;

events {
    worker_connections 1024;
}

http {
    # HTTP server: redirects all traffic to HTTPS
    server {
        listen 80;
        server_name pariksha;

        # Port specified for local
        return 301 https://$host:3000$request_uri;
    }

    # HTTPS server
    server {
        listen 443 ssl;
        server_name pariksha;

        ssl_certificate /etc/ssl/certs/cert.pem;
        ssl_certificate_key /etc/ssl/private/key.pem;

        # Only allow secure TLS versions (disable SSLv3, TLSv1.0, and TLSv1.1)
        # TLSv1.3 is preferred; TLSv1.2 is allowed for older clients
        ssl_protocols TLSv1.3 TLSv1.2;

        # Enforce HTTPS usage with HSTS
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

        # https://github.com/nuxt/icon?tab=readme-ov-file#icon-customization
        location /api/_nuxt_icon/ {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/ {
            proxy_pass http://backend:4000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # https://github.com/nuxt/nuxt/issues/12003#issuecomment-1397230032
        location /_nuxt/hmr/ {
            proxy_pass http://frontend:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
