{{- if and .Values.externalSecrets.enabled .Values.ingress.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ingress-tls-externalsecret
  labels:
    app: {{ .Chart.Name }}
    component: ingress-tls
    environment: {{ .Values.global.environment }}
spec:
  refreshPolicy: Periodic
  refreshInterval: 2h
  secretStoreRef:
    name: {{ .Values.externalSecrets.vault.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.ingress.tlsSecret }}
    creationPolicy: Owner
    template:
      # k8s TLS secret which Ingress expects
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: certs
        property: certificate
    - secretKey: tls.key
      remoteRef:
        key: certs
        property: private_key
{{- end }}
