{{- if and .Values.externalSecrets.enabled .Values.mail.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mail-externalsecret
  labels:
    app: mail
    component: externalsecret
    tier: backend
    environment: {{ .Values.global.environment }}
spec:
  refreshPolicy: Periodic
  refreshInterval: 2h
  secretStoreRef:
    name: {{ .Values.externalSecrets.vault.name }}
    kind: ClusterSecretStore
  target:
    name: mail-secret
    creationPolicy: Owner
  data:
    - secretKey: SMTP_FROM
      remoteRef:
        key: mail
        property: smtp-from
    - secretKey: SMTP_USER
      remoteRef:
        key: mail
        property: smtp-user
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: mail
        property: smtp-password
    - secretKey: SMTP_HOST
      remoteRef:
        key: mail
        property: smtp-host
{{- end }}
