syntax = "proto3";

package proto;

option go_package = "/api";

service MailService {
  rpc SendVerificationMail(SendVerificationMailRequest) returns (MailResponse);
  rpc SendLoginOtpMail(SendLoginOtpMailRequest) returns (MailResponse);
  rpc SendForgotPasswordMail(SendForgotPasswordMailRequest) returns (MailResponse);
  rpc SendResetPasswordSuccessMail(SendResetPasswordSuccessMailRequest) returns (MailResponse);
}

message SendVerificationMailRequest {
  string to = 1;
  string otp = 2;
  int32 expiresInMinutes = 3;
}

message SendLoginOtpMailRequest {
  string to = 1;
  string otp = 2;
  int32 expiresInMinutes = 3;
}

message SendForgotPasswordMailRequest {
  string to = 1;
  string otp = 2;
  int32 expiresInMinutes = 3;
}

message SendResetPasswordSuccessMailRequest {
  string to = 1;
}

message MailResponse {
  bool success = 1;
  string error = 2;
}