{{- if .Values.examWorker.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: exam-worker-config
data:
  GO_ENV: {{ .Values.global.environment }}

  EXAM_DB_NAME: {{ .Values.examWorker.config.EXAM_DB_NAME }}
  EXAM_DB_SSLMODE: {{ .Values.examWorker.config.EXAM_DB_SSLMODE }}

  EXAM_QUEUE_HOST: {{ .Values.examWorker.config.EXAM_QUEUE_HOST }}
  EXAM_QUEUE_PORT: {{ .Values.examWorker.config.EXAM_QUEUE_PORT | quote }}

  PAPER_SERVER_HOST: {{ .Values.examWorker.config.PAPER_SERVER_HOST }}
  PAPER_SERVER_PORT: {{ .Values.examWorker.config.PAPER_SERVER_PORT | quote }}

  QUESTION_SERVER_HOST: {{ .Values.examWorker.config.QUESTION_SERVER_HOST }}
  QUESTION_SERVER_PORT: {{ .Values.examWorker.config.QUESTION_SERVER_PORT | quote }}
{{- end }}
