{{- if .Values.examWorker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-worker-deployment
  labels:
    app: exam-worker
    component: worker
    tier: backend
    environment: {{ .Values.global.environment }}
spec:
  replicas: {{ .Values.examWorker.replicaCount }}
  selector:
    matchLabels:
      app: exam-worker
      component: worker
      tier: backend
      environment: {{ .Values.global.environment }}
  template:
    metadata:
      labels:
        app: exam-worker
        component: worker
        tier: backend
        environment: {{ .Values.global.environment }}
    spec:
      initContainers:
        - name: wait-for-exam-queue
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z {{ .Values.examWorker.config.EXAM_QUEUE_HOST }} {{ .Values.examWorker.config.EXAM_QUEUE_PORT }}; do
                echo "Waiting for Exam Queue...";
                sleep 4;
              done

      containers:
        - name: exam-worker
          image: {{ .Values.examWorker.image.repository }}:{{ .Values.examWorker.image.tag }}
          envFrom:
            - configMapRef:
                name: exam-worker-config
            - secretRef:
                name: exam-worker-secret
          ports:
            - containerPort: {{ .Values.examWorker.service.targetPort }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
{{- end }}
