{{- if .Values.examWorker.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: exam-worker-service
  labels:
    app: exam-worker
    component: worker
    tier: backend
    environment: {{ .Values.global.environment }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.examWorker.service.port }}
      targetPort: {{ .Values.examWorker.service.targetPort }}
  selector:
    app: exam-worker
    component: worker
    tier: backend
    environment: {{ .Values.global.environment }}
{{- end }}
