{{- if .Values.examDb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: external-exam-db-service
  labels:
    app: exam
    component: api
    tier: database
    environment: {{ .Values.global.environment }}
spec:
  type: ExternalName
  externalName: {{ .Values.examDb.externalName }}
{{- end }}
