{{- if .Values.exam.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-deployment
  labels:
    app: exam
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
spec:
  replicas: {{ .Values.exam.replicaCount }}
  selector:
    matchLabels:
      app: exam
      component: api
      tier: backend
      environment: {{ .Values.global.environment }}
  template:
    metadata:
      labels:
        app: exam
        component: api
        tier: backend
        environment: {{ .Values.global.environment }}
    spec:
      {{- if or .Values.examDb.enabled .Values.examQueue.enabled }}
      initContainers:
        {{- if .Values.examDb.enabled }}
        - name: wait-for-exam-db
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z {{ .Values.exam.config.EXAM_DB_ADDR }}; do
                echo "Waiting for PostgreSQL...";
                sleep 4;
              done
        {{- end }}
        {{- if .Values.examQueue.enabled }}
        - name: wait-for-exam-queue
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z exam-queue-service {{ .Values.examQueue.service.port }}; do
                echo "Waiting for Exam Queue...";
                sleep 4;
              done
        {{- end }}
      {{- end }}
      containers:
        - name: exam
          image: {{ .Values.exam.image.repository }}:{{ .Values.exam.image.tag }}
          envFrom:
            - configMapRef:
                name: exam-config
            - secretRef:
                name: exam-secret
          ports:
            - containerPort: {{ .Values.exam.service.targetPort }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          {{- with .Values.exam.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.exam.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.exam.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.exam.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
