{{- if .Values.exam.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: exam-externalsecret
  labels:
    app: exam
    component: externalsecret
    tier: backend
    environment: {{ .Values.global.environment }}
spec:
  refreshPolicy: Periodic
  refreshInterval: 2h
  secretStoreRef:
    name: {{ .Values.externalSecrets.vault.name }}
    kind: ClusterSecretStore
  target:
    name: exam-secret
    creationPolicy: Owner
  data:
    - secretKey: EXAM_DB_USER
      remoteRef:
        key: exam
        property: db-user
    - secretKey: EXAM_DB_PASS
      remoteRef:
        key: exam
        property: db-pass
    - secretKey: EXAM_API_TOKEN
      remoteRef:
        key: exam
        property: api-token
{{- end }}
