apiVersion: v1
kind: Secret
metadata:
  name: exam-secret
  labels:
    app: exam
    component: secrets
    tier: backend
    environment: development
type: Opaque
stringData:
  EXAM_DB_USER: "postgres"
  EXAM_DB_PASS: "postgres"

  EXAM_API_TOKEN: "very-very-top-secret-exam-api-token"
