{{- if .Values.exam.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: exam-secret
  labels:
    app: exam
    component: secrets
    tier: backend
    environment: {{ .Values.global.environment }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.exam.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
