{{- if .Values.exam.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: exam-service
  labels:
    app: exam
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
spec:
  type: {{ .Values.exam.service.type }}
  ports:
    - port: {{ .Values.exam.service.port }}
      targetPort: {{ .Values.exam.service.targetPort }}
  selector:
    app: exam
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
{{- end }}
