{{- if .Values.engine.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: engine-config
  labels:
    app: engine
    component: config
    tier: backend
    environment: {{ .Values.global.environment }}
data:
  {{- range $key, $value := .Values.engine.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
