{{- if .Values.engine.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-deployment
  labels:
    app: engine
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
spec:
  replicas: {{ .Values.engine.replicaCount }}
  selector:
    matchLabels:
      app: engine
      component: api
      tier: backend
      environment: {{ .Values.global.environment }}
  template:
    metadata:
      labels:
        app: engine
        component: api
        tier: backend
        environment: {{ .Values.global.environment }}
    spec:
      serviceAccountName: engine-serviceaccount
      containers:
        - name: engine
          image: {{ .Values.engine.image.repository }}:{{ .Values.engine.image.tag }}
          envFrom:
            - configMapRef:
                name: engine-config
            - secretRef:
                name: engine-secret
          ports:
            - containerPort: {{ .Values.engine.service.targetPort }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          {{- with .Values.engine.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.engine.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.engine.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.engine.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
