{{- if .Values.engine.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: engine-externalsecret
  labels:
    app: engine
    component: externalsecret
    tier: backend
    environment: {{ .Values.global.environment }}
spec:
  refreshPolicy: Periodic
  refreshInterval: 2h
  secretStoreRef:
    name: {{ .Values.externalSecrets.vault.name }}
    kind: ClusterSecretStore
  target:
    name: engine-secret
    creationPolicy: Owner
  data:
    - secretKey: ENGINE_API_TOKEN
      remoteRef:
        key: engine
        property: api-token
{{- end }}
