{{- if .Values.engine.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: engine-image-pull-secret
  labels:
    app: engine
    component: secret
    tier: backend
    environment: {{ .Values.global.environment }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {}}" | b64enc }}
{{- end }}
