{{- if .Values.engine.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: engine-role
  labels:
    app: engine
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "configmaps"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: engine-rolebinding
  labels:
    app: engine
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
subjects:
  - kind: ServiceAccount
    name: engine-serviceaccount
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: engine-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
