apiVersion: v1
kind: Secret
metadata:
  name: engine-secret
  labels:
    app: engine
    component: secrets
    tier: backend
    environment: development
type: Opaque
stringData:
  ENGINE_API_TOKEN: "very-very-top-secret-engine-api-token"
