{{- if .Values.engine.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: engine-secret
  labels:
    app: engine
    component: secrets
    tier: backend
    environment: {{ .Values.global.environment }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.engine.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
