apiVersion: v1
kind: Service
metadata:
  name: engine-service
  labels:
    app: engine
    component: api
    tier: backend
    environment: development
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: engine
    component: api
    tier: backend
    environment: development
