{{- if .Values.engine.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: engine-service
  labels:
    app: engine
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
spec:
  type: {{ .Values.engine.service.type }}
  ports:
    - port: {{ .Values.engine.service.port }}
      targetPort: {{ .Values.engine.service.targetPort }}
  selector:
    app: engine
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
{{- end }}
