apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  labels:
    app: gateway
    component: config
    tier: backend
    environment: development
data:
  GO_ENV: "development"
  API_PORT: "4000"

  AUTH_SERVER_HOST: "host.docker.internal"
  AUTH_SERVER_PORT: "4000"

  PAPER_SERVER_HOST: "paper-service"
  PAPER_SERVER_PORT: "4000"

  EXAM_SERVER_HOST: "exam-service"
  EXAM_SERVER_PORT: "4000"

  ENGINE_SERVER_HOST: "engine-service"
  ENGINE_SERVER_PORT: "4000"

  CLIENT_URL: "https://localhost/3000"
