apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
    component: api
    tier: backend
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      component: api
      tier: backend
      environment: development
  template:
    metadata:
      labels:
        app: gateway
        component: api
        tier: backend
        environment: development
    spec:
      containers:
        - name: gateway
          image: pariksha_backend
          envFrom:
            - configMapRef:
                name: gateway-config
          ports:
            - containerPort: 4000
          imagePullPolicy: Never
