apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway
    component: api
    tier: backend
    environment: development
spec:
  type: ClusterIP
  ports:
    - name: entrypoint
      port: 4000
      targetPort: 4000
  selector:
    app: gateway
    component: api
    tier: backend
    environment: development
