// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: exam.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExamService_GetUserExams_FullMethodName               = "/proto.ExamService/GetUserExams"
	ExamService_CreateExam_FullMethodName                 = "/proto.ExamService/CreateExam"
	ExamService_UpdateExam_FullMethodName                 = "/proto.ExamService/UpdateExam"
	ExamService_GetExam_FullMethodName                    = "/proto.ExamService/GetExam"
	ExamService_GetExamQuestions_FullMethodName           = "/proto.ExamService/GetExamQuestions"
	ExamService_GetExamCategories_FullMethodName          = "/proto.ExamService/GetExamCategories"
	ExamService_GetExamPermission_FullMethodName          = "/proto.ExamService/GetExamPermission"
	ExamService_GetExamParticipants_FullMethodName        = "/proto.ExamService/GetExamParticipants"
	ExamService_AddExamParticipant_FullMethodName         = "/proto.ExamService/AddExamParticipant"
	ExamService_RemoveExamParticipant_FullMethodName      = "/proto.ExamService/RemoveExamParticipant"
	ExamService_StartExam_FullMethodName                  = "/proto.ExamService/StartExam"
	ExamService_EndExam_FullMethodName                    = "/proto.ExamService/EndExam"
	ExamService_GetExamParticipant_FullMethodName         = "/proto.ExamService/GetExamParticipant"
	ExamService_GetParticipantAnswers_FullMethodName      = "/proto.ExamService/GetParticipantAnswers"
	ExamService_GetAnswerForExam_FullMethodName           = "/proto.ExamService/GetAnswerForExam"
	ExamService_UpsertAnswer_FullMethodName               = "/proto.ExamService/UpsertAnswer"
	ExamService_GetAnswerForEvaluation_FullMethodName     = "/proto.ExamService/GetAnswerForEvaluation"
	ExamService_UpdateAnswerForEvaluation_FullMethodName  = "/proto.ExamService/UpdateAnswerForEvaluation"
	ExamService_MarkParticipantAsEvaluated_FullMethodName = "/proto.ExamService/MarkParticipantAsEvaluated"
)

// ExamServiceClient is the client API for ExamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExamServiceClient interface {
	// Exam operations
	GetUserExams(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ExamList, error)
	CreateExam(ctx context.Context, in *CreateExamRequest, opts ...grpc.CallOption) (*ExamResponse, error)
	UpdateExam(ctx context.Context, in *UpdateExamRequest, opts ...grpc.CallOption) (*ExamResponse, error)
	GetExam(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamResponse, error)
	GetExamQuestions(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamQuestionsResponse, error)
	GetExamCategories(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamCategoriesResponse, error)
	GetExamPermission(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamPermissionResponse, error)
	// Participant operations
	GetExamParticipants(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ParticipantList, error)
	AddExamParticipant(ctx context.Context, in *AddParticipantRequest, opts ...grpc.CallOption) (*ParticipantResponse, error)
	RemoveExamParticipant(ctx context.Context, in *RemoveParticipantRequest, opts ...grpc.CallOption) (*Empty, error)
	StartExam(ctx context.Context, in *StartExamRequest, opts ...grpc.CallOption) (*Empty, error)
	EndExam(ctx context.Context, in *EndExamRequest, opts ...grpc.CallOption) (*Empty, error)
	GetExamParticipant(ctx context.Context, in *GetExamParticipantRequest, opts ...grpc.CallOption) (*GetExamParticipantResponse, error)
	// Answer operations
	GetParticipantAnswers(ctx context.Context, in *ParticipantRequest, opts ...grpc.CallOption) (*AnswerList, error)
	GetAnswerForExam(ctx context.Context, in *GetAnswerRequest, opts ...grpc.CallOption) (*GetAnswerResponse, error)
	UpsertAnswer(ctx context.Context, in *UpsertAnswersRequest, opts ...grpc.CallOption) (*UpsertAnswersResponse, error)
	// Evaluation
	GetAnswerForEvaluation(ctx context.Context, in *GetAnswerForEvaluationRequest, opts ...grpc.CallOption) (*GetAnswerForEvaluationResponse, error)
	UpdateAnswerForEvaluation(ctx context.Context, in *UpdateAnswerRequest, opts ...grpc.CallOption) (*Empty, error)
	MarkParticipantAsEvaluated(ctx context.Context, in *ParticipantRequest, opts ...grpc.CallOption) (*EvaluationStatusResponse, error)
}

type examServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExamServiceClient(cc grpc.ClientConnInterface) ExamServiceClient {
	return &examServiceClient{cc}
}

func (c *examServiceClient) GetUserExams(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ExamList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExamList)
	err := c.cc.Invoke(ctx, ExamService_GetUserExams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examServiceClient) CreateExam(ctx context.Context, in *CreateExamRequest, opts ...grpc.CallOption) (*ExamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExamResponse)
	err := c.cc.Invoke(ctx, ExamService_CreateExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examServiceClient) UpdateExam(ctx context.Context, in *UpdateExamRequest, opts ...grpc.CallOption) (*ExamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExamResponse)
	err := c.cc.Invoke(ctx, ExamService_UpdateExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examServiceClient) GetExam(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExamResponse)
	err := c.cc.Invoke(ctx, ExamService_GetExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examServiceClient) GetExamQuestions(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExamQuestionsResponse)
	err := c.cc.Invoke(ctx, ExamService_GetExamQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examServiceClient) GetExamCategories(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExamCategoriesResponse)
	err := c.cc.Invoke(ctx, ExamService_GetExamCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examServiceClient) GetExamPermission(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamPermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExamPermissionResponse)
	err := c.cc.Invoke(ctx, ExamService_GetExamPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examServiceClient) GetExamParticipants(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ParticipantList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParticipantList)
	err := c.cc.Invoke(ctx, ExamService_GetExamParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examServiceClient) AddExamParticipant(ctx context.Context, in *AddParticipantRequest, opts ...grpc.CallOption) (*ParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParticipantResponse)
	err := c.cc.Invoke(ctx, ExamService_AddExamParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examServiceClient) RemoveExamParticipant(ctx context.Context, in *RemoveParticipantRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ExamService_RemoveExamParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examServiceClient) StartExam(ctx context.Context, in *StartExamRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ExamService_StartExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examServiceClient) EndExam(ctx context.Context, in *EndExamRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ExamService_EndExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examServiceClient) GetExamParticipant(ctx context.Context, in *GetExamParticipantRequest, opts ...grpc.CallOption) (*GetExamParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExamParticipantResponse)
	err := c.cc.Invoke(ctx, ExamService_GetExamParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examServiceClient) GetParticipantAnswers(ctx context.Context, in *ParticipantRequest, opts ...grpc.CallOption) (*AnswerList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerList)
	err := c.cc.Invoke(ctx, ExamService_GetParticipantAnswers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examServiceClient) GetAnswerForExam(ctx context.Context, in *GetAnswerRequest, opts ...grpc.CallOption) (*GetAnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnswerResponse)
	err := c.cc.Invoke(ctx, ExamService_GetAnswerForExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examServiceClient) UpsertAnswer(ctx context.Context, in *UpsertAnswersRequest, opts ...grpc.CallOption) (*UpsertAnswersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertAnswersResponse)
	err := c.cc.Invoke(ctx, ExamService_UpsertAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examServiceClient) GetAnswerForEvaluation(ctx context.Context, in *GetAnswerForEvaluationRequest, opts ...grpc.CallOption) (*GetAnswerForEvaluationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnswerForEvaluationResponse)
	err := c.cc.Invoke(ctx, ExamService_GetAnswerForEvaluation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examServiceClient) UpdateAnswerForEvaluation(ctx context.Context, in *UpdateAnswerRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ExamService_UpdateAnswerForEvaluation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examServiceClient) MarkParticipantAsEvaluated(ctx context.Context, in *ParticipantRequest, opts ...grpc.CallOption) (*EvaluationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluationStatusResponse)
	err := c.cc.Invoke(ctx, ExamService_MarkParticipantAsEvaluated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExamServiceServer is the server API for ExamService service.
// All implementations must embed UnimplementedExamServiceServer
// for forward compatibility.
type ExamServiceServer interface {
	// Exam operations
	GetUserExams(context.Context, *Empty) (*ExamList, error)
	CreateExam(context.Context, *CreateExamRequest) (*ExamResponse, error)
	UpdateExam(context.Context, *UpdateExamRequest) (*ExamResponse, error)
	GetExam(context.Context, *ExamRequest) (*ExamResponse, error)
	GetExamQuestions(context.Context, *ExamRequest) (*ExamQuestionsResponse, error)
	GetExamCategories(context.Context, *ExamRequest) (*ExamCategoriesResponse, error)
	GetExamPermission(context.Context, *ExamRequest) (*ExamPermissionResponse, error)
	// Participant operations
	GetExamParticipants(context.Context, *ExamRequest) (*ParticipantList, error)
	AddExamParticipant(context.Context, *AddParticipantRequest) (*ParticipantResponse, error)
	RemoveExamParticipant(context.Context, *RemoveParticipantRequest) (*Empty, error)
	StartExam(context.Context, *StartExamRequest) (*Empty, error)
	EndExam(context.Context, *EndExamRequest) (*Empty, error)
	GetExamParticipant(context.Context, *GetExamParticipantRequest) (*GetExamParticipantResponse, error)
	// Answer operations
	GetParticipantAnswers(context.Context, *ParticipantRequest) (*AnswerList, error)
	GetAnswerForExam(context.Context, *GetAnswerRequest) (*GetAnswerResponse, error)
	UpsertAnswer(context.Context, *UpsertAnswersRequest) (*UpsertAnswersResponse, error)
	// Evaluation
	GetAnswerForEvaluation(context.Context, *GetAnswerForEvaluationRequest) (*GetAnswerForEvaluationResponse, error)
	UpdateAnswerForEvaluation(context.Context, *UpdateAnswerRequest) (*Empty, error)
	MarkParticipantAsEvaluated(context.Context, *ParticipantRequest) (*EvaluationStatusResponse, error)
	mustEmbedUnimplementedExamServiceServer()
}

// UnimplementedExamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExamServiceServer struct{}

func (UnimplementedExamServiceServer) GetUserExams(context.Context, *Empty) (*ExamList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserExams not implemented")
}
func (UnimplementedExamServiceServer) CreateExam(context.Context, *CreateExamRequest) (*ExamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateExam not implemented")
}
func (UnimplementedExamServiceServer) UpdateExam(context.Context, *UpdateExamRequest) (*ExamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateExam not implemented")
}
func (UnimplementedExamServiceServer) GetExam(context.Context, *ExamRequest) (*ExamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExam not implemented")
}
func (UnimplementedExamServiceServer) GetExamQuestions(context.Context, *ExamRequest) (*ExamQuestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExamQuestions not implemented")
}
func (UnimplementedExamServiceServer) GetExamCategories(context.Context, *ExamRequest) (*ExamCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExamCategories not implemented")
}
func (UnimplementedExamServiceServer) GetExamPermission(context.Context, *ExamRequest) (*ExamPermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExamPermission not implemented")
}
func (UnimplementedExamServiceServer) GetExamParticipants(context.Context, *ExamRequest) (*ParticipantList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExamParticipants not implemented")
}
func (UnimplementedExamServiceServer) AddExamParticipant(context.Context, *AddParticipantRequest) (*ParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddExamParticipant not implemented")
}
func (UnimplementedExamServiceServer) RemoveExamParticipant(context.Context, *RemoveParticipantRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveExamParticipant not implemented")
}
func (UnimplementedExamServiceServer) StartExam(context.Context, *StartExamRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartExam not implemented")
}
func (UnimplementedExamServiceServer) EndExam(context.Context, *EndExamRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndExam not implemented")
}
func (UnimplementedExamServiceServer) GetExamParticipant(context.Context, *GetExamParticipantRequest) (*GetExamParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExamParticipant not implemented")
}
func (UnimplementedExamServiceServer) GetParticipantAnswers(context.Context, *ParticipantRequest) (*AnswerList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParticipantAnswers not implemented")
}
func (UnimplementedExamServiceServer) GetAnswerForExam(context.Context, *GetAnswerRequest) (*GetAnswerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnswerForExam not implemented")
}
func (UnimplementedExamServiceServer) UpsertAnswer(context.Context, *UpsertAnswersRequest) (*UpsertAnswersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertAnswer not implemented")
}
func (UnimplementedExamServiceServer) GetAnswerForEvaluation(context.Context, *GetAnswerForEvaluationRequest) (*GetAnswerForEvaluationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnswerForEvaluation not implemented")
}
func (UnimplementedExamServiceServer) UpdateAnswerForEvaluation(context.Context, *UpdateAnswerRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAnswerForEvaluation not implemented")
}
func (UnimplementedExamServiceServer) MarkParticipantAsEvaluated(context.Context, *ParticipantRequest) (*EvaluationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkParticipantAsEvaluated not implemented")
}
func (UnimplementedExamServiceServer) mustEmbedUnimplementedExamServiceServer() {}
func (UnimplementedExamServiceServer) testEmbeddedByValue()                     {}

// UnsafeExamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExamServiceServer will
// result in compilation errors.
type UnsafeExamServiceServer interface {
	mustEmbedUnimplementedExamServiceServer()
}

func RegisterExamServiceServer(s grpc.ServiceRegistrar, srv ExamServiceServer) {
	// If the following call pancis, it indicates UnimplementedExamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExamService_ServiceDesc, srv)
}

func _ExamService_GetUserExams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).GetUserExams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_GetUserExams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).GetUserExams(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamService_CreateExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).CreateExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_CreateExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).CreateExam(ctx, req.(*CreateExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamService_UpdateExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).UpdateExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_UpdateExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).UpdateExam(ctx, req.(*UpdateExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamService_GetExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).GetExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_GetExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).GetExam(ctx, req.(*ExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamService_GetExamQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).GetExamQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_GetExamQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).GetExamQuestions(ctx, req.(*ExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamService_GetExamCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).GetExamCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_GetExamCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).GetExamCategories(ctx, req.(*ExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamService_GetExamPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).GetExamPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_GetExamPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).GetExamPermission(ctx, req.(*ExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamService_GetExamParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).GetExamParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_GetExamParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).GetExamParticipants(ctx, req.(*ExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamService_AddExamParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).AddExamParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_AddExamParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).AddExamParticipant(ctx, req.(*AddParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamService_RemoveExamParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).RemoveExamParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_RemoveExamParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).RemoveExamParticipant(ctx, req.(*RemoveParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamService_StartExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).StartExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_StartExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).StartExam(ctx, req.(*StartExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamService_EndExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).EndExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_EndExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).EndExam(ctx, req.(*EndExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamService_GetExamParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExamParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).GetExamParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_GetExamParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).GetExamParticipant(ctx, req.(*GetExamParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamService_GetParticipantAnswers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).GetParticipantAnswers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_GetParticipantAnswers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).GetParticipantAnswers(ctx, req.(*ParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamService_GetAnswerForExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).GetAnswerForExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_GetAnswerForExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).GetAnswerForExam(ctx, req.(*GetAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamService_UpsertAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertAnswersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).UpsertAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_UpsertAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).UpsertAnswer(ctx, req.(*UpsertAnswersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamService_GetAnswerForEvaluation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnswerForEvaluationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).GetAnswerForEvaluation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_GetAnswerForEvaluation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).GetAnswerForEvaluation(ctx, req.(*GetAnswerForEvaluationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamService_UpdateAnswerForEvaluation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).UpdateAnswerForEvaluation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_UpdateAnswerForEvaluation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).UpdateAnswerForEvaluation(ctx, req.(*UpdateAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamService_MarkParticipantAsEvaluated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServiceServer).MarkParticipantAsEvaluated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamService_MarkParticipantAsEvaluated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServiceServer).MarkParticipantAsEvaluated(ctx, req.(*ParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExamService_ServiceDesc is the grpc.ServiceDesc for ExamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ExamService",
	HandlerType: (*ExamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserExams",
			Handler:    _ExamService_GetUserExams_Handler,
		},
		{
			MethodName: "CreateExam",
			Handler:    _ExamService_CreateExam_Handler,
		},
		{
			MethodName: "UpdateExam",
			Handler:    _ExamService_UpdateExam_Handler,
		},
		{
			MethodName: "GetExam",
			Handler:    _ExamService_GetExam_Handler,
		},
		{
			MethodName: "GetExamQuestions",
			Handler:    _ExamService_GetExamQuestions_Handler,
		},
		{
			MethodName: "GetExamCategories",
			Handler:    _ExamService_GetExamCategories_Handler,
		},
		{
			MethodName: "GetExamPermission",
			Handler:    _ExamService_GetExamPermission_Handler,
		},
		{
			MethodName: "GetExamParticipants",
			Handler:    _ExamService_GetExamParticipants_Handler,
		},
		{
			MethodName: "AddExamParticipant",
			Handler:    _ExamService_AddExamParticipant_Handler,
		},
		{
			MethodName: "RemoveExamParticipant",
			Handler:    _ExamService_RemoveExamParticipant_Handler,
		},
		{
			MethodName: "StartExam",
			Handler:    _ExamService_StartExam_Handler,
		},
		{
			MethodName: "EndExam",
			Handler:    _ExamService_EndExam_Handler,
		},
		{
			MethodName: "GetExamParticipant",
			Handler:    _ExamService_GetExamParticipant_Handler,
		},
		{
			MethodName: "GetParticipantAnswers",
			Handler:    _ExamService_GetParticipantAnswers_Handler,
		},
		{
			MethodName: "GetAnswerForExam",
			Handler:    _ExamService_GetAnswerForExam_Handler,
		},
		{
			MethodName: "UpsertAnswer",
			Handler:    _ExamService_UpsertAnswer_Handler,
		},
		{
			MethodName: "GetAnswerForEvaluation",
			Handler:    _ExamService_GetAnswerForEvaluation_Handler,
		},
		{
			MethodName: "UpdateAnswerForEvaluation",
			Handler:    _ExamService_UpdateAnswerForEvaluation_Handler,
		},
		{
			MethodName: "MarkParticipantAsEvaluated",
			Handler:    _ExamService_MarkParticipantAsEvaluated_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exam.proto",
}
