// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: exam.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Exam_GetUserExams_FullMethodName               = "/proto.Exam/GetUserExams"
	Exam_CreateExam_FullMethodName                 = "/proto.Exam/CreateExam"
	Exam_UpdateExam_FullMethodName                 = "/proto.Exam/UpdateExam"
	Exam_GetExam_FullMethodName                    = "/proto.Exam/GetExam"
	Exam_GetExamQuestions_FullMethodName           = "/proto.Exam/GetExamQuestions"
	Exam_GetExamCategories_FullMethodName          = "/proto.Exam/GetExamCategories"
	Exam_GetExamPermission_FullMethodName          = "/proto.Exam/GetExamPermission"
	Exam_DeleteExams_FullMethodName                = "/proto.Exam/DeleteExams"
	Exam_GetExamResults_FullMethodName             = "/proto.Exam/GetExamResults"
	Exam_GetExamParticipants_FullMethodName        = "/proto.Exam/GetExamParticipants"
	Exam_AddExamParticipant_FullMethodName         = "/proto.Exam/AddExamParticipant"
	Exam_RemoveExamParticipant_FullMethodName      = "/proto.Exam/RemoveExamParticipant"
	Exam_StartExam_FullMethodName                  = "/proto.Exam/StartExam"
	Exam_EndExam_FullMethodName                    = "/proto.Exam/EndExam"
	Exam_GetExamParticipant_FullMethodName         = "/proto.Exam/GetExamParticipant"
	Exam_GetParticipantById_FullMethodName         = "/proto.Exam/GetParticipantById"
	Exam_GetParticipantAnswers_FullMethodName      = "/proto.Exam/GetParticipantAnswers"
	Exam_GetAnswerForExam_FullMethodName           = "/proto.Exam/GetAnswerForExam"
	Exam_UpsertAnswer_FullMethodName               = "/proto.Exam/UpsertAnswer"
	Exam_GetAnswerEvaluationData_FullMethodName    = "/proto.Exam/GetAnswerEvaluationData"
	Exam_UpdateAnswerForEvaluation_FullMethodName  = "/proto.Exam/UpdateAnswerForEvaluation"
	Exam_MarkParticipantAsEvaluated_FullMethodName = "/proto.Exam/MarkParticipantAsEvaluated"
	Exam_GetAnswerForEvaluation_FullMethodName     = "/proto.Exam/GetAnswerForEvaluation"
)

// ExamClient is the client API for Exam service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExamClient interface {
	// Exam operations
	GetUserExams(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ExamList, error)
	CreateExam(ctx context.Context, in *CreateExamRequest, opts ...grpc.CallOption) (*ExamResponse, error)
	UpdateExam(ctx context.Context, in *UpdateExamRequest, opts ...grpc.CallOption) (*ExamResponse, error)
	GetExam(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamResponse, error)
	GetExamQuestions(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamQuestionsResponse, error)
	GetExamCategories(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamCategoriesResponse, error)
	GetExamPermission(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamPermissionResponse, error)
	DeleteExams(ctx context.Context, in *DeleteExamsRequest, opts ...grpc.CallOption) (*Empty, error)
	GetExamResults(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamResultsResponse, error)
	// Participant operations
	GetExamParticipants(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ParticipantList, error)
	AddExamParticipant(ctx context.Context, in *AddParticipantRequest, opts ...grpc.CallOption) (*ParticipantResponse, error)
	RemoveExamParticipant(ctx context.Context, in *RemoveParticipantRequest, opts ...grpc.CallOption) (*Empty, error)
	StartExam(ctx context.Context, in *StartExamRequest, opts ...grpc.CallOption) (*Empty, error)
	EndExam(ctx context.Context, in *EndExamRequest, opts ...grpc.CallOption) (*Empty, error)
	GetExamParticipant(ctx context.Context, in *GetExamParticipantRequest, opts ...grpc.CallOption) (*GetExamParticipantResponse, error)
	GetParticipantById(ctx context.Context, in *ParticipantRequest, opts ...grpc.CallOption) (*ParticipantResponse, error)
	// Answer operations
	GetParticipantAnswers(ctx context.Context, in *ParticipantRequest, opts ...grpc.CallOption) (*AnswerList, error)
	GetAnswerForExam(ctx context.Context, in *GetAnswerRequest, opts ...grpc.CallOption) (*AnswerMinimalResponse, error)
	UpsertAnswer(ctx context.Context, in *UpsertAnswersRequest, opts ...grpc.CallOption) (*UpsertAnswersResponse, error)
	// Evaluation
	GetAnswerEvaluationData(ctx context.Context, in *ParticipantQuestionRequest, opts ...grpc.CallOption) (*GetAnswerEvaluationDataResponse, error)
	UpdateAnswerForEvaluation(ctx context.Context, in *UpdateAnswerRequest, opts ...grpc.CallOption) (*GetAnswerEvaluationDataResponse, error)
	MarkParticipantAsEvaluated(ctx context.Context, in *ParticipantRequest, opts ...grpc.CallOption) (*EvaluationStatusResponse, error)
	GetAnswerForEvaluation(ctx context.Context, in *ParticipantQuestionRequest, opts ...grpc.CallOption) (*AnswerMinimalResponse, error)
}

type examClient struct {
	cc grpc.ClientConnInterface
}

func NewExamClient(cc grpc.ClientConnInterface) ExamClient {
	return &examClient{cc}
}

func (c *examClient) GetUserExams(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ExamList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExamList)
	err := c.cc.Invoke(ctx, Exam_GetUserExams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) CreateExam(ctx context.Context, in *CreateExamRequest, opts ...grpc.CallOption) (*ExamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExamResponse)
	err := c.cc.Invoke(ctx, Exam_CreateExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) UpdateExam(ctx context.Context, in *UpdateExamRequest, opts ...grpc.CallOption) (*ExamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExamResponse)
	err := c.cc.Invoke(ctx, Exam_UpdateExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetExam(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExamResponse)
	err := c.cc.Invoke(ctx, Exam_GetExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetExamQuestions(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExamQuestionsResponse)
	err := c.cc.Invoke(ctx, Exam_GetExamQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetExamCategories(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExamCategoriesResponse)
	err := c.cc.Invoke(ctx, Exam_GetExamCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetExamPermission(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamPermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExamPermissionResponse)
	err := c.cc.Invoke(ctx, Exam_GetExamPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) DeleteExams(ctx context.Context, in *DeleteExamsRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Exam_DeleteExams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetExamResults(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ExamResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExamResultsResponse)
	err := c.cc.Invoke(ctx, Exam_GetExamResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetExamParticipants(ctx context.Context, in *ExamRequest, opts ...grpc.CallOption) (*ParticipantList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParticipantList)
	err := c.cc.Invoke(ctx, Exam_GetExamParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) AddExamParticipant(ctx context.Context, in *AddParticipantRequest, opts ...grpc.CallOption) (*ParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParticipantResponse)
	err := c.cc.Invoke(ctx, Exam_AddExamParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) RemoveExamParticipant(ctx context.Context, in *RemoveParticipantRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Exam_RemoveExamParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) StartExam(ctx context.Context, in *StartExamRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Exam_StartExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) EndExam(ctx context.Context, in *EndExamRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Exam_EndExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetExamParticipant(ctx context.Context, in *GetExamParticipantRequest, opts ...grpc.CallOption) (*GetExamParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExamParticipantResponse)
	err := c.cc.Invoke(ctx, Exam_GetExamParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetParticipantById(ctx context.Context, in *ParticipantRequest, opts ...grpc.CallOption) (*ParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParticipantResponse)
	err := c.cc.Invoke(ctx, Exam_GetParticipantById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetParticipantAnswers(ctx context.Context, in *ParticipantRequest, opts ...grpc.CallOption) (*AnswerList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerList)
	err := c.cc.Invoke(ctx, Exam_GetParticipantAnswers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetAnswerForExam(ctx context.Context, in *GetAnswerRequest, opts ...grpc.CallOption) (*AnswerMinimalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerMinimalResponse)
	err := c.cc.Invoke(ctx, Exam_GetAnswerForExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) UpsertAnswer(ctx context.Context, in *UpsertAnswersRequest, opts ...grpc.CallOption) (*UpsertAnswersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertAnswersResponse)
	err := c.cc.Invoke(ctx, Exam_UpsertAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetAnswerEvaluationData(ctx context.Context, in *ParticipantQuestionRequest, opts ...grpc.CallOption) (*GetAnswerEvaluationDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnswerEvaluationDataResponse)
	err := c.cc.Invoke(ctx, Exam_GetAnswerEvaluationData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) UpdateAnswerForEvaluation(ctx context.Context, in *UpdateAnswerRequest, opts ...grpc.CallOption) (*GetAnswerEvaluationDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnswerEvaluationDataResponse)
	err := c.cc.Invoke(ctx, Exam_UpdateAnswerForEvaluation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) MarkParticipantAsEvaluated(ctx context.Context, in *ParticipantRequest, opts ...grpc.CallOption) (*EvaluationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluationStatusResponse)
	err := c.cc.Invoke(ctx, Exam_MarkParticipantAsEvaluated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetAnswerForEvaluation(ctx context.Context, in *ParticipantQuestionRequest, opts ...grpc.CallOption) (*AnswerMinimalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerMinimalResponse)
	err := c.cc.Invoke(ctx, Exam_GetAnswerForEvaluation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExamServer is the server API for Exam service.
// All implementations must embed UnimplementedExamServer
// for forward compatibility.
type ExamServer interface {
	// Exam operations
	GetUserExams(context.Context, *Empty) (*ExamList, error)
	CreateExam(context.Context, *CreateExamRequest) (*ExamResponse, error)
	UpdateExam(context.Context, *UpdateExamRequest) (*ExamResponse, error)
	GetExam(context.Context, *ExamRequest) (*ExamResponse, error)
	GetExamQuestions(context.Context, *ExamRequest) (*ExamQuestionsResponse, error)
	GetExamCategories(context.Context, *ExamRequest) (*ExamCategoriesResponse, error)
	GetExamPermission(context.Context, *ExamRequest) (*ExamPermissionResponse, error)
	DeleteExams(context.Context, *DeleteExamsRequest) (*Empty, error)
	GetExamResults(context.Context, *ExamRequest) (*ExamResultsResponse, error)
	// Participant operations
	GetExamParticipants(context.Context, *ExamRequest) (*ParticipantList, error)
	AddExamParticipant(context.Context, *AddParticipantRequest) (*ParticipantResponse, error)
	RemoveExamParticipant(context.Context, *RemoveParticipantRequest) (*Empty, error)
	StartExam(context.Context, *StartExamRequest) (*Empty, error)
	EndExam(context.Context, *EndExamRequest) (*Empty, error)
	GetExamParticipant(context.Context, *GetExamParticipantRequest) (*GetExamParticipantResponse, error)
	GetParticipantById(context.Context, *ParticipantRequest) (*ParticipantResponse, error)
	// Answer operations
	GetParticipantAnswers(context.Context, *ParticipantRequest) (*AnswerList, error)
	GetAnswerForExam(context.Context, *GetAnswerRequest) (*AnswerMinimalResponse, error)
	UpsertAnswer(context.Context, *UpsertAnswersRequest) (*UpsertAnswersResponse, error)
	// Evaluation
	GetAnswerEvaluationData(context.Context, *ParticipantQuestionRequest) (*GetAnswerEvaluationDataResponse, error)
	UpdateAnswerForEvaluation(context.Context, *UpdateAnswerRequest) (*GetAnswerEvaluationDataResponse, error)
	MarkParticipantAsEvaluated(context.Context, *ParticipantRequest) (*EvaluationStatusResponse, error)
	GetAnswerForEvaluation(context.Context, *ParticipantQuestionRequest) (*AnswerMinimalResponse, error)
	mustEmbedUnimplementedExamServer()
}

// UnimplementedExamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExamServer struct{}

func (UnimplementedExamServer) GetUserExams(context.Context, *Empty) (*ExamList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserExams not implemented")
}
func (UnimplementedExamServer) CreateExam(context.Context, *CreateExamRequest) (*ExamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateExam not implemented")
}
func (UnimplementedExamServer) UpdateExam(context.Context, *UpdateExamRequest) (*ExamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateExam not implemented")
}
func (UnimplementedExamServer) GetExam(context.Context, *ExamRequest) (*ExamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExam not implemented")
}
func (UnimplementedExamServer) GetExamQuestions(context.Context, *ExamRequest) (*ExamQuestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExamQuestions not implemented")
}
func (UnimplementedExamServer) GetExamCategories(context.Context, *ExamRequest) (*ExamCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExamCategories not implemented")
}
func (UnimplementedExamServer) GetExamPermission(context.Context, *ExamRequest) (*ExamPermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExamPermission not implemented")
}
func (UnimplementedExamServer) DeleteExams(context.Context, *DeleteExamsRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExams not implemented")
}
func (UnimplementedExamServer) GetExamResults(context.Context, *ExamRequest) (*ExamResultsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExamResults not implemented")
}
func (UnimplementedExamServer) GetExamParticipants(context.Context, *ExamRequest) (*ParticipantList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExamParticipants not implemented")
}
func (UnimplementedExamServer) AddExamParticipant(context.Context, *AddParticipantRequest) (*ParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddExamParticipant not implemented")
}
func (UnimplementedExamServer) RemoveExamParticipant(context.Context, *RemoveParticipantRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveExamParticipant not implemented")
}
func (UnimplementedExamServer) StartExam(context.Context, *StartExamRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartExam not implemented")
}
func (UnimplementedExamServer) EndExam(context.Context, *EndExamRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndExam not implemented")
}
func (UnimplementedExamServer) GetExamParticipant(context.Context, *GetExamParticipantRequest) (*GetExamParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExamParticipant not implemented")
}
func (UnimplementedExamServer) GetParticipantById(context.Context, *ParticipantRequest) (*ParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParticipantById not implemented")
}
func (UnimplementedExamServer) GetParticipantAnswers(context.Context, *ParticipantRequest) (*AnswerList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParticipantAnswers not implemented")
}
func (UnimplementedExamServer) GetAnswerForExam(context.Context, *GetAnswerRequest) (*AnswerMinimalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnswerForExam not implemented")
}
func (UnimplementedExamServer) UpsertAnswer(context.Context, *UpsertAnswersRequest) (*UpsertAnswersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertAnswer not implemented")
}
func (UnimplementedExamServer) GetAnswerEvaluationData(context.Context, *ParticipantQuestionRequest) (*GetAnswerEvaluationDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnswerEvaluationData not implemented")
}
func (UnimplementedExamServer) UpdateAnswerForEvaluation(context.Context, *UpdateAnswerRequest) (*GetAnswerEvaluationDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAnswerForEvaluation not implemented")
}
func (UnimplementedExamServer) MarkParticipantAsEvaluated(context.Context, *ParticipantRequest) (*EvaluationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkParticipantAsEvaluated not implemented")
}
func (UnimplementedExamServer) GetAnswerForEvaluation(context.Context, *ParticipantQuestionRequest) (*AnswerMinimalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnswerForEvaluation not implemented")
}
func (UnimplementedExamServer) mustEmbedUnimplementedExamServer() {}
func (UnimplementedExamServer) testEmbeddedByValue()              {}

// UnsafeExamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExamServer will
// result in compilation errors.
type UnsafeExamServer interface {
	mustEmbedUnimplementedExamServer()
}

func RegisterExamServer(s grpc.ServiceRegistrar, srv ExamServer) {
	// If the following call pancis, it indicates UnimplementedExamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Exam_ServiceDesc, srv)
}

func _Exam_GetUserExams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetUserExams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetUserExams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetUserExams(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_CreateExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).CreateExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_CreateExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).CreateExam(ctx, req.(*CreateExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_UpdateExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).UpdateExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_UpdateExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).UpdateExam(ctx, req.(*UpdateExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetExam(ctx, req.(*ExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetExamQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetExamQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetExamQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetExamQuestions(ctx, req.(*ExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetExamCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetExamCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetExamCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetExamCategories(ctx, req.(*ExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetExamPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetExamPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetExamPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetExamPermission(ctx, req.(*ExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_DeleteExams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).DeleteExams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_DeleteExams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).DeleteExams(ctx, req.(*DeleteExamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetExamResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetExamResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetExamResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetExamResults(ctx, req.(*ExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetExamParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetExamParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetExamParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetExamParticipants(ctx, req.(*ExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_AddExamParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).AddExamParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_AddExamParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).AddExamParticipant(ctx, req.(*AddParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_RemoveExamParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).RemoveExamParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_RemoveExamParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).RemoveExamParticipant(ctx, req.(*RemoveParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_StartExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).StartExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_StartExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).StartExam(ctx, req.(*StartExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_EndExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).EndExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_EndExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).EndExam(ctx, req.(*EndExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetExamParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExamParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetExamParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetExamParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetExamParticipant(ctx, req.(*GetExamParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetParticipantById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetParticipantById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetParticipantById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetParticipantById(ctx, req.(*ParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetParticipantAnswers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetParticipantAnswers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetParticipantAnswers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetParticipantAnswers(ctx, req.(*ParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetAnswerForExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetAnswerForExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetAnswerForExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetAnswerForExam(ctx, req.(*GetAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_UpsertAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertAnswersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).UpsertAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_UpsertAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).UpsertAnswer(ctx, req.(*UpsertAnswersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetAnswerEvaluationData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParticipantQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetAnswerEvaluationData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetAnswerEvaluationData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetAnswerEvaluationData(ctx, req.(*ParticipantQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_UpdateAnswerForEvaluation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).UpdateAnswerForEvaluation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_UpdateAnswerForEvaluation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).UpdateAnswerForEvaluation(ctx, req.(*UpdateAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_MarkParticipantAsEvaluated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).MarkParticipantAsEvaluated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_MarkParticipantAsEvaluated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).MarkParticipantAsEvaluated(ctx, req.(*ParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetAnswerForEvaluation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParticipantQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetAnswerForEvaluation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetAnswerForEvaluation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetAnswerForEvaluation(ctx, req.(*ParticipantQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Exam_ServiceDesc is the grpc.ServiceDesc for Exam service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Exam_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Exam",
	HandlerType: (*ExamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserExams",
			Handler:    _Exam_GetUserExams_Handler,
		},
		{
			MethodName: "CreateExam",
			Handler:    _Exam_CreateExam_Handler,
		},
		{
			MethodName: "UpdateExam",
			Handler:    _Exam_UpdateExam_Handler,
		},
		{
			MethodName: "GetExam",
			Handler:    _Exam_GetExam_Handler,
		},
		{
			MethodName: "GetExamQuestions",
			Handler:    _Exam_GetExamQuestions_Handler,
		},
		{
			MethodName: "GetExamCategories",
			Handler:    _Exam_GetExamCategories_Handler,
		},
		{
			MethodName: "GetExamPermission",
			Handler:    _Exam_GetExamPermission_Handler,
		},
		{
			MethodName: "DeleteExams",
			Handler:    _Exam_DeleteExams_Handler,
		},
		{
			MethodName: "GetExamResults",
			Handler:    _Exam_GetExamResults_Handler,
		},
		{
			MethodName: "GetExamParticipants",
			Handler:    _Exam_GetExamParticipants_Handler,
		},
		{
			MethodName: "AddExamParticipant",
			Handler:    _Exam_AddExamParticipant_Handler,
		},
		{
			MethodName: "RemoveExamParticipant",
			Handler:    _Exam_RemoveExamParticipant_Handler,
		},
		{
			MethodName: "StartExam",
			Handler:    _Exam_StartExam_Handler,
		},
		{
			MethodName: "EndExam",
			Handler:    _Exam_EndExam_Handler,
		},
		{
			MethodName: "GetExamParticipant",
			Handler:    _Exam_GetExamParticipant_Handler,
		},
		{
			MethodName: "GetParticipantById",
			Handler:    _Exam_GetParticipantById_Handler,
		},
		{
			MethodName: "GetParticipantAnswers",
			Handler:    _Exam_GetParticipantAnswers_Handler,
		},
		{
			MethodName: "GetAnswerForExam",
			Handler:    _Exam_GetAnswerForExam_Handler,
		},
		{
			MethodName: "UpsertAnswer",
			Handler:    _Exam_UpsertAnswer_Handler,
		},
		{
			MethodName: "GetAnswerEvaluationData",
			Handler:    _Exam_GetAnswerEvaluationData_Handler,
		},
		{
			MethodName: "UpdateAnswerForEvaluation",
			Handler:    _Exam_UpdateAnswerForEvaluation_Handler,
		},
		{
			MethodName: "MarkParticipantAsEvaluated",
			Handler:    _Exam_MarkParticipantAsEvaluated_Handler,
		},
		{
			MethodName: "GetAnswerForEvaluation",
			Handler:    _Exam_GetAnswerForEvaluation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exam.proto",
}
