// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: paper.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Paper_GetUserPapers_FullMethodName          = "/proto.Paper/GetUserPapers"
	Paper_GetPaper_FullMethodName               = "/proto.Paper/GetPaper"
	Paper_CreatePaper_FullMethodName            = "/proto.Paper/CreatePaper"
	Paper_UpdatePaper_FullMethodName            = "/proto.Paper/UpdatePaper"
	Paper_DeletePapers_FullMethodName           = "/proto.Paper/DeletePapers"
	Paper_GetPaperPermissions_FullMethodName    = "/proto.Paper/GetPaperPermissions"
	Paper_GetPaperQuestions_FullMethodName      = "/proto.Paper/GetPaperQuestions"
	Paper_GetPaperQuestion_FullMethodName       = "/proto.Paper/GetPaperQuestion"
	Paper_CreatePaperQuestion_FullMethodName    = "/proto.Paper/CreatePaperQuestion"
	Paper_UpdatePaperQuestion_FullMethodName    = "/proto.Paper/UpdatePaperQuestion"
	Paper_DeletePaperQuestion_FullMethodName    = "/proto.Paper/DeletePaperQuestion"
	Paper_ReorderPaperQuestions_FullMethodName  = "/proto.Paper/ReorderPaperQuestions"
	Paper_GetPaperBoilerplate_FullMethodName    = "/proto.Paper/GetPaperBoilerplate"
	Paper_UpsertPaperTestCases_FullMethodName   = "/proto.Paper/UpsertPaperTestCases"
	Paper_GetPaperCategories_FullMethodName     = "/proto.Paper/GetPaperCategories"
	Paper_CreatePaperCategory_FullMethodName    = "/proto.Paper/CreatePaperCategory"
	Paper_UpdatePaperCategory_FullMethodName    = "/proto.Paper/UpdatePaperCategory"
	Paper_DeletePaperCategory_FullMethodName    = "/proto.Paper/DeletePaperCategory"
	Paper_ReorderPaperCategories_FullMethodName = "/proto.Paper/ReorderPaperCategories"
	Paper_GetPaperQuestionsMeta_FullMethodName  = "/proto.Paper/GetPaperQuestionsMeta"
	Paper_GetPaperCategoriesMeta_FullMethodName = "/proto.Paper/GetPaperCategoriesMeta"
)

// PaperClient is the client API for Paper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaperClient interface {
	// Paper operations
	GetUserPapers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PaperList, error)
	GetPaper(ctx context.Context, in *PaperRequest, opts ...grpc.CallOption) (*PaperResponse, error)
	CreatePaper(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CreatePaperResponse, error)
	UpdatePaper(ctx context.Context, in *UpdatePaperRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeletePapers(ctx context.Context, in *DeletePapersRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPaperPermissions(ctx context.Context, in *PaperRequest, opts ...grpc.CallOption) (*PaperPermissionsResponse, error)
	// Question operations
	GetPaperQuestions(ctx context.Context, in *PaperRequest, opts ...grpc.CallOption) (*QuestionList, error)
	GetPaperQuestion(ctx context.Context, in *PaperQuestionRequest, opts ...grpc.CallOption) (*PaperQuestionResponse, error)
	CreatePaperQuestion(ctx context.Context, in *CreatePaperQuestionRequest, opts ...grpc.CallOption) (*CreatePaperQuestionResponse, error)
	UpdatePaperQuestion(ctx context.Context, in *UpdatePaperQuestionRequest, opts ...grpc.CallOption) (*UpdatePaperQuestionResponse, error)
	DeletePaperQuestion(ctx context.Context, in *PaperQuestionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReorderPaperQuestions(ctx context.Context, in *ReorderPaperQuestionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPaperBoilerplate(ctx context.Context, in *GetPaperBoilerplateRequest, opts ...grpc.CallOption) (*BoilerplateResponse, error)
	UpsertPaperTestCases(ctx context.Context, in *UpsertPaperTestCasesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Category operations
	GetPaperCategories(ctx context.Context, in *PaperRequest, opts ...grpc.CallOption) (*PaperCategoryList, error)
	CreatePaperCategory(ctx context.Context, in *CreatePaperCategoryRequest, opts ...grpc.CallOption) (*PaperCategoryResponse, error)
	UpdatePaperCategory(ctx context.Context, in *UpdatePaperCategoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeletePaperCategory(ctx context.Context, in *PaperCategoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReorderPaperCategories(ctx context.Context, in *ReorderPaperCategoriesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Exam operations
	GetPaperQuestionsMeta(ctx context.Context, in *PaperRequest, opts ...grpc.CallOption) (*PaperQuestionsMeta, error)
	GetPaperCategoriesMeta(ctx context.Context, in *PaperRequest, opts ...grpc.CallOption) (*PaperCategoriesMeta, error)
}

type paperClient struct {
	cc grpc.ClientConnInterface
}

func NewPaperClient(cc grpc.ClientConnInterface) PaperClient {
	return &paperClient{cc}
}

func (c *paperClient) GetUserPapers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PaperList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaperList)
	err := c.cc.Invoke(ctx, Paper_GetUserPapers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) GetPaper(ctx context.Context, in *PaperRequest, opts ...grpc.CallOption) (*PaperResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaperResponse)
	err := c.cc.Invoke(ctx, Paper_GetPaper_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) CreatePaper(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CreatePaperResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaperResponse)
	err := c.cc.Invoke(ctx, Paper_CreatePaper_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) UpdatePaper(ctx context.Context, in *UpdatePaperRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Paper_UpdatePaper_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) DeletePapers(ctx context.Context, in *DeletePapersRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Paper_DeletePapers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) GetPaperPermissions(ctx context.Context, in *PaperRequest, opts ...grpc.CallOption) (*PaperPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaperPermissionsResponse)
	err := c.cc.Invoke(ctx, Paper_GetPaperPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) GetPaperQuestions(ctx context.Context, in *PaperRequest, opts ...grpc.CallOption) (*QuestionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionList)
	err := c.cc.Invoke(ctx, Paper_GetPaperQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) GetPaperQuestion(ctx context.Context, in *PaperQuestionRequest, opts ...grpc.CallOption) (*PaperQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaperQuestionResponse)
	err := c.cc.Invoke(ctx, Paper_GetPaperQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) CreatePaperQuestion(ctx context.Context, in *CreatePaperQuestionRequest, opts ...grpc.CallOption) (*CreatePaperQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaperQuestionResponse)
	err := c.cc.Invoke(ctx, Paper_CreatePaperQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) UpdatePaperQuestion(ctx context.Context, in *UpdatePaperQuestionRequest, opts ...grpc.CallOption) (*UpdatePaperQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePaperQuestionResponse)
	err := c.cc.Invoke(ctx, Paper_UpdatePaperQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) DeletePaperQuestion(ctx context.Context, in *PaperQuestionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Paper_DeletePaperQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) ReorderPaperQuestions(ctx context.Context, in *ReorderPaperQuestionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Paper_ReorderPaperQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) GetPaperBoilerplate(ctx context.Context, in *GetPaperBoilerplateRequest, opts ...grpc.CallOption) (*BoilerplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoilerplateResponse)
	err := c.cc.Invoke(ctx, Paper_GetPaperBoilerplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) UpsertPaperTestCases(ctx context.Context, in *UpsertPaperTestCasesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Paper_UpsertPaperTestCases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) GetPaperCategories(ctx context.Context, in *PaperRequest, opts ...grpc.CallOption) (*PaperCategoryList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaperCategoryList)
	err := c.cc.Invoke(ctx, Paper_GetPaperCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) CreatePaperCategory(ctx context.Context, in *CreatePaperCategoryRequest, opts ...grpc.CallOption) (*PaperCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaperCategoryResponse)
	err := c.cc.Invoke(ctx, Paper_CreatePaperCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) UpdatePaperCategory(ctx context.Context, in *UpdatePaperCategoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Paper_UpdatePaperCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) DeletePaperCategory(ctx context.Context, in *PaperCategoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Paper_DeletePaperCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) ReorderPaperCategories(ctx context.Context, in *ReorderPaperCategoriesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Paper_ReorderPaperCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) GetPaperQuestionsMeta(ctx context.Context, in *PaperRequest, opts ...grpc.CallOption) (*PaperQuestionsMeta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaperQuestionsMeta)
	err := c.cc.Invoke(ctx, Paper_GetPaperQuestionsMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paperClient) GetPaperCategoriesMeta(ctx context.Context, in *PaperRequest, opts ...grpc.CallOption) (*PaperCategoriesMeta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaperCategoriesMeta)
	err := c.cc.Invoke(ctx, Paper_GetPaperCategoriesMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaperServer is the server API for Paper service.
// All implementations must embed UnimplementedPaperServer
// for forward compatibility.
type PaperServer interface {
	// Paper operations
	GetUserPapers(context.Context, *emptypb.Empty) (*PaperList, error)
	GetPaper(context.Context, *PaperRequest) (*PaperResponse, error)
	CreatePaper(context.Context, *emptypb.Empty) (*CreatePaperResponse, error)
	UpdatePaper(context.Context, *UpdatePaperRequest) (*emptypb.Empty, error)
	DeletePapers(context.Context, *DeletePapersRequest) (*emptypb.Empty, error)
	GetPaperPermissions(context.Context, *PaperRequest) (*PaperPermissionsResponse, error)
	// Question operations
	GetPaperQuestions(context.Context, *PaperRequest) (*QuestionList, error)
	GetPaperQuestion(context.Context, *PaperQuestionRequest) (*PaperQuestionResponse, error)
	CreatePaperQuestion(context.Context, *CreatePaperQuestionRequest) (*CreatePaperQuestionResponse, error)
	UpdatePaperQuestion(context.Context, *UpdatePaperQuestionRequest) (*UpdatePaperQuestionResponse, error)
	DeletePaperQuestion(context.Context, *PaperQuestionRequest) (*emptypb.Empty, error)
	ReorderPaperQuestions(context.Context, *ReorderPaperQuestionsRequest) (*emptypb.Empty, error)
	GetPaperBoilerplate(context.Context, *GetPaperBoilerplateRequest) (*BoilerplateResponse, error)
	UpsertPaperTestCases(context.Context, *UpsertPaperTestCasesRequest) (*emptypb.Empty, error)
	// Category operations
	GetPaperCategories(context.Context, *PaperRequest) (*PaperCategoryList, error)
	CreatePaperCategory(context.Context, *CreatePaperCategoryRequest) (*PaperCategoryResponse, error)
	UpdatePaperCategory(context.Context, *UpdatePaperCategoryRequest) (*emptypb.Empty, error)
	DeletePaperCategory(context.Context, *PaperCategoryRequest) (*emptypb.Empty, error)
	ReorderPaperCategories(context.Context, *ReorderPaperCategoriesRequest) (*emptypb.Empty, error)
	// Exam operations
	GetPaperQuestionsMeta(context.Context, *PaperRequest) (*PaperQuestionsMeta, error)
	GetPaperCategoriesMeta(context.Context, *PaperRequest) (*PaperCategoriesMeta, error)
	mustEmbedUnimplementedPaperServer()
}

// UnimplementedPaperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaperServer struct{}

func (UnimplementedPaperServer) GetUserPapers(context.Context, *emptypb.Empty) (*PaperList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPapers not implemented")
}
func (UnimplementedPaperServer) GetPaper(context.Context, *PaperRequest) (*PaperResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaper not implemented")
}
func (UnimplementedPaperServer) CreatePaper(context.Context, *emptypb.Empty) (*CreatePaperResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePaper not implemented")
}
func (UnimplementedPaperServer) UpdatePaper(context.Context, *UpdatePaperRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePaper not implemented")
}
func (UnimplementedPaperServer) DeletePapers(context.Context, *DeletePapersRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePapers not implemented")
}
func (UnimplementedPaperServer) GetPaperPermissions(context.Context, *PaperRequest) (*PaperPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaperPermissions not implemented")
}
func (UnimplementedPaperServer) GetPaperQuestions(context.Context, *PaperRequest) (*QuestionList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaperQuestions not implemented")
}
func (UnimplementedPaperServer) GetPaperQuestion(context.Context, *PaperQuestionRequest) (*PaperQuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaperQuestion not implemented")
}
func (UnimplementedPaperServer) CreatePaperQuestion(context.Context, *CreatePaperQuestionRequest) (*CreatePaperQuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePaperQuestion not implemented")
}
func (UnimplementedPaperServer) UpdatePaperQuestion(context.Context, *UpdatePaperQuestionRequest) (*UpdatePaperQuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePaperQuestion not implemented")
}
func (UnimplementedPaperServer) DeletePaperQuestion(context.Context, *PaperQuestionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePaperQuestion not implemented")
}
func (UnimplementedPaperServer) ReorderPaperQuestions(context.Context, *ReorderPaperQuestionsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReorderPaperQuestions not implemented")
}
func (UnimplementedPaperServer) GetPaperBoilerplate(context.Context, *GetPaperBoilerplateRequest) (*BoilerplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaperBoilerplate not implemented")
}
func (UnimplementedPaperServer) UpsertPaperTestCases(context.Context, *UpsertPaperTestCasesRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertPaperTestCases not implemented")
}
func (UnimplementedPaperServer) GetPaperCategories(context.Context, *PaperRequest) (*PaperCategoryList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaperCategories not implemented")
}
func (UnimplementedPaperServer) CreatePaperCategory(context.Context, *CreatePaperCategoryRequest) (*PaperCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePaperCategory not implemented")
}
func (UnimplementedPaperServer) UpdatePaperCategory(context.Context, *UpdatePaperCategoryRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePaperCategory not implemented")
}
func (UnimplementedPaperServer) DeletePaperCategory(context.Context, *PaperCategoryRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePaperCategory not implemented")
}
func (UnimplementedPaperServer) ReorderPaperCategories(context.Context, *ReorderPaperCategoriesRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReorderPaperCategories not implemented")
}
func (UnimplementedPaperServer) GetPaperQuestionsMeta(context.Context, *PaperRequest) (*PaperQuestionsMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaperQuestionsMeta not implemented")
}
func (UnimplementedPaperServer) GetPaperCategoriesMeta(context.Context, *PaperRequest) (*PaperCategoriesMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaperCategoriesMeta not implemented")
}
func (UnimplementedPaperServer) mustEmbedUnimplementedPaperServer() {}
func (UnimplementedPaperServer) testEmbeddedByValue()               {}

// UnsafePaperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaperServer will
// result in compilation errors.
type UnsafePaperServer interface {
	mustEmbedUnimplementedPaperServer()
}

func RegisterPaperServer(s grpc.ServiceRegistrar, srv PaperServer) {
	// If the following call pancis, it indicates UnimplementedPaperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Paper_ServiceDesc, srv)
}

func _Paper_GetUserPapers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).GetUserPapers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_GetUserPapers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).GetUserPapers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_GetPaper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).GetPaper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_GetPaper_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).GetPaper(ctx, req.(*PaperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_CreatePaper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).CreatePaper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_CreatePaper_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).CreatePaper(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_UpdatePaper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).UpdatePaper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_UpdatePaper_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).UpdatePaper(ctx, req.(*UpdatePaperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_DeletePapers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePapersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).DeletePapers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_DeletePapers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).DeletePapers(ctx, req.(*DeletePapersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_GetPaperPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).GetPaperPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_GetPaperPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).GetPaperPermissions(ctx, req.(*PaperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_GetPaperQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).GetPaperQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_GetPaperQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).GetPaperQuestions(ctx, req.(*PaperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_GetPaperQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaperQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).GetPaperQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_GetPaperQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).GetPaperQuestion(ctx, req.(*PaperQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_CreatePaperQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaperQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).CreatePaperQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_CreatePaperQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).CreatePaperQuestion(ctx, req.(*CreatePaperQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_UpdatePaperQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaperQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).UpdatePaperQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_UpdatePaperQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).UpdatePaperQuestion(ctx, req.(*UpdatePaperQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_DeletePaperQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaperQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).DeletePaperQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_DeletePaperQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).DeletePaperQuestion(ctx, req.(*PaperQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_ReorderPaperQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReorderPaperQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).ReorderPaperQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_ReorderPaperQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).ReorderPaperQuestions(ctx, req.(*ReorderPaperQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_GetPaperBoilerplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaperBoilerplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).GetPaperBoilerplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_GetPaperBoilerplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).GetPaperBoilerplate(ctx, req.(*GetPaperBoilerplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_UpsertPaperTestCases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertPaperTestCasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).UpsertPaperTestCases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_UpsertPaperTestCases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).UpsertPaperTestCases(ctx, req.(*UpsertPaperTestCasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_GetPaperCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).GetPaperCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_GetPaperCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).GetPaperCategories(ctx, req.(*PaperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_CreatePaperCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaperCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).CreatePaperCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_CreatePaperCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).CreatePaperCategory(ctx, req.(*CreatePaperCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_UpdatePaperCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaperCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).UpdatePaperCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_UpdatePaperCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).UpdatePaperCategory(ctx, req.(*UpdatePaperCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_DeletePaperCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaperCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).DeletePaperCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_DeletePaperCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).DeletePaperCategory(ctx, req.(*PaperCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_ReorderPaperCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReorderPaperCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).ReorderPaperCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_ReorderPaperCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).ReorderPaperCategories(ctx, req.(*ReorderPaperCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_GetPaperQuestionsMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).GetPaperQuestionsMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_GetPaperQuestionsMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).GetPaperQuestionsMeta(ctx, req.(*PaperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paper_GetPaperCategoriesMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServer).GetPaperCategoriesMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paper_GetPaperCategoriesMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServer).GetPaperCategoriesMeta(ctx, req.(*PaperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Paper_ServiceDesc is the grpc.ServiceDesc for Paper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Paper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Paper",
	HandlerType: (*PaperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserPapers",
			Handler:    _Paper_GetUserPapers_Handler,
		},
		{
			MethodName: "GetPaper",
			Handler:    _Paper_GetPaper_Handler,
		},
		{
			MethodName: "CreatePaper",
			Handler:    _Paper_CreatePaper_Handler,
		},
		{
			MethodName: "UpdatePaper",
			Handler:    _Paper_UpdatePaper_Handler,
		},
		{
			MethodName: "DeletePapers",
			Handler:    _Paper_DeletePapers_Handler,
		},
		{
			MethodName: "GetPaperPermissions",
			Handler:    _Paper_GetPaperPermissions_Handler,
		},
		{
			MethodName: "GetPaperQuestions",
			Handler:    _Paper_GetPaperQuestions_Handler,
		},
		{
			MethodName: "GetPaperQuestion",
			Handler:    _Paper_GetPaperQuestion_Handler,
		},
		{
			MethodName: "CreatePaperQuestion",
			Handler:    _Paper_CreatePaperQuestion_Handler,
		},
		{
			MethodName: "UpdatePaperQuestion",
			Handler:    _Paper_UpdatePaperQuestion_Handler,
		},
		{
			MethodName: "DeletePaperQuestion",
			Handler:    _Paper_DeletePaperQuestion_Handler,
		},
		{
			MethodName: "ReorderPaperQuestions",
			Handler:    _Paper_ReorderPaperQuestions_Handler,
		},
		{
			MethodName: "GetPaperBoilerplate",
			Handler:    _Paper_GetPaperBoilerplate_Handler,
		},
		{
			MethodName: "UpsertPaperTestCases",
			Handler:    _Paper_UpsertPaperTestCases_Handler,
		},
		{
			MethodName: "GetPaperCategories",
			Handler:    _Paper_GetPaperCategories_Handler,
		},
		{
			MethodName: "CreatePaperCategory",
			Handler:    _Paper_CreatePaperCategory_Handler,
		},
		{
			MethodName: "UpdatePaperCategory",
			Handler:    _Paper_UpdatePaperCategory_Handler,
		},
		{
			MethodName: "DeletePaperCategory",
			Handler:    _Paper_DeletePaperCategory_Handler,
		},
		{
			MethodName: "ReorderPaperCategories",
			Handler:    _Paper_ReorderPaperCategories_Handler,
		},
		{
			MethodName: "GetPaperQuestionsMeta",
			Handler:    _Paper_GetPaperQuestionsMeta_Handler,
		},
		{
			MethodName: "GetPaperCategoriesMeta",
			Handler:    _Paper_GetPaperCategoriesMeta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paper.proto",
}
