// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: paper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Paper messages
type PaperRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperHash     string                 `protobuf:"bytes,1,opt,name=paper_hash,json=paperHash,proto3" json:"paper_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaperRequest) Reset() {
	*x = PaperRequest{}
	mi := &file_paper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperRequest) ProtoMessage() {}

func (x *PaperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperRequest.ProtoReflect.Descriptor instead.
func (*PaperRequest) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{0}
}

func (x *PaperRequest) GetPaperHash() string {
	if x != nil {
		return x.PaperHash
	}
	return ""
}

type PaperResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaperHash       string                 `protobuf:"bytes,1,opt,name=paper_hash,json=paperHash,proto3" json:"paper_hash,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	MaxScore        int32                  `protobuf:"varint,3,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,4,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	QuestionCounts  *QuestionCount         `protobuf:"bytes,5,opt,name=question_counts,json=questionCounts,proto3" json:"question_counts,omitempty"`
	CreatedBy       int64                  `protobuf:"varint,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaperResponse) Reset() {
	*x = PaperResponse{}
	mi := &file_paper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperResponse) ProtoMessage() {}

func (x *PaperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperResponse.ProtoReflect.Descriptor instead.
func (*PaperResponse) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{1}
}

func (x *PaperResponse) GetPaperHash() string {
	if x != nil {
		return x.PaperHash
	}
	return ""
}

func (x *PaperResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PaperResponse) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *PaperResponse) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *PaperResponse) GetQuestionCounts() *QuestionCount {
	if x != nil {
		return x.QuestionCounts
	}
	return nil
}

func (x *PaperResponse) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

type CreatePaperResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperHash     string                 `protobuf:"bytes,1,opt,name=paper_hash,json=paperHash,proto3" json:"paper_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaperResponse) Reset() {
	*x = CreatePaperResponse{}
	mi := &file_paper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaperResponse) ProtoMessage() {}

func (x *CreatePaperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaperResponse.ProtoReflect.Descriptor instead.
func (*CreatePaperResponse) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePaperResponse) GetPaperHash() string {
	if x != nil {
		return x.PaperHash
	}
	return ""
}

type PaperList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Papers        []*PaperResponse       `protobuf:"bytes,1,rep,name=papers,proto3" json:"papers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaperList) Reset() {
	*x = PaperList{}
	mi := &file_paper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperList) ProtoMessage() {}

func (x *PaperList) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperList.ProtoReflect.Descriptor instead.
func (*PaperList) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{3}
}

func (x *PaperList) GetPapers() []*PaperResponse {
	if x != nil {
		return x.Papers
	}
	return nil
}

type UpdatePaperRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaperHash       string                 `protobuf:"bytes,1,opt,name=paper_hash,json=paperHash,proto3" json:"paper_hash,omitempty"`
	Title           *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	DurationMinutes *int32                 `protobuf:"varint,3,opt,name=duration_minutes,json=durationMinutes,proto3,oneof" json:"duration_minutes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdatePaperRequest) Reset() {
	*x = UpdatePaperRequest{}
	mi := &file_paper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaperRequest) ProtoMessage() {}

func (x *UpdatePaperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaperRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaperRequest) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePaperRequest) GetPaperHash() string {
	if x != nil {
		return x.PaperHash
	}
	return ""
}

func (x *UpdatePaperRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdatePaperRequest) GetDurationMinutes() int32 {
	if x != nil && x.DurationMinutes != nil {
		return *x.DurationMinutes
	}
	return 0
}

type QuestionCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mcq           int32                  `protobuf:"varint,1,opt,name=mcq,proto3" json:"mcq,omitempty"`
	Subjective    int32                  `protobuf:"varint,2,opt,name=subjective,proto3" json:"subjective,omitempty"`
	Coding        int32                  `protobuf:"varint,3,opt,name=coding,proto3" json:"coding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionCount) Reset() {
	*x = QuestionCount{}
	mi := &file_paper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionCount) ProtoMessage() {}

func (x *QuestionCount) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionCount.ProtoReflect.Descriptor instead.
func (*QuestionCount) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{5}
}

func (x *QuestionCount) GetMcq() int32 {
	if x != nil {
		return x.Mcq
	}
	return 0
}

func (x *QuestionCount) GetSubjective() int32 {
	if x != nil {
		return x.Subjective
	}
	return 0
}

func (x *QuestionCount) GetCoding() int32 {
	if x != nil {
		return x.Coding
	}
	return 0
}

type DeletePapersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperHashes   []string               `protobuf:"bytes,1,rep,name=paper_hashes,json=paperHashes,proto3" json:"paper_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePapersRequest) Reset() {
	*x = DeletePapersRequest{}
	mi := &file_paper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePapersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePapersRequest) ProtoMessage() {}

func (x *DeletePapersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePapersRequest.ProtoReflect.Descriptor instead.
func (*DeletePapersRequest) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePapersRequest) GetPaperHashes() []string {
	if x != nil {
		return x.PaperHashes
	}
	return nil
}

// Question messages
type PaperQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperHash     string                 `protobuf:"bytes,1,opt,name=paper_hash,json=paperHash,proto3" json:"paper_hash,omitempty"`
	QuestionHash  string                 `protobuf:"bytes,2,opt,name=question_hash,json=questionHash,proto3" json:"question_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaperQuestionRequest) Reset() {
	*x = PaperQuestionRequest{}
	mi := &file_paper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperQuestionRequest) ProtoMessage() {}

func (x *PaperQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperQuestionRequest.ProtoReflect.Descriptor instead.
func (*PaperQuestionRequest) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{7}
}

func (x *PaperQuestionRequest) GetPaperHash() string {
	if x != nil {
		return x.PaperHash
	}
	return ""
}

func (x *PaperQuestionRequest) GetQuestionHash() string {
	if x != nil {
		return x.QuestionHash
	}
	return ""
}

type PaperQuestionResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	QuestionHash  string                    `protobuf:"bytes,1,opt,name=question_hash,json=questionHash,proto3" json:"question_hash,omitempty"`
	RawQuestion   []byte                    `protobuf:"bytes,2,opt,name=raw_question,json=rawQuestion,proto3" json:"raw_question,omitempty"`
	CategoryId    int64                     `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Type          QuestionType              `protobuf:"varint,5,opt,name=type,proto3,enum=proto.QuestionType" json:"type,omitempty"`
	PaperHash     string                    `protobuf:"bytes,6,opt,name=paper_hash,json=paperHash,proto3" json:"paper_hash,omitempty"`
	MaxScore      int32                     `protobuf:"varint,7,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	TestCases     []*CodingQuestionTestCase `protobuf:"bytes,8,rep,name=test_cases,json=testCases,proto3" json:"test_cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaperQuestionResponse) Reset() {
	*x = PaperQuestionResponse{}
	mi := &file_paper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperQuestionResponse) ProtoMessage() {}

func (x *PaperQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperQuestionResponse.ProtoReflect.Descriptor instead.
func (*PaperQuestionResponse) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{8}
}

func (x *PaperQuestionResponse) GetQuestionHash() string {
	if x != nil {
		return x.QuestionHash
	}
	return ""
}

func (x *PaperQuestionResponse) GetRawQuestion() []byte {
	if x != nil {
		return x.RawQuestion
	}
	return nil
}

func (x *PaperQuestionResponse) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *PaperQuestionResponse) GetType() QuestionType {
	if x != nil {
		return x.Type
	}
	return QuestionType_UNKNOWN_QUESTION_TYPE
}

func (x *PaperQuestionResponse) GetPaperHash() string {
	if x != nil {
		return x.PaperHash
	}
	return ""
}

func (x *PaperQuestionResponse) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *PaperQuestionResponse) GetTestCases() []*CodingQuestionTestCase {
	if x != nil {
		return x.TestCases
	}
	return nil
}

type QuestionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*QuestionMinimal     `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionList) Reset() {
	*x = QuestionList{}
	mi := &file_paper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionList) ProtoMessage() {}

func (x *QuestionList) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionList.ProtoReflect.Descriptor instead.
func (*QuestionList) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{9}
}

func (x *QuestionList) GetQuestions() []*QuestionMinimal {
	if x != nil {
		return x.Questions
	}
	return nil
}

type QuestionMinimal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionHash  string                 `protobuf:"bytes,1,opt,name=question_hash,json=questionHash,proto3" json:"question_hash,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	PaperHash     string                 `protobuf:"bytes,3,opt,name=paper_hash,json=paperHash,proto3" json:"paper_hash,omitempty"`
	Order         int32                  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	RawQuestion   []byte                 `protobuf:"bytes,5,opt,name=raw_question,json=rawQuestion,proto3" json:"raw_question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionMinimal) Reset() {
	*x = QuestionMinimal{}
	mi := &file_paper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionMinimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionMinimal) ProtoMessage() {}

func (x *QuestionMinimal) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionMinimal.ProtoReflect.Descriptor instead.
func (*QuestionMinimal) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{10}
}

func (x *QuestionMinimal) GetQuestionHash() string {
	if x != nil {
		return x.QuestionHash
	}
	return ""
}

func (x *QuestionMinimal) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *QuestionMinimal) GetPaperHash() string {
	if x != nil {
		return x.PaperHash
	}
	return ""
}

func (x *QuestionMinimal) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *QuestionMinimal) GetRawQuestion() []byte {
	if x != nil {
		return x.RawQuestion
	}
	return nil
}

type PaperQuestionsMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*PaperQuestionMeta   `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaperQuestionsMeta) Reset() {
	*x = PaperQuestionsMeta{}
	mi := &file_paper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperQuestionsMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperQuestionsMeta) ProtoMessage() {}

func (x *PaperQuestionsMeta) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperQuestionsMeta.ProtoReflect.Descriptor instead.
func (*PaperQuestionsMeta) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{11}
}

func (x *PaperQuestionsMeta) GetQuestions() []*PaperQuestionMeta {
	if x != nil {
		return x.Questions
	}
	return nil
}

type PaperQuestionMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Order         int32                  `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	MaxScore      int32                  `protobuf:"varint,4,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaperQuestionMeta) Reset() {
	*x = PaperQuestionMeta{}
	mi := &file_paper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperQuestionMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperQuestionMeta) ProtoMessage() {}

func (x *PaperQuestionMeta) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperQuestionMeta.ProtoReflect.Descriptor instead.
func (*PaperQuestionMeta) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{12}
}

func (x *PaperQuestionMeta) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaperQuestionMeta) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *PaperQuestionMeta) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *PaperQuestionMeta) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

type CreatePaperQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperHash     string                 `protobuf:"bytes,1,opt,name=paper_hash,json=paperHash,proto3" json:"paper_hash,omitempty"`
	RawQuestion   []byte                 `protobuf:"bytes,2,opt,name=raw_question,json=rawQuestion,proto3" json:"raw_question,omitempty"`
	CategoryId    int64                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Type          QuestionType           `protobuf:"varint,4,opt,name=type,proto3,enum=proto.QuestionType" json:"type,omitempty"`
	MaxScore      int32                  `protobuf:"varint,5,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaperQuestionRequest) Reset() {
	*x = CreatePaperQuestionRequest{}
	mi := &file_paper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaperQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaperQuestionRequest) ProtoMessage() {}

func (x *CreatePaperQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaperQuestionRequest.ProtoReflect.Descriptor instead.
func (*CreatePaperQuestionRequest) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePaperQuestionRequest) GetPaperHash() string {
	if x != nil {
		return x.PaperHash
	}
	return ""
}

func (x *CreatePaperQuestionRequest) GetRawQuestion() []byte {
	if x != nil {
		return x.RawQuestion
	}
	return nil
}

func (x *CreatePaperQuestionRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreatePaperQuestionRequest) GetType() QuestionType {
	if x != nil {
		return x.Type
	}
	return QuestionType_UNKNOWN_QUESTION_TYPE
}

func (x *CreatePaperQuestionRequest) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

type CreatePaperQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionHash  string                 `protobuf:"bytes,1,opt,name=question_hash,json=questionHash,proto3" json:"question_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaperQuestionResponse) Reset() {
	*x = CreatePaperQuestionResponse{}
	mi := &file_paper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaperQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaperQuestionResponse) ProtoMessage() {}

func (x *CreatePaperQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaperQuestionResponse.ProtoReflect.Descriptor instead.
func (*CreatePaperQuestionResponse) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{14}
}

func (x *CreatePaperQuestionResponse) GetQuestionHash() string {
	if x != nil {
		return x.QuestionHash
	}
	return ""
}

type UpdatePaperQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperHash     string                 `protobuf:"bytes,1,opt,name=paper_hash,json=paperHash,proto3" json:"paper_hash,omitempty"`
	QuestionHash  string                 `protobuf:"bytes,2,opt,name=question_hash,json=questionHash,proto3" json:"question_hash,omitempty"`
	Type          *QuestionType          `protobuf:"varint,3,opt,name=type,proto3,enum=proto.QuestionType,oneof" json:"type,omitempty"`
	RawQuestion   []byte                 `protobuf:"bytes,4,opt,name=raw_question,json=rawQuestion,proto3,oneof" json:"raw_question,omitempty"`
	MaxScore      *int32                 `protobuf:"varint,5,opt,name=max_score,json=maxScore,proto3,oneof" json:"max_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaperQuestionRequest) Reset() {
	*x = UpdatePaperQuestionRequest{}
	mi := &file_paper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaperQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaperQuestionRequest) ProtoMessage() {}

func (x *UpdatePaperQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaperQuestionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaperQuestionRequest) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{15}
}

func (x *UpdatePaperQuestionRequest) GetPaperHash() string {
	if x != nil {
		return x.PaperHash
	}
	return ""
}

func (x *UpdatePaperQuestionRequest) GetQuestionHash() string {
	if x != nil {
		return x.QuestionHash
	}
	return ""
}

func (x *UpdatePaperQuestionRequest) GetType() QuestionType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return QuestionType_UNKNOWN_QUESTION_TYPE
}

func (x *UpdatePaperQuestionRequest) GetRawQuestion() []byte {
	if x != nil {
		return x.RawQuestion
	}
	return nil
}

func (x *UpdatePaperQuestionRequest) GetMaxScore() int32 {
	if x != nil && x.MaxScore != nil {
		return *x.MaxScore
	}
	return 0
}

type UpdatePaperQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionHash  string                 `protobuf:"bytes,1,opt,name=question_hash,json=questionHash,proto3" json:"question_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaperQuestionResponse) Reset() {
	*x = UpdatePaperQuestionResponse{}
	mi := &file_paper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaperQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaperQuestionResponse) ProtoMessage() {}

func (x *UpdatePaperQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaperQuestionResponse.ProtoReflect.Descriptor instead.
func (*UpdatePaperQuestionResponse) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{16}
}

func (x *UpdatePaperQuestionResponse) GetQuestionHash() string {
	if x != nil {
		return x.QuestionHash
	}
	return ""
}

type ReorderPaperQuestionsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaperHash      string                 `protobuf:"bytes,1,opt,name=paper_hash,json=paperHash,proto3" json:"paper_hash,omitempty"`
	CategoryId     int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	QuestionHashes []string               `protobuf:"bytes,3,rep,name=question_hashes,json=questionHashes,proto3" json:"question_hashes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReorderPaperQuestionsRequest) Reset() {
	*x = ReorderPaperQuestionsRequest{}
	mi := &file_paper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderPaperQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderPaperQuestionsRequest) ProtoMessage() {}

func (x *ReorderPaperQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderPaperQuestionsRequest.ProtoReflect.Descriptor instead.
func (*ReorderPaperQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{17}
}

func (x *ReorderPaperQuestionsRequest) GetPaperHash() string {
	if x != nil {
		return x.PaperHash
	}
	return ""
}

func (x *ReorderPaperQuestionsRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ReorderPaperQuestionsRequest) GetQuestionHashes() []string {
	if x != nil {
		return x.QuestionHashes
	}
	return nil
}

type PaperCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperHash     string                 `protobuf:"bytes,1,opt,name=paper_hash,json=paperHash,proto3" json:"paper_hash,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaperCategoryRequest) Reset() {
	*x = PaperCategoryRequest{}
	mi := &file_paper_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperCategoryRequest) ProtoMessage() {}

func (x *PaperCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperCategoryRequest.ProtoReflect.Descriptor instead.
func (*PaperCategoryRequest) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{18}
}

func (x *PaperCategoryRequest) GetPaperHash() string {
	if x != nil {
		return x.PaperHash
	}
	return ""
}

func (x *PaperCategoryRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type PaperCategoryList struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Categories    []*PaperCategoryResponse `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaperCategoryList) Reset() {
	*x = PaperCategoryList{}
	mi := &file_paper_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperCategoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperCategoryList) ProtoMessage() {}

func (x *PaperCategoryList) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperCategoryList.ProtoReflect.Descriptor instead.
func (*PaperCategoryList) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{19}
}

func (x *PaperCategoryList) GetCategories() []*PaperCategoryResponse {
	if x != nil {
		return x.Categories
	}
	return nil
}

type PaperCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Order         int32                  `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaperCategoryResponse) Reset() {
	*x = PaperCategoryResponse{}
	mi := &file_paper_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperCategoryResponse) ProtoMessage() {}

func (x *PaperCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperCategoryResponse.ProtoReflect.Descriptor instead.
func (*PaperCategoryResponse) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{20}
}

func (x *PaperCategoryResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaperCategoryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PaperCategoryResponse) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type PaperCategoriesMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*PaperCategoryMeta   `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaperCategoriesMeta) Reset() {
	*x = PaperCategoriesMeta{}
	mi := &file_paper_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperCategoriesMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperCategoriesMeta) ProtoMessage() {}

func (x *PaperCategoriesMeta) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperCategoriesMeta.ProtoReflect.Descriptor instead.
func (*PaperCategoriesMeta) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{21}
}

func (x *PaperCategoriesMeta) GetCategories() []*PaperCategoryMeta {
	if x != nil {
		return x.Categories
	}
	return nil
}

type PaperCategoryMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Order         int32                  `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaperCategoryMeta) Reset() {
	*x = PaperCategoryMeta{}
	mi := &file_paper_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperCategoryMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperCategoryMeta) ProtoMessage() {}

func (x *PaperCategoryMeta) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperCategoryMeta.ProtoReflect.Descriptor instead.
func (*PaperCategoryMeta) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{22}
}

func (x *PaperCategoryMeta) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaperCategoryMeta) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type CreatePaperCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperHash     string                 `protobuf:"bytes,1,opt,name=paper_hash,json=paperHash,proto3" json:"paper_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaperCategoryRequest) Reset() {
	*x = CreatePaperCategoryRequest{}
	mi := &file_paper_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaperCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaperCategoryRequest) ProtoMessage() {}

func (x *CreatePaperCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaperCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreatePaperCategoryRequest) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{23}
}

func (x *CreatePaperCategoryRequest) GetPaperHash() string {
	if x != nil {
		return x.PaperHash
	}
	return ""
}

type UpdatePaperCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperHash     string                 `protobuf:"bytes,1,opt,name=paper_hash,json=paperHash,proto3" json:"paper_hash,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaperCategoryRequest) Reset() {
	*x = UpdatePaperCategoryRequest{}
	mi := &file_paper_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaperCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaperCategoryRequest) ProtoMessage() {}

func (x *UpdatePaperCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaperCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaperCategoryRequest) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{24}
}

func (x *UpdatePaperCategoryRequest) GetPaperHash() string {
	if x != nil {
		return x.PaperHash
	}
	return ""
}

func (x *UpdatePaperCategoryRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdatePaperCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReorderPaperCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperHash     string                 `protobuf:"bytes,1,opt,name=paper_hash,json=paperHash,proto3" json:"paper_hash,omitempty"`
	CategoryIds   []int64                `protobuf:"varint,2,rep,packed,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderPaperCategoriesRequest) Reset() {
	*x = ReorderPaperCategoriesRequest{}
	mi := &file_paper_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderPaperCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderPaperCategoriesRequest) ProtoMessage() {}

func (x *ReorderPaperCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderPaperCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ReorderPaperCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{25}
}

func (x *ReorderPaperCategoriesRequest) GetPaperHash() string {
	if x != nil {
		return x.PaperHash
	}
	return ""
}

func (x *ReorderPaperCategoriesRequest) GetCategoryIds() []int64 {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

type PaperPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanRead       bool                   `protobuf:"varint,1,opt,name=can_read,json=canRead,proto3" json:"can_read,omitempty"`
	CanWrite      bool                   `protobuf:"varint,2,opt,name=can_write,json=canWrite,proto3" json:"can_write,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaperPermissionsResponse) Reset() {
	*x = PaperPermissionsResponse{}
	mi := &file_paper_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperPermissionsResponse) ProtoMessage() {}

func (x *PaperPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperPermissionsResponse.ProtoReflect.Descriptor instead.
func (*PaperPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{26}
}

func (x *PaperPermissionsResponse) GetCanRead() bool {
	if x != nil {
		return x.CanRead
	}
	return false
}

func (x *PaperPermissionsResponse) GetCanWrite() bool {
	if x != nil {
		return x.CanWrite
	}
	return false
}

type GetPaperBoilerplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperHash     string                 `protobuf:"bytes,1,opt,name=paper_hash,json=paperHash,proto3" json:"paper_hash,omitempty"`
	QuestionHash  string                 `protobuf:"bytes,2,opt,name=question_hash,json=questionHash,proto3" json:"question_hash,omitempty"`
	LanguageId    int32                  `protobuf:"varint,3,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaperBoilerplateRequest) Reset() {
	*x = GetPaperBoilerplateRequest{}
	mi := &file_paper_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaperBoilerplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaperBoilerplateRequest) ProtoMessage() {}

func (x *GetPaperBoilerplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaperBoilerplateRequest.ProtoReflect.Descriptor instead.
func (*GetPaperBoilerplateRequest) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{27}
}

func (x *GetPaperBoilerplateRequest) GetPaperHash() string {
	if x != nil {
		return x.PaperHash
	}
	return ""
}

func (x *GetPaperBoilerplateRequest) GetQuestionHash() string {
	if x != nil {
		return x.QuestionHash
	}
	return ""
}

func (x *GetPaperBoilerplateRequest) GetLanguageId() int32 {
	if x != nil {
		return x.LanguageId
	}
	return 0
}

type UpsertPaperTestCasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperHash     string                 `protobuf:"bytes,1,opt,name=paper_hash,json=paperHash,proto3" json:"paper_hash,omitempty"`
	QuestionHash  string                 `protobuf:"bytes,2,opt,name=question_hash,json=questionHash,proto3" json:"question_hash,omitempty"`
	TestCases     []*UpsertTestCase      `protobuf:"bytes,3,rep,name=test_cases,json=testCases,proto3" json:"test_cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertPaperTestCasesRequest) Reset() {
	*x = UpsertPaperTestCasesRequest{}
	mi := &file_paper_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPaperTestCasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPaperTestCasesRequest) ProtoMessage() {}

func (x *UpsertPaperTestCasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPaperTestCasesRequest.ProtoReflect.Descriptor instead.
func (*UpsertPaperTestCasesRequest) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{28}
}

func (x *UpsertPaperTestCasesRequest) GetPaperHash() string {
	if x != nil {
		return x.PaperHash
	}
	return ""
}

func (x *UpsertPaperTestCasesRequest) GetQuestionHash() string {
	if x != nil {
		return x.QuestionHash
	}
	return ""
}

func (x *UpsertPaperTestCasesRequest) GetTestCases() []*UpsertTestCase {
	if x != nil {
		return x.TestCases
	}
	return nil
}

var File_paper_proto protoreflect.FileDescriptor

const file_paper_proto_rawDesc = "" +
	"\n" +
	"\vpaper.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\fcommon.proto\"-\n" +
	"\fPaperRequest\x12\x1d\n" +
	"\n" +
	"paper_hash\x18\x01 \x01(\tR\tpaperHash\"\xea\x01\n" +
	"\rPaperResponse\x12\x1d\n" +
	"\n" +
	"paper_hash\x18\x01 \x01(\tR\tpaperHash\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tmax_score\x18\x03 \x01(\x05R\bmaxScore\x12)\n" +
	"\x10duration_minutes\x18\x04 \x01(\x05R\x0fdurationMinutes\x12=\n" +
	"\x0fquestion_counts\x18\x05 \x01(\v2\x14.proto.QuestionCountR\x0equestionCounts\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\x03R\tcreatedBy\"4\n" +
	"\x13CreatePaperResponse\x12\x1d\n" +
	"\n" +
	"paper_hash\x18\x01 \x01(\tR\tpaperHash\"9\n" +
	"\tPaperList\x12,\n" +
	"\x06papers\x18\x01 \x03(\v2\x14.proto.PaperResponseR\x06papers\"\x9d\x01\n" +
	"\x12UpdatePaperRequest\x12\x1d\n" +
	"\n" +
	"paper_hash\x18\x01 \x01(\tR\tpaperHash\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12.\n" +
	"\x10duration_minutes\x18\x03 \x01(\x05H\x01R\x0fdurationMinutes\x88\x01\x01B\b\n" +
	"\x06_titleB\x13\n" +
	"\x11_duration_minutes\"Y\n" +
	"\rQuestionCount\x12\x10\n" +
	"\x03mcq\x18\x01 \x01(\x05R\x03mcq\x12\x1e\n" +
	"\n" +
	"subjective\x18\x02 \x01(\x05R\n" +
	"subjective\x12\x16\n" +
	"\x06coding\x18\x03 \x01(\x05R\x06coding\"8\n" +
	"\x13DeletePapersRequest\x12!\n" +
	"\fpaper_hashes\x18\x01 \x03(\tR\vpaperHashes\"Z\n" +
	"\x14PaperQuestionRequest\x12\x1d\n" +
	"\n" +
	"paper_hash\x18\x01 \x01(\tR\tpaperHash\x12#\n" +
	"\rquestion_hash\x18\x02 \x01(\tR\fquestionHash\"\xa3\x02\n" +
	"\x15PaperQuestionResponse\x12#\n" +
	"\rquestion_hash\x18\x01 \x01(\tR\fquestionHash\x12!\n" +
	"\fraw_question\x18\x02 \x01(\fR\vrawQuestion\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x03R\n" +
	"categoryId\x12'\n" +
	"\x04type\x18\x05 \x01(\x0e2\x13.proto.QuestionTypeR\x04type\x12\x1d\n" +
	"\n" +
	"paper_hash\x18\x06 \x01(\tR\tpaperHash\x12\x1b\n" +
	"\tmax_score\x18\a \x01(\x05R\bmaxScore\x12<\n" +
	"\n" +
	"test_cases\x18\b \x03(\v2\x1d.proto.CodingQuestionTestCaseR\ttestCases\"D\n" +
	"\fQuestionList\x124\n" +
	"\tquestions\x18\x01 \x03(\v2\x16.proto.QuestionMinimalR\tquestions\"\xaf\x01\n" +
	"\x0fQuestionMinimal\x12#\n" +
	"\rquestion_hash\x18\x01 \x01(\tR\fquestionHash\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x1d\n" +
	"\n" +
	"paper_hash\x18\x03 \x01(\tR\tpaperHash\x12\x14\n" +
	"\x05order\x18\x04 \x01(\x05R\x05order\x12!\n" +
	"\fraw_question\x18\x05 \x01(\fR\vrawQuestion\"L\n" +
	"\x12PaperQuestionsMeta\x126\n" +
	"\tquestions\x18\x01 \x03(\v2\x18.proto.PaperQuestionMetaR\tquestions\"w\n" +
	"\x11PaperQuestionMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x14\n" +
	"\x05order\x18\x03 \x01(\x05R\x05order\x12\x1b\n" +
	"\tmax_score\x18\x04 \x01(\x05R\bmaxScore\"\xc5\x01\n" +
	"\x1aCreatePaperQuestionRequest\x12\x1d\n" +
	"\n" +
	"paper_hash\x18\x01 \x01(\tR\tpaperHash\x12!\n" +
	"\fraw_question\x18\x02 \x01(\fR\vrawQuestion\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x03R\n" +
	"categoryId\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.proto.QuestionTypeR\x04type\x12\x1b\n" +
	"\tmax_score\x18\x05 \x01(\x05R\bmaxScore\"B\n" +
	"\x1bCreatePaperQuestionResponse\x12#\n" +
	"\rquestion_hash\x18\x01 \x01(\tR\fquestionHash\"\x80\x02\n" +
	"\x1aUpdatePaperQuestionRequest\x12\x1d\n" +
	"\n" +
	"paper_hash\x18\x01 \x01(\tR\tpaperHash\x12#\n" +
	"\rquestion_hash\x18\x02 \x01(\tR\fquestionHash\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.proto.QuestionTypeH\x00R\x04type\x88\x01\x01\x12&\n" +
	"\fraw_question\x18\x04 \x01(\fH\x01R\vrawQuestion\x88\x01\x01\x12 \n" +
	"\tmax_score\x18\x05 \x01(\x05H\x02R\bmaxScore\x88\x01\x01B\a\n" +
	"\x05_typeB\x0f\n" +
	"\r_raw_questionB\f\n" +
	"\n" +
	"_max_score\"B\n" +
	"\x1bUpdatePaperQuestionResponse\x12#\n" +
	"\rquestion_hash\x18\x01 \x01(\tR\fquestionHash\"\x87\x01\n" +
	"\x1cReorderPaperQuestionsRequest\x12\x1d\n" +
	"\n" +
	"paper_hash\x18\x01 \x01(\tR\tpaperHash\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12'\n" +
	"\x0fquestion_hashes\x18\x03 \x03(\tR\x0equestionHashes\"V\n" +
	"\x14PaperCategoryRequest\x12\x1d\n" +
	"\n" +
	"paper_hash\x18\x01 \x01(\tR\tpaperHash\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\"Q\n" +
	"\x11PaperCategoryList\x12<\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1c.proto.PaperCategoryResponseR\n" +
	"categories\"Q\n" +
	"\x15PaperCategoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05order\x18\x03 \x01(\x05R\x05order\"O\n" +
	"\x13PaperCategoriesMeta\x128\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x18.proto.PaperCategoryMetaR\n" +
	"categories\"9\n" +
	"\x11PaperCategoryMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05order\x18\x03 \x01(\x05R\x05order\";\n" +
	"\x1aCreatePaperCategoryRequest\x12\x1d\n" +
	"\n" +
	"paper_hash\x18\x01 \x01(\tR\tpaperHash\"p\n" +
	"\x1aUpdatePaperCategoryRequest\x12\x1d\n" +
	"\n" +
	"paper_hash\x18\x01 \x01(\tR\tpaperHash\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"a\n" +
	"\x1dReorderPaperCategoriesRequest\x12\x1d\n" +
	"\n" +
	"paper_hash\x18\x01 \x01(\tR\tpaperHash\x12!\n" +
	"\fcategory_ids\x18\x02 \x03(\x03R\vcategoryIds\"R\n" +
	"\x18PaperPermissionsResponse\x12\x19\n" +
	"\bcan_read\x18\x01 \x01(\bR\acanRead\x12\x1b\n" +
	"\tcan_write\x18\x02 \x01(\bR\bcanWrite\"\x81\x01\n" +
	"\x1aGetPaperBoilerplateRequest\x12\x1d\n" +
	"\n" +
	"paper_hash\x18\x01 \x01(\tR\tpaperHash\x12#\n" +
	"\rquestion_hash\x18\x02 \x01(\tR\fquestionHash\x12\x1f\n" +
	"\vlanguage_id\x18\x03 \x01(\x05R\n" +
	"languageId\"\x97\x01\n" +
	"\x1bUpsertPaperTestCasesRequest\x12\x1d\n" +
	"\n" +
	"paper_hash\x18\x01 \x01(\tR\tpaperHash\x12#\n" +
	"\rquestion_hash\x18\x02 \x01(\tR\fquestionHash\x124\n" +
	"\n" +
	"test_cases\x18\x03 \x03(\v2\x15.proto.UpsertTestCaseR\ttestCases2\xf6\f\n" +
	"\x05Paper\x12;\n" +
	"\rGetUserPapers\x12\x16.google.protobuf.Empty\x1a\x10.proto.PaperList\"\x00\x127\n" +
	"\bGetPaper\x12\x13.proto.PaperRequest\x1a\x14.proto.PaperResponse\"\x00\x12C\n" +
	"\vCreatePaper\x12\x16.google.protobuf.Empty\x1a\x1a.proto.CreatePaperResponse\"\x00\x12B\n" +
	"\vUpdatePaper\x12\x19.proto.UpdatePaperRequest\x1a\x16.google.protobuf.Empty\"\x00\x12D\n" +
	"\fDeletePapers\x12\x1a.proto.DeletePapersRequest\x1a\x16.google.protobuf.Empty\"\x00\x12M\n" +
	"\x13GetPaperPermissions\x12\x13.proto.PaperRequest\x1a\x1f.proto.PaperPermissionsResponse\"\x00\x12?\n" +
	"\x11GetPaperQuestions\x12\x13.proto.PaperRequest\x1a\x13.proto.QuestionList\"\x00\x12O\n" +
	"\x10GetPaperQuestion\x12\x1b.proto.PaperQuestionRequest\x1a\x1c.proto.PaperQuestionResponse\"\x00\x12^\n" +
	"\x13CreatePaperQuestion\x12!.proto.CreatePaperQuestionRequest\x1a\".proto.CreatePaperQuestionResponse\"\x00\x12^\n" +
	"\x13UpdatePaperQuestion\x12!.proto.UpdatePaperQuestionRequest\x1a\".proto.UpdatePaperQuestionResponse\"\x00\x12L\n" +
	"\x13DeletePaperQuestion\x12\x1b.proto.PaperQuestionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12V\n" +
	"\x15ReorderPaperQuestions\x12#.proto.ReorderPaperQuestionsRequest\x1a\x16.google.protobuf.Empty\"\x00\x12V\n" +
	"\x13GetPaperBoilerplate\x12!.proto.GetPaperBoilerplateRequest\x1a\x1a.proto.BoilerplateResponse\"\x00\x12T\n" +
	"\x14UpsertPaperTestCases\x12\".proto.UpsertPaperTestCasesRequest\x1a\x16.google.protobuf.Empty\"\x00\x12E\n" +
	"\x12GetPaperCategories\x12\x13.proto.PaperRequest\x1a\x18.proto.PaperCategoryList\"\x00\x12X\n" +
	"\x13CreatePaperCategory\x12!.proto.CreatePaperCategoryRequest\x1a\x1c.proto.PaperCategoryResponse\"\x00\x12R\n" +
	"\x13UpdatePaperCategory\x12!.proto.UpdatePaperCategoryRequest\x1a\x16.google.protobuf.Empty\"\x00\x12L\n" +
	"\x13DeletePaperCategory\x12\x1b.proto.PaperCategoryRequest\x1a\x16.google.protobuf.Empty\"\x00\x12X\n" +
	"\x16ReorderPaperCategories\x12$.proto.ReorderPaperCategoriesRequest\x1a\x16.google.protobuf.Empty\"\x00\x12I\n" +
	"\x15GetPaperQuestionsMeta\x12\x13.proto.PaperRequest\x1a\x19.proto.PaperQuestionsMeta\"\x00\x12K\n" +
	"\x16GetPaperCategoriesMeta\x12\x13.proto.PaperRequest\x1a\x1a.proto.PaperCategoriesMeta\"\x00B\bZ\x06/protob\x06proto3"

var (
	file_paper_proto_rawDescOnce sync.Once
	file_paper_proto_rawDescData []byte
)

func file_paper_proto_rawDescGZIP() []byte {
	file_paper_proto_rawDescOnce.Do(func() {
		file_paper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paper_proto_rawDesc), len(file_paper_proto_rawDesc)))
	})
	return file_paper_proto_rawDescData
}

var file_paper_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_paper_proto_goTypes = []any{
	(*PaperRequest)(nil),                  // 0: proto.PaperRequest
	(*PaperResponse)(nil),                 // 1: proto.PaperResponse
	(*CreatePaperResponse)(nil),           // 2: proto.CreatePaperResponse
	(*PaperList)(nil),                     // 3: proto.PaperList
	(*UpdatePaperRequest)(nil),            // 4: proto.UpdatePaperRequest
	(*QuestionCount)(nil),                 // 5: proto.QuestionCount
	(*DeletePapersRequest)(nil),           // 6: proto.DeletePapersRequest
	(*PaperQuestionRequest)(nil),          // 7: proto.PaperQuestionRequest
	(*PaperQuestionResponse)(nil),         // 8: proto.PaperQuestionResponse
	(*QuestionList)(nil),                  // 9: proto.QuestionList
	(*QuestionMinimal)(nil),               // 10: proto.QuestionMinimal
	(*PaperQuestionsMeta)(nil),            // 11: proto.PaperQuestionsMeta
	(*PaperQuestionMeta)(nil),             // 12: proto.PaperQuestionMeta
	(*CreatePaperQuestionRequest)(nil),    // 13: proto.CreatePaperQuestionRequest
	(*CreatePaperQuestionResponse)(nil),   // 14: proto.CreatePaperQuestionResponse
	(*UpdatePaperQuestionRequest)(nil),    // 15: proto.UpdatePaperQuestionRequest
	(*UpdatePaperQuestionResponse)(nil),   // 16: proto.UpdatePaperQuestionResponse
	(*ReorderPaperQuestionsRequest)(nil),  // 17: proto.ReorderPaperQuestionsRequest
	(*PaperCategoryRequest)(nil),          // 18: proto.PaperCategoryRequest
	(*PaperCategoryList)(nil),             // 19: proto.PaperCategoryList
	(*PaperCategoryResponse)(nil),         // 20: proto.PaperCategoryResponse
	(*PaperCategoriesMeta)(nil),           // 21: proto.PaperCategoriesMeta
	(*PaperCategoryMeta)(nil),             // 22: proto.PaperCategoryMeta
	(*CreatePaperCategoryRequest)(nil),    // 23: proto.CreatePaperCategoryRequest
	(*UpdatePaperCategoryRequest)(nil),    // 24: proto.UpdatePaperCategoryRequest
	(*ReorderPaperCategoriesRequest)(nil), // 25: proto.ReorderPaperCategoriesRequest
	(*PaperPermissionsResponse)(nil),      // 26: proto.PaperPermissionsResponse
	(*GetPaperBoilerplateRequest)(nil),    // 27: proto.GetPaperBoilerplateRequest
	(*UpsertPaperTestCasesRequest)(nil),   // 28: proto.UpsertPaperTestCasesRequest
	(QuestionType)(0),                     // 29: proto.QuestionType
	(*CodingQuestionTestCase)(nil),        // 30: proto.CodingQuestionTestCase
	(*UpsertTestCase)(nil),                // 31: proto.UpsertTestCase
	(*emptypb.Empty)(nil),                 // 32: google.protobuf.Empty
	(*BoilerplateResponse)(nil),           // 33: proto.BoilerplateResponse
}
var file_paper_proto_depIdxs = []int32{
	5,  // 0: proto.PaperResponse.question_counts:type_name -> proto.QuestionCount
	1,  // 1: proto.PaperList.papers:type_name -> proto.PaperResponse
	29, // 2: proto.PaperQuestionResponse.type:type_name -> proto.QuestionType
	30, // 3: proto.PaperQuestionResponse.test_cases:type_name -> proto.CodingQuestionTestCase
	10, // 4: proto.QuestionList.questions:type_name -> proto.QuestionMinimal
	12, // 5: proto.PaperQuestionsMeta.questions:type_name -> proto.PaperQuestionMeta
	29, // 6: proto.CreatePaperQuestionRequest.type:type_name -> proto.QuestionType
	29, // 7: proto.UpdatePaperQuestionRequest.type:type_name -> proto.QuestionType
	20, // 8: proto.PaperCategoryList.categories:type_name -> proto.PaperCategoryResponse
	22, // 9: proto.PaperCategoriesMeta.categories:type_name -> proto.PaperCategoryMeta
	31, // 10: proto.UpsertPaperTestCasesRequest.test_cases:type_name -> proto.UpsertTestCase
	32, // 11: proto.Paper.GetUserPapers:input_type -> google.protobuf.Empty
	0,  // 12: proto.Paper.GetPaper:input_type -> proto.PaperRequest
	32, // 13: proto.Paper.CreatePaper:input_type -> google.protobuf.Empty
	4,  // 14: proto.Paper.UpdatePaper:input_type -> proto.UpdatePaperRequest
	6,  // 15: proto.Paper.DeletePapers:input_type -> proto.DeletePapersRequest
	0,  // 16: proto.Paper.GetPaperPermissions:input_type -> proto.PaperRequest
	0,  // 17: proto.Paper.GetPaperQuestions:input_type -> proto.PaperRequest
	7,  // 18: proto.Paper.GetPaperQuestion:input_type -> proto.PaperQuestionRequest
	13, // 19: proto.Paper.CreatePaperQuestion:input_type -> proto.CreatePaperQuestionRequest
	15, // 20: proto.Paper.UpdatePaperQuestion:input_type -> proto.UpdatePaperQuestionRequest
	7,  // 21: proto.Paper.DeletePaperQuestion:input_type -> proto.PaperQuestionRequest
	17, // 22: proto.Paper.ReorderPaperQuestions:input_type -> proto.ReorderPaperQuestionsRequest
	27, // 23: proto.Paper.GetPaperBoilerplate:input_type -> proto.GetPaperBoilerplateRequest
	28, // 24: proto.Paper.UpsertPaperTestCases:input_type -> proto.UpsertPaperTestCasesRequest
	0,  // 25: proto.Paper.GetPaperCategories:input_type -> proto.PaperRequest
	23, // 26: proto.Paper.CreatePaperCategory:input_type -> proto.CreatePaperCategoryRequest
	24, // 27: proto.Paper.UpdatePaperCategory:input_type -> proto.UpdatePaperCategoryRequest
	18, // 28: proto.Paper.DeletePaperCategory:input_type -> proto.PaperCategoryRequest
	25, // 29: proto.Paper.ReorderPaperCategories:input_type -> proto.ReorderPaperCategoriesRequest
	0,  // 30: proto.Paper.GetPaperQuestionsMeta:input_type -> proto.PaperRequest
	0,  // 31: proto.Paper.GetPaperCategoriesMeta:input_type -> proto.PaperRequest
	3,  // 32: proto.Paper.GetUserPapers:output_type -> proto.PaperList
	1,  // 33: proto.Paper.GetPaper:output_type -> proto.PaperResponse
	2,  // 34: proto.Paper.CreatePaper:output_type -> proto.CreatePaperResponse
	32, // 35: proto.Paper.UpdatePaper:output_type -> google.protobuf.Empty
	32, // 36: proto.Paper.DeletePapers:output_type -> google.protobuf.Empty
	26, // 37: proto.Paper.GetPaperPermissions:output_type -> proto.PaperPermissionsResponse
	9,  // 38: proto.Paper.GetPaperQuestions:output_type -> proto.QuestionList
	8,  // 39: proto.Paper.GetPaperQuestion:output_type -> proto.PaperQuestionResponse
	14, // 40: proto.Paper.CreatePaperQuestion:output_type -> proto.CreatePaperQuestionResponse
	16, // 41: proto.Paper.UpdatePaperQuestion:output_type -> proto.UpdatePaperQuestionResponse
	32, // 42: proto.Paper.DeletePaperQuestion:output_type -> google.protobuf.Empty
	32, // 43: proto.Paper.ReorderPaperQuestions:output_type -> google.protobuf.Empty
	33, // 44: proto.Paper.GetPaperBoilerplate:output_type -> proto.BoilerplateResponse
	32, // 45: proto.Paper.UpsertPaperTestCases:output_type -> google.protobuf.Empty
	19, // 46: proto.Paper.GetPaperCategories:output_type -> proto.PaperCategoryList
	20, // 47: proto.Paper.CreatePaperCategory:output_type -> proto.PaperCategoryResponse
	32, // 48: proto.Paper.UpdatePaperCategory:output_type -> google.protobuf.Empty
	32, // 49: proto.Paper.DeletePaperCategory:output_type -> google.protobuf.Empty
	32, // 50: proto.Paper.ReorderPaperCategories:output_type -> google.protobuf.Empty
	11, // 51: proto.Paper.GetPaperQuestionsMeta:output_type -> proto.PaperQuestionsMeta
	21, // 52: proto.Paper.GetPaperCategoriesMeta:output_type -> proto.PaperCategoriesMeta
	32, // [32:53] is the sub-list for method output_type
	11, // [11:32] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_paper_proto_init() }
func file_paper_proto_init() {
	if File_paper_proto != nil {
		return
	}
	file_common_proto_init()
	file_paper_proto_msgTypes[4].OneofWrappers = []any{}
	file_paper_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paper_proto_rawDesc), len(file_paper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paper_proto_goTypes,
		DependencyIndexes: file_paper_proto_depIdxs,
		MessageInfos:      file_paper_proto_msgTypes,
	}.Build()
	File_paper_proto = out.File
	file_paper_proto_goTypes = nil
	file_paper_proto_depIdxs = nil
}
