// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: question.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Question_CreateQuestion_FullMethodName                    = "/proto.Question/CreateQuestion"
	Question_UpdateQuestion_FullMethodName                    = "/proto.Question/UpdateQuestion"
	Question_GetQuestionsByIds_FullMethodName                 = "/proto.Question/GetQuestionsByIds"
	Question_GetQuestionsByHashes_FullMethodName              = "/proto.Question/GetQuestionsByHashes"
	Question_GetQuestionsMetaByIds_FullMethodName             = "/proto.Question/GetQuestionsMetaByIds"
	Question_GetQuestionsMetaByHashes_FullMethodName          = "/proto.Question/GetQuestionsMetaByHashes"
	Question_GetQuestionIdsByHashes_FullMethodName            = "/proto.Question/GetQuestionIdsByHashes"
	Question_GetQuestionHashesByIds_FullMethodName            = "/proto.Question/GetQuestionHashesByIds"
	Question_IncQuestionPaperIndegreeByIds_FullMethodName     = "/proto.Question/IncQuestionPaperIndegreeByIds"
	Question_DecQuestionPaperIndegreeByIds_FullMethodName     = "/proto.Question/DecQuestionPaperIndegreeByIds"
	Question_IncQuestionExamIndegreeByIds_FullMethodName      = "/proto.Question/IncQuestionExamIndegreeByIds"
	Question_DecQuestionExamIndegreeByIds_FullMethodName      = "/proto.Question/DecQuestionExamIndegreeByIds"
	Question_UpsertTestCases_FullMethodName                   = "/proto.Question/UpsertTestCases"
	Question_GetBoilerplate_FullMethodName                    = "/proto.Question/GetBoilerplate"
	Question_CreateCategory_FullMethodName                    = "/proto.Question/CreateCategory"
	Question_GetCategoriesByIds_FullMethodName                = "/proto.Question/GetCategoriesByIds"
	Question_UpdateCategoryName_FullMethodName                = "/proto.Question/UpdateCategoryName"
	Question_GetCodingQuestionInputDefinitions_FullMethodName = "/proto.Question/GetCodingQuestionInputDefinitions"
)

// QuestionClient is the client API for Question service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuestionClient interface {
	// Question operations
	CreateQuestion(ctx context.Context, in *CreateQuestionRequest, opts ...grpc.CallOption) (*CreateQuestionResponse, error)
	UpdateQuestion(ctx context.Context, in *UpdateQuestionRequest, opts ...grpc.CallOption) (*UpdateQuestionResponse, error)
	GetQuestionsByIds(ctx context.Context, in *QuestionIdsRequest, opts ...grpc.CallOption) (*GetQuestionsResponse, error)
	GetQuestionsByHashes(ctx context.Context, in *QuestionHashesRequest, opts ...grpc.CallOption) (*GetQuestionsResponse, error)
	GetQuestionsMetaByIds(ctx context.Context, in *QuestionIdsRequest, opts ...grpc.CallOption) (*QuestionsMetaResponse, error)
	GetQuestionsMetaByHashes(ctx context.Context, in *QuestionHashesRequest, opts ...grpc.CallOption) (*QuestionsMetaResponse, error)
	GetQuestionIdsByHashes(ctx context.Context, in *QuestionHashesRequest, opts ...grpc.CallOption) (*GetQuestionIdsByHashesResponse, error)
	GetQuestionHashesByIds(ctx context.Context, in *QuestionIdsRequest, opts ...grpc.CallOption) (*GetQuestionHashesByIdsResponse, error)
	IncQuestionPaperIndegreeByIds(ctx context.Context, in *QuestionIdsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DecQuestionPaperIndegreeByIds(ctx context.Context, in *QuestionIdsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	IncQuestionExamIndegreeByIds(ctx context.Context, in *QuestionIdsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DecQuestionExamIndegreeByIds(ctx context.Context, in *QuestionIdsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpsertTestCases(ctx context.Context, in *UpsertTestCasesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetBoilerplate(ctx context.Context, in *GetBoilerplateRequest, opts ...grpc.CallOption) (*BoilerplateResponse, error)
	// Category operations
	CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error)
	GetCategoriesByIds(ctx context.Context, in *CategoryIdsRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
	UpdateCategoryName(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error)
	// Engine Operations
	GetCodingQuestionInputDefinitions(ctx context.Context, in *GetCodingQuestionInputDefinitionsRequest, opts ...grpc.CallOption) (*GetCodingQuestionInputDefinitionsResponse, error)
}

type questionClient struct {
	cc grpc.ClientConnInterface
}

func NewQuestionClient(cc grpc.ClientConnInterface) QuestionClient {
	return &questionClient{cc}
}

func (c *questionClient) CreateQuestion(ctx context.Context, in *CreateQuestionRequest, opts ...grpc.CallOption) (*CreateQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateQuestionResponse)
	err := c.cc.Invoke(ctx, Question_CreateQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) UpdateQuestion(ctx context.Context, in *UpdateQuestionRequest, opts ...grpc.CallOption) (*UpdateQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateQuestionResponse)
	err := c.cc.Invoke(ctx, Question_UpdateQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GetQuestionsByIds(ctx context.Context, in *QuestionIdsRequest, opts ...grpc.CallOption) (*GetQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuestionsResponse)
	err := c.cc.Invoke(ctx, Question_GetQuestionsByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GetQuestionsByHashes(ctx context.Context, in *QuestionHashesRequest, opts ...grpc.CallOption) (*GetQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuestionsResponse)
	err := c.cc.Invoke(ctx, Question_GetQuestionsByHashes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GetQuestionsMetaByIds(ctx context.Context, in *QuestionIdsRequest, opts ...grpc.CallOption) (*QuestionsMetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionsMetaResponse)
	err := c.cc.Invoke(ctx, Question_GetQuestionsMetaByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GetQuestionsMetaByHashes(ctx context.Context, in *QuestionHashesRequest, opts ...grpc.CallOption) (*QuestionsMetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionsMetaResponse)
	err := c.cc.Invoke(ctx, Question_GetQuestionsMetaByHashes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GetQuestionIdsByHashes(ctx context.Context, in *QuestionHashesRequest, opts ...grpc.CallOption) (*GetQuestionIdsByHashesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuestionIdsByHashesResponse)
	err := c.cc.Invoke(ctx, Question_GetQuestionIdsByHashes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GetQuestionHashesByIds(ctx context.Context, in *QuestionIdsRequest, opts ...grpc.CallOption) (*GetQuestionHashesByIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuestionHashesByIdsResponse)
	err := c.cc.Invoke(ctx, Question_GetQuestionHashesByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) IncQuestionPaperIndegreeByIds(ctx context.Context, in *QuestionIdsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Question_IncQuestionPaperIndegreeByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) DecQuestionPaperIndegreeByIds(ctx context.Context, in *QuestionIdsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Question_DecQuestionPaperIndegreeByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) IncQuestionExamIndegreeByIds(ctx context.Context, in *QuestionIdsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Question_IncQuestionExamIndegreeByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) DecQuestionExamIndegreeByIds(ctx context.Context, in *QuestionIdsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Question_DecQuestionExamIndegreeByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) UpsertTestCases(ctx context.Context, in *UpsertTestCasesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Question_UpsertTestCases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GetBoilerplate(ctx context.Context, in *GetBoilerplateRequest, opts ...grpc.CallOption) (*BoilerplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoilerplateResponse)
	err := c.cc.Invoke(ctx, Question_GetBoilerplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryResponse)
	err := c.cc.Invoke(ctx, Question_CreateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GetCategoriesByIds(ctx context.Context, in *CategoryIdsRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoriesResponse)
	err := c.cc.Invoke(ctx, Question_GetCategoriesByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) UpdateCategoryName(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCategoryResponse)
	err := c.cc.Invoke(ctx, Question_UpdateCategoryName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GetCodingQuestionInputDefinitions(ctx context.Context, in *GetCodingQuestionInputDefinitionsRequest, opts ...grpc.CallOption) (*GetCodingQuestionInputDefinitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCodingQuestionInputDefinitionsResponse)
	err := c.cc.Invoke(ctx, Question_GetCodingQuestionInputDefinitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuestionServer is the server API for Question service.
// All implementations must embed UnimplementedQuestionServer
// for forward compatibility.
type QuestionServer interface {
	// Question operations
	CreateQuestion(context.Context, *CreateQuestionRequest) (*CreateQuestionResponse, error)
	UpdateQuestion(context.Context, *UpdateQuestionRequest) (*UpdateQuestionResponse, error)
	GetQuestionsByIds(context.Context, *QuestionIdsRequest) (*GetQuestionsResponse, error)
	GetQuestionsByHashes(context.Context, *QuestionHashesRequest) (*GetQuestionsResponse, error)
	GetQuestionsMetaByIds(context.Context, *QuestionIdsRequest) (*QuestionsMetaResponse, error)
	GetQuestionsMetaByHashes(context.Context, *QuestionHashesRequest) (*QuestionsMetaResponse, error)
	GetQuestionIdsByHashes(context.Context, *QuestionHashesRequest) (*GetQuestionIdsByHashesResponse, error)
	GetQuestionHashesByIds(context.Context, *QuestionIdsRequest) (*GetQuestionHashesByIdsResponse, error)
	IncQuestionPaperIndegreeByIds(context.Context, *QuestionIdsRequest) (*emptypb.Empty, error)
	DecQuestionPaperIndegreeByIds(context.Context, *QuestionIdsRequest) (*emptypb.Empty, error)
	IncQuestionExamIndegreeByIds(context.Context, *QuestionIdsRequest) (*emptypb.Empty, error)
	DecQuestionExamIndegreeByIds(context.Context, *QuestionIdsRequest) (*emptypb.Empty, error)
	UpsertTestCases(context.Context, *UpsertTestCasesRequest) (*emptypb.Empty, error)
	GetBoilerplate(context.Context, *GetBoilerplateRequest) (*BoilerplateResponse, error)
	// Category operations
	CreateCategory(context.Context, *CreateCategoryRequest) (*CategoryResponse, error)
	GetCategoriesByIds(context.Context, *CategoryIdsRequest) (*GetCategoriesResponse, error)
	UpdateCategoryName(context.Context, *UpdateCategoryRequest) (*UpdateCategoryResponse, error)
	// Engine Operations
	GetCodingQuestionInputDefinitions(context.Context, *GetCodingQuestionInputDefinitionsRequest) (*GetCodingQuestionInputDefinitionsResponse, error)
	mustEmbedUnimplementedQuestionServer()
}

// UnimplementedQuestionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuestionServer struct{}

func (UnimplementedQuestionServer) CreateQuestion(context.Context, *CreateQuestionRequest) (*CreateQuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQuestion not implemented")
}
func (UnimplementedQuestionServer) UpdateQuestion(context.Context, *UpdateQuestionRequest) (*UpdateQuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateQuestion not implemented")
}
func (UnimplementedQuestionServer) GetQuestionsByIds(context.Context, *QuestionIdsRequest) (*GetQuestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestionsByIds not implemented")
}
func (UnimplementedQuestionServer) GetQuestionsByHashes(context.Context, *QuestionHashesRequest) (*GetQuestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestionsByHashes not implemented")
}
func (UnimplementedQuestionServer) GetQuestionsMetaByIds(context.Context, *QuestionIdsRequest) (*QuestionsMetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestionsMetaByIds not implemented")
}
func (UnimplementedQuestionServer) GetQuestionsMetaByHashes(context.Context, *QuestionHashesRequest) (*QuestionsMetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestionsMetaByHashes not implemented")
}
func (UnimplementedQuestionServer) GetQuestionIdsByHashes(context.Context, *QuestionHashesRequest) (*GetQuestionIdsByHashesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestionIdsByHashes not implemented")
}
func (UnimplementedQuestionServer) GetQuestionHashesByIds(context.Context, *QuestionIdsRequest) (*GetQuestionHashesByIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestionHashesByIds not implemented")
}
func (UnimplementedQuestionServer) IncQuestionPaperIndegreeByIds(context.Context, *QuestionIdsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncQuestionPaperIndegreeByIds not implemented")
}
func (UnimplementedQuestionServer) DecQuestionPaperIndegreeByIds(context.Context, *QuestionIdsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecQuestionPaperIndegreeByIds not implemented")
}
func (UnimplementedQuestionServer) IncQuestionExamIndegreeByIds(context.Context, *QuestionIdsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncQuestionExamIndegreeByIds not implemented")
}
func (UnimplementedQuestionServer) DecQuestionExamIndegreeByIds(context.Context, *QuestionIdsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecQuestionExamIndegreeByIds not implemented")
}
func (UnimplementedQuestionServer) UpsertTestCases(context.Context, *UpsertTestCasesRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertTestCases not implemented")
}
func (UnimplementedQuestionServer) GetBoilerplate(context.Context, *GetBoilerplateRequest) (*BoilerplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBoilerplate not implemented")
}
func (UnimplementedQuestionServer) CreateCategory(context.Context, *CreateCategoryRequest) (*CategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedQuestionServer) GetCategoriesByIds(context.Context, *CategoryIdsRequest) (*GetCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategoriesByIds not implemented")
}
func (UnimplementedQuestionServer) UpdateCategoryName(context.Context, *UpdateCategoryRequest) (*UpdateCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCategoryName not implemented")
}
func (UnimplementedQuestionServer) GetCodingQuestionInputDefinitions(context.Context, *GetCodingQuestionInputDefinitionsRequest) (*GetCodingQuestionInputDefinitionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCodingQuestionInputDefinitions not implemented")
}
func (UnimplementedQuestionServer) mustEmbedUnimplementedQuestionServer() {}
func (UnimplementedQuestionServer) testEmbeddedByValue()                  {}

// UnsafeQuestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuestionServer will
// result in compilation errors.
type UnsafeQuestionServer interface {
	mustEmbedUnimplementedQuestionServer()
}

func RegisterQuestionServer(s grpc.ServiceRegistrar, srv QuestionServer) {
	// If the following call pancis, it indicates UnimplementedQuestionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Question_ServiceDesc, srv)
}

func _Question_CreateQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).CreateQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_CreateQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).CreateQuestion(ctx, req.(*CreateQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_UpdateQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).UpdateQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_UpdateQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).UpdateQuestion(ctx, req.(*UpdateQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GetQuestionsByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GetQuestionsByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_GetQuestionsByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GetQuestionsByIds(ctx, req.(*QuestionIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GetQuestionsByHashes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionHashesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GetQuestionsByHashes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_GetQuestionsByHashes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GetQuestionsByHashes(ctx, req.(*QuestionHashesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GetQuestionsMetaByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GetQuestionsMetaByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_GetQuestionsMetaByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GetQuestionsMetaByIds(ctx, req.(*QuestionIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GetQuestionsMetaByHashes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionHashesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GetQuestionsMetaByHashes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_GetQuestionsMetaByHashes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GetQuestionsMetaByHashes(ctx, req.(*QuestionHashesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GetQuestionIdsByHashes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionHashesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GetQuestionIdsByHashes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_GetQuestionIdsByHashes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GetQuestionIdsByHashes(ctx, req.(*QuestionHashesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GetQuestionHashesByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GetQuestionHashesByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_GetQuestionHashesByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GetQuestionHashesByIds(ctx, req.(*QuestionIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_IncQuestionPaperIndegreeByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).IncQuestionPaperIndegreeByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_IncQuestionPaperIndegreeByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).IncQuestionPaperIndegreeByIds(ctx, req.(*QuestionIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_DecQuestionPaperIndegreeByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).DecQuestionPaperIndegreeByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_DecQuestionPaperIndegreeByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).DecQuestionPaperIndegreeByIds(ctx, req.(*QuestionIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_IncQuestionExamIndegreeByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).IncQuestionExamIndegreeByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_IncQuestionExamIndegreeByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).IncQuestionExamIndegreeByIds(ctx, req.(*QuestionIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_DecQuestionExamIndegreeByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).DecQuestionExamIndegreeByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_DecQuestionExamIndegreeByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).DecQuestionExamIndegreeByIds(ctx, req.(*QuestionIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_UpsertTestCases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertTestCasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).UpsertTestCases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_UpsertTestCases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).UpsertTestCases(ctx, req.(*UpsertTestCasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GetBoilerplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBoilerplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GetBoilerplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_GetBoilerplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GetBoilerplate(ctx, req.(*GetBoilerplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).CreateCategory(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GetCategoriesByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GetCategoriesByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_GetCategoriesByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GetCategoriesByIds(ctx, req.(*CategoryIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_UpdateCategoryName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).UpdateCategoryName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_UpdateCategoryName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).UpdateCategoryName(ctx, req.(*UpdateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GetCodingQuestionInputDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCodingQuestionInputDefinitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GetCodingQuestionInputDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_GetCodingQuestionInputDefinitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GetCodingQuestionInputDefinitions(ctx, req.(*GetCodingQuestionInputDefinitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Question_ServiceDesc is the grpc.ServiceDesc for Question service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Question_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Question",
	HandlerType: (*QuestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQuestion",
			Handler:    _Question_CreateQuestion_Handler,
		},
		{
			MethodName: "UpdateQuestion",
			Handler:    _Question_UpdateQuestion_Handler,
		},
		{
			MethodName: "GetQuestionsByIds",
			Handler:    _Question_GetQuestionsByIds_Handler,
		},
		{
			MethodName: "GetQuestionsByHashes",
			Handler:    _Question_GetQuestionsByHashes_Handler,
		},
		{
			MethodName: "GetQuestionsMetaByIds",
			Handler:    _Question_GetQuestionsMetaByIds_Handler,
		},
		{
			MethodName: "GetQuestionsMetaByHashes",
			Handler:    _Question_GetQuestionsMetaByHashes_Handler,
		},
		{
			MethodName: "GetQuestionIdsByHashes",
			Handler:    _Question_GetQuestionIdsByHashes_Handler,
		},
		{
			MethodName: "GetQuestionHashesByIds",
			Handler:    _Question_GetQuestionHashesByIds_Handler,
		},
		{
			MethodName: "IncQuestionPaperIndegreeByIds",
			Handler:    _Question_IncQuestionPaperIndegreeByIds_Handler,
		},
		{
			MethodName: "DecQuestionPaperIndegreeByIds",
			Handler:    _Question_DecQuestionPaperIndegreeByIds_Handler,
		},
		{
			MethodName: "IncQuestionExamIndegreeByIds",
			Handler:    _Question_IncQuestionExamIndegreeByIds_Handler,
		},
		{
			MethodName: "DecQuestionExamIndegreeByIds",
			Handler:    _Question_DecQuestionExamIndegreeByIds_Handler,
		},
		{
			MethodName: "UpsertTestCases",
			Handler:    _Question_UpsertTestCases_Handler,
		},
		{
			MethodName: "GetBoilerplate",
			Handler:    _Question_GetBoilerplate_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _Question_CreateCategory_Handler,
		},
		{
			MethodName: "GetCategoriesByIds",
			Handler:    _Question_GetCategoriesByIds_Handler,
		},
		{
			MethodName: "UpdateCategoryName",
			Handler:    _Question_UpdateCategoryName_Handler,
		},
		{
			MethodName: "GetCodingQuestionInputDefinitions",
			Handler:    _Question_GetCodingQuestionInputDefinitions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "question.proto",
}
