// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: question.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawQuestion   []byte                 `protobuf:"bytes,1,opt,name=raw_question,json=rawQuestion,proto3" json:"raw_question,omitempty"`
	Type          QuestionType           `protobuf:"varint,2,opt,name=type,proto3,enum=proto.QuestionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionRequest) Reset() {
	*x = CreateQuestionRequest{}
	mi := &file_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionRequest) ProtoMessage() {}

func (x *CreateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionRequest.ProtoReflect.Descriptor instead.
func (*CreateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{0}
}

func (x *CreateQuestionRequest) GetRawQuestion() []byte {
	if x != nil {
		return x.RawQuestion
	}
	return nil
}

func (x *CreateQuestionRequest) GetType() QuestionType {
	if x != nil {
		return x.Type
	}
	return QuestionType_UNKNOWN_QUESTION_TYPE
}

type CreateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionResponse) Reset() {
	*x = CreateQuestionResponse{}
	mi := &file_question_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionResponse) ProtoMessage() {}

func (x *CreateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionResponse.ProtoReflect.Descriptor instead.
func (*CreateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{1}
}

func (x *CreateQuestionResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateQuestionResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type UpdateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Type          *QuestionType          `protobuf:"varint,2,opt,name=type,proto3,enum=proto.QuestionType,oneof" json:"type,omitempty"`
	RawQuestion   []byte                 `protobuf:"bytes,3,opt,name=raw_question,json=rawQuestion,proto3,oneof" json:"raw_question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionRequest) Reset() {
	*x = UpdateQuestionRequest{}
	mi := &file_question_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionRequest) ProtoMessage() {}

func (x *UpdateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateQuestionRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *UpdateQuestionRequest) GetType() QuestionType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return QuestionType_UNKNOWN_QUESTION_TYPE
}

func (x *UpdateQuestionRequest) GetRawQuestion() []byte {
	if x != nil {
		return x.RawQuestion
	}
	return nil
}

type UpdateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionResponse) Reset() {
	*x = UpdateQuestionResponse{}
	mi := &file_question_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionResponse) ProtoMessage() {}

func (x *UpdateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateQuestionResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateQuestionResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type QuestionIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionIdsRequest) Reset() {
	*x = QuestionIdsRequest{}
	mi := &file_question_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionIdsRequest) ProtoMessage() {}

func (x *QuestionIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionIdsRequest.ProtoReflect.Descriptor instead.
func (*QuestionIdsRequest) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{4}
}

func (x *QuestionIdsRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*QuestionResponse    `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionsResponse) Reset() {
	*x = GetQuestionsResponse{}
	mi := &file_question_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionsResponse) ProtoMessage() {}

func (x *GetQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionsResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{5}
}

func (x *GetQuestionsResponse) GetQuestions() []*QuestionResponse {
	if x != nil {
		return x.Questions
	}
	return nil
}

type QuestionsMetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          []*QuestionMeta        `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionsMetaResponse) Reset() {
	*x = QuestionsMetaResponse{}
	mi := &file_question_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionsMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionsMetaResponse) ProtoMessage() {}

func (x *QuestionsMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionsMetaResponse.ProtoReflect.Descriptor instead.
func (*QuestionsMetaResponse) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{6}
}

func (x *QuestionsMetaResponse) GetMeta() []*QuestionMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type QuestionHashesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        []string               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionHashesRequest) Reset() {
	*x = QuestionHashesRequest{}
	mi := &file_question_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionHashesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionHashesRequest) ProtoMessage() {}

func (x *QuestionHashesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionHashesRequest.ProtoReflect.Descriptor instead.
func (*QuestionHashesRequest) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{7}
}

func (x *QuestionHashesRequest) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type GetQuestionIdsByHashesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionIdsByHashesResponse) Reset() {
	*x = GetQuestionIdsByHashesResponse{}
	mi := &file_question_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionIdsByHashesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionIdsByHashesResponse) ProtoMessage() {}

func (x *GetQuestionIdsByHashesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionIdsByHashesResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionIdsByHashesResponse) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{8}
}

func (x *GetQuestionIdsByHashesResponse) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetQuestionHashesByIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        []string               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionHashesByIdsResponse) Reset() {
	*x = GetQuestionHashesByIdsResponse{}
	mi := &file_question_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionHashesByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionHashesByIdsResponse) ProtoMessage() {}

func (x *GetQuestionHashesByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionHashesByIdsResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionHashesByIdsResponse) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{9}
}

func (x *GetQuestionHashesByIdsResponse) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type QuestionResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            int64                     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash          string                    `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	RawQuestion   []byte                    `protobuf:"bytes,3,opt,name=raw_question,json=rawQuestion,proto3" json:"raw_question,omitempty"`
	Type          QuestionType              `protobuf:"varint,4,opt,name=type,proto3,enum=proto.QuestionType" json:"type,omitempty"`
	TestCases     []*CodingQuestionTestCase `protobuf:"bytes,5,rep,name=test_cases,json=testCases,proto3" json:"test_cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionResponse) Reset() {
	*x = QuestionResponse{}
	mi := &file_question_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionResponse) ProtoMessage() {}

func (x *QuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionResponse.ProtoReflect.Descriptor instead.
func (*QuestionResponse) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{10}
}

func (x *QuestionResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuestionResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *QuestionResponse) GetRawQuestion() []byte {
	if x != nil {
		return x.RawQuestion
	}
	return nil
}

func (x *QuestionResponse) GetType() QuestionType {
	if x != nil {
		return x.Type
	}
	return QuestionType_UNKNOWN_QUESTION_TYPE
}

func (x *QuestionResponse) GetTestCases() []*CodingQuestionTestCase {
	if x != nil {
		return x.TestCases
	}
	return nil
}

type QuestionMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	RawQuestion   []byte                 `protobuf:"bytes,3,opt,name=raw_question,json=rawQuestion,proto3" json:"raw_question,omitempty"`
	Type          QuestionType           `protobuf:"varint,4,opt,name=type,proto3,enum=proto.QuestionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionMeta) Reset() {
	*x = QuestionMeta{}
	mi := &file_question_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionMeta) ProtoMessage() {}

func (x *QuestionMeta) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionMeta.ProtoReflect.Descriptor instead.
func (*QuestionMeta) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{11}
}

func (x *QuestionMeta) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuestionMeta) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *QuestionMeta) GetRawQuestion() []byte {
	if x != nil {
		return x.RawQuestion
	}
	return nil
}

func (x *QuestionMeta) GetType() QuestionType {
	if x != nil {
		return x.Type
	}
	return QuestionType_UNKNOWN_QUESTION_TYPE
}

type GetBoilerplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionHash  string                 `protobuf:"bytes,1,opt,name=question_hash,json=questionHash,proto3" json:"question_hash,omitempty"`
	LanguageId    int32                  `protobuf:"varint,2,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoilerplateRequest) Reset() {
	*x = GetBoilerplateRequest{}
	mi := &file_question_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoilerplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoilerplateRequest) ProtoMessage() {}

func (x *GetBoilerplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoilerplateRequest.ProtoReflect.Descriptor instead.
func (*GetBoilerplateRequest) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{12}
}

func (x *GetBoilerplateRequest) GetQuestionHash() string {
	if x != nil {
		return x.QuestionHash
	}
	return ""
}

func (x *GetBoilerplateRequest) GetLanguageId() int32 {
	if x != nil {
		return x.LanguageId
	}
	return 0
}

type UpsertTestCasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionHash  string                 `protobuf:"bytes,1,opt,name=question_hash,json=questionHash,proto3" json:"question_hash,omitempty"`
	TestCases     []*UpsertTestCase      `protobuf:"bytes,2,rep,name=test_cases,json=testCases,proto3" json:"test_cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTestCasesRequest) Reset() {
	*x = UpsertTestCasesRequest{}
	mi := &file_question_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTestCasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTestCasesRequest) ProtoMessage() {}

func (x *UpsertTestCasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTestCasesRequest.ProtoReflect.Descriptor instead.
func (*UpsertTestCasesRequest) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{13}
}

func (x *UpsertTestCasesRequest) GetQuestionHash() string {
	if x != nil {
		return x.QuestionHash
	}
	return ""
}

func (x *UpsertTestCasesRequest) GetTestCases() []*UpsertTestCase {
	if x != nil {
		return x.TestCases
	}
	return nil
}

type CategoryIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryIdsRequest) Reset() {
	*x = CategoryIdsRequest{}
	mi := &file_question_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryIdsRequest) ProtoMessage() {}

func (x *CategoryIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryIdsRequest.ProtoReflect.Descriptor instead.
func (*CategoryIdsRequest) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{14}
}

func (x *CategoryIdsRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryResponse) Reset() {
	*x = CategoryResponse{}
	mi := &file_question_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryResponse) ProtoMessage() {}

func (x *CategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryResponse.ProtoReflect.Descriptor instead.
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{15}
}

func (x *CategoryResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CategoryResponse    `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesResponse) Reset() {
	*x = GetCategoriesResponse{}
	mi := &file_question_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesResponse) ProtoMessage() {}

func (x *GetCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{16}
}

func (x *GetCategoriesResponse) GetCategories() []*CategoryResponse {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_question_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{17}
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_question_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryResponse) Reset() {
	*x = UpdateCategoryResponse{}
	mi := &file_question_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryResponse) ProtoMessage() {}

func (x *UpdateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateCategoryResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCodingQuestionInputDefinitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionHash  string                 `protobuf:"bytes,1,opt,name=question_hash,json=questionHash,proto3" json:"question_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCodingQuestionInputDefinitionsRequest) Reset() {
	*x = GetCodingQuestionInputDefinitionsRequest{}
	mi := &file_question_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCodingQuestionInputDefinitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCodingQuestionInputDefinitionsRequest) ProtoMessage() {}

func (x *GetCodingQuestionInputDefinitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCodingQuestionInputDefinitionsRequest.ProtoReflect.Descriptor instead.
func (*GetCodingQuestionInputDefinitionsRequest) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{20}
}

func (x *GetCodingQuestionInputDefinitionsRequest) GetQuestionHash() string {
	if x != nil {
		return x.QuestionHash
	}
	return ""
}

type GetCodingQuestionInputDefinitionsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InputDefinitions []*InputDefinition     `protobuf:"bytes,1,rep,name=input_definitions,json=inputDefinitions,proto3" json:"input_definitions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetCodingQuestionInputDefinitionsResponse) Reset() {
	*x = GetCodingQuestionInputDefinitionsResponse{}
	mi := &file_question_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCodingQuestionInputDefinitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCodingQuestionInputDefinitionsResponse) ProtoMessage() {}

func (x *GetCodingQuestionInputDefinitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCodingQuestionInputDefinitionsResponse.ProtoReflect.Descriptor instead.
func (*GetCodingQuestionInputDefinitionsResponse) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{21}
}

func (x *GetCodingQuestionInputDefinitionsResponse) GetInputDefinitions() []*InputDefinition {
	if x != nil {
		return x.InputDefinitions
	}
	return nil
}

type InputDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VariableName  string                 `protobuf:"bytes,1,opt,name=variable_name,json=variableName,proto3" json:"variable_name,omitempty"`
	Type          ParameterType          `protobuf:"varint,2,opt,name=type,proto3,enum=proto.ParameterType" json:"type,omitempty"`
	Items         []*ParameterItem       `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputDefinition) Reset() {
	*x = InputDefinition{}
	mi := &file_question_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputDefinition) ProtoMessage() {}

func (x *InputDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputDefinition.ProtoReflect.Descriptor instead.
func (*InputDefinition) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{22}
}

func (x *InputDefinition) GetVariableName() string {
	if x != nil {
		return x.VariableName
	}
	return ""
}

func (x *InputDefinition) GetType() ParameterType {
	if x != nil {
		return x.Type
	}
	return ParameterType_UNKNOWN_PARAMETER_TYPE
}

func (x *InputDefinition) GetItems() []*ParameterItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ParameterItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyName  *string                `protobuf:"bytes,1,opt,name=property_name,json=propertyName,proto3,oneof" json:"property_name,omitempty"`
	Type          ParameterType          `protobuf:"varint,2,opt,name=type,proto3,enum=proto.ParameterType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterItem) Reset() {
	*x = ParameterItem{}
	mi := &file_question_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterItem) ProtoMessage() {}

func (x *ParameterItem) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterItem.ProtoReflect.Descriptor instead.
func (*ParameterItem) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{23}
}

func (x *ParameterItem) GetPropertyName() string {
	if x != nil && x.PropertyName != nil {
		return *x.PropertyName
	}
	return ""
}

func (x *ParameterItem) GetType() ParameterType {
	if x != nil {
		return x.Type
	}
	return ParameterType_UNKNOWN_PARAMETER_TYPE
}

var File_question_proto protoreflect.FileDescriptor

const file_question_proto_rawDesc = "" +
	"\n" +
	"\x0equestion.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\fcommon.proto\"c\n" +
	"\x15CreateQuestionRequest\x12!\n" +
	"\fraw_question\x18\x01 \x01(\fR\vrawQuestion\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.proto.QuestionTypeR\x04type\"<\n" +
	"\x16CreateQuestionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"\x9b\x01\n" +
	"\x15UpdateQuestionRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.proto.QuestionTypeH\x00R\x04type\x88\x01\x01\x12&\n" +
	"\fraw_question\x18\x03 \x01(\fH\x01R\vrawQuestion\x88\x01\x01B\a\n" +
	"\x05_typeB\x0f\n" +
	"\r_raw_question\"<\n" +
	"\x16UpdateQuestionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"&\n" +
	"\x12QuestionIdsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"M\n" +
	"\x14GetQuestionsResponse\x125\n" +
	"\tquestions\x18\x01 \x03(\v2\x17.proto.QuestionResponseR\tquestions\"@\n" +
	"\x15QuestionsMetaResponse\x12'\n" +
	"\x04meta\x18\x01 \x03(\v2\x13.proto.QuestionMetaR\x04meta\"/\n" +
	"\x15QuestionHashesRequest\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\tR\x06hashes\"2\n" +
	"\x1eGetQuestionIdsByHashesResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"8\n" +
	"\x1eGetQuestionHashesByIdsResponse\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\tR\x06hashes\"\xc0\x01\n" +
	"\x10QuestionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12!\n" +
	"\fraw_question\x18\x03 \x01(\fR\vrawQuestion\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.proto.QuestionTypeR\x04type\x12<\n" +
	"\n" +
	"test_cases\x18\x05 \x03(\v2\x1d.proto.CodingQuestionTestCaseR\ttestCases\"~\n" +
	"\fQuestionMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12!\n" +
	"\fraw_question\x18\x03 \x01(\fR\vrawQuestion\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.proto.QuestionTypeR\x04type\"]\n" +
	"\x15GetBoilerplateRequest\x12#\n" +
	"\rquestion_hash\x18\x01 \x01(\tR\fquestionHash\x12\x1f\n" +
	"\vlanguage_id\x18\x02 \x01(\x05R\n" +
	"languageId\"s\n" +
	"\x16UpsertTestCasesRequest\x12#\n" +
	"\rquestion_hash\x18\x01 \x01(\tR\fquestionHash\x124\n" +
	"\n" +
	"test_cases\x18\x02 \x03(\v2\x15.proto.UpsertTestCaseR\ttestCases\"&\n" +
	"\x12CategoryIdsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"6\n" +
	"\x10CategoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"P\n" +
	"\x15GetCategoriesResponse\x127\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x17.proto.CategoryResponseR\n" +
	"categories\"+\n" +
	"\x15CreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\";\n" +
	"\x15UpdateCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"(\n" +
	"\x16UpdateCategoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"O\n" +
	"(GetCodingQuestionInputDefinitionsRequest\x12#\n" +
	"\rquestion_hash\x18\x01 \x01(\tR\fquestionHash\"p\n" +
	")GetCodingQuestionInputDefinitionsResponse\x12C\n" +
	"\x11input_definitions\x18\x01 \x03(\v2\x16.proto.InputDefinitionR\x10inputDefinitions\"\x8c\x01\n" +
	"\x0fInputDefinition\x12#\n" +
	"\rvariable_name\x18\x01 \x01(\tR\fvariableName\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.proto.ParameterTypeR\x04type\x12*\n" +
	"\x05items\x18\x03 \x03(\v2\x14.proto.ParameterItemR\x05items\"u\n" +
	"\rParameterItem\x12(\n" +
	"\rproperty_name\x18\x01 \x01(\tH\x00R\fpropertyName\x88\x01\x01\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.proto.ParameterTypeR\x04typeB\x10\n" +
	"\x0e_property_name2\xa9\f\n" +
	"\bQuestion\x12O\n" +
	"\x0eCreateQuestion\x12\x1c.proto.CreateQuestionRequest\x1a\x1d.proto.CreateQuestionResponse\"\x00\x12O\n" +
	"\x0eUpdateQuestion\x12\x1c.proto.UpdateQuestionRequest\x1a\x1d.proto.UpdateQuestionResponse\"\x00\x12M\n" +
	"\x11GetQuestionsByIds\x12\x19.proto.QuestionIdsRequest\x1a\x1b.proto.GetQuestionsResponse\"\x00\x12S\n" +
	"\x14GetQuestionsByHashes\x12\x1c.proto.QuestionHashesRequest\x1a\x1b.proto.GetQuestionsResponse\"\x00\x12R\n" +
	"\x15GetQuestionsMetaByIds\x12\x19.proto.QuestionIdsRequest\x1a\x1c.proto.QuestionsMetaResponse\"\x00\x12X\n" +
	"\x18GetQuestionsMetaByHashes\x12\x1c.proto.QuestionHashesRequest\x1a\x1c.proto.QuestionsMetaResponse\"\x00\x12_\n" +
	"\x16GetQuestionIdsByHashes\x12\x1c.proto.QuestionHashesRequest\x1a%.proto.GetQuestionIdsByHashesResponse\"\x00\x12\\\n" +
	"\x16GetQuestionHashesByIds\x12\x19.proto.QuestionIdsRequest\x1a%.proto.GetQuestionHashesByIdsResponse\"\x00\x12T\n" +
	"\x1dIncQuestionPaperIndegreeByIds\x12\x19.proto.QuestionIdsRequest\x1a\x16.google.protobuf.Empty\"\x00\x12T\n" +
	"\x1dDecQuestionPaperIndegreeByIds\x12\x19.proto.QuestionIdsRequest\x1a\x16.google.protobuf.Empty\"\x00\x12S\n" +
	"\x1cIncQuestionExamIndegreeByIds\x12\x19.proto.QuestionIdsRequest\x1a\x16.google.protobuf.Empty\"\x00\x12S\n" +
	"\x1cDecQuestionExamIndegreeByIds\x12\x19.proto.QuestionIdsRequest\x1a\x16.google.protobuf.Empty\"\x00\x12J\n" +
	"\x0fUpsertTestCases\x12\x1d.proto.UpsertTestCasesRequest\x1a\x16.google.protobuf.Empty\"\x00\x12L\n" +
	"\x0eGetBoilerplate\x12\x1c.proto.GetBoilerplateRequest\x1a\x1a.proto.BoilerplateResponse\"\x00\x12I\n" +
	"\x0eCreateCategory\x12\x1c.proto.CreateCategoryRequest\x1a\x17.proto.CategoryResponse\"\x00\x12O\n" +
	"\x12GetCategoriesByIds\x12\x19.proto.CategoryIdsRequest\x1a\x1c.proto.GetCategoriesResponse\"\x00\x12S\n" +
	"\x12UpdateCategoryName\x12\x1c.proto.UpdateCategoryRequest\x1a\x1d.proto.UpdateCategoryResponse\"\x00\x12\x88\x01\n" +
	"!GetCodingQuestionInputDefinitions\x12/.proto.GetCodingQuestionInputDefinitionsRequest\x1a0.proto.GetCodingQuestionInputDefinitionsResponse\"\x00B\bZ\x06/protob\x06proto3"

var (
	file_question_proto_rawDescOnce sync.Once
	file_question_proto_rawDescData []byte
)

func file_question_proto_rawDescGZIP() []byte {
	file_question_proto_rawDescOnce.Do(func() {
		file_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_question_proto_rawDesc), len(file_question_proto_rawDesc)))
	})
	return file_question_proto_rawDescData
}

var file_question_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_question_proto_goTypes = []any{
	(*CreateQuestionRequest)(nil),                     // 0: proto.CreateQuestionRequest
	(*CreateQuestionResponse)(nil),                    // 1: proto.CreateQuestionResponse
	(*UpdateQuestionRequest)(nil),                     // 2: proto.UpdateQuestionRequest
	(*UpdateQuestionResponse)(nil),                    // 3: proto.UpdateQuestionResponse
	(*QuestionIdsRequest)(nil),                        // 4: proto.QuestionIdsRequest
	(*GetQuestionsResponse)(nil),                      // 5: proto.GetQuestionsResponse
	(*QuestionsMetaResponse)(nil),                     // 6: proto.QuestionsMetaResponse
	(*QuestionHashesRequest)(nil),                     // 7: proto.QuestionHashesRequest
	(*GetQuestionIdsByHashesResponse)(nil),            // 8: proto.GetQuestionIdsByHashesResponse
	(*GetQuestionHashesByIdsResponse)(nil),            // 9: proto.GetQuestionHashesByIdsResponse
	(*QuestionResponse)(nil),                          // 10: proto.QuestionResponse
	(*QuestionMeta)(nil),                              // 11: proto.QuestionMeta
	(*GetBoilerplateRequest)(nil),                     // 12: proto.GetBoilerplateRequest
	(*UpsertTestCasesRequest)(nil),                    // 13: proto.UpsertTestCasesRequest
	(*CategoryIdsRequest)(nil),                        // 14: proto.CategoryIdsRequest
	(*CategoryResponse)(nil),                          // 15: proto.CategoryResponse
	(*GetCategoriesResponse)(nil),                     // 16: proto.GetCategoriesResponse
	(*CreateCategoryRequest)(nil),                     // 17: proto.CreateCategoryRequest
	(*UpdateCategoryRequest)(nil),                     // 18: proto.UpdateCategoryRequest
	(*UpdateCategoryResponse)(nil),                    // 19: proto.UpdateCategoryResponse
	(*GetCodingQuestionInputDefinitionsRequest)(nil),  // 20: proto.GetCodingQuestionInputDefinitionsRequest
	(*GetCodingQuestionInputDefinitionsResponse)(nil), // 21: proto.GetCodingQuestionInputDefinitionsResponse
	(*InputDefinition)(nil),                           // 22: proto.InputDefinition
	(*ParameterItem)(nil),                             // 23: proto.ParameterItem
	(QuestionType)(0),                                 // 24: proto.QuestionType
	(*CodingQuestionTestCase)(nil),                    // 25: proto.CodingQuestionTestCase
	(*UpsertTestCase)(nil),                            // 26: proto.UpsertTestCase
	(ParameterType)(0),                                // 27: proto.ParameterType
	(*emptypb.Empty)(nil),                             // 28: google.protobuf.Empty
	(*BoilerplateResponse)(nil),                       // 29: proto.BoilerplateResponse
}
var file_question_proto_depIdxs = []int32{
	24, // 0: proto.CreateQuestionRequest.type:type_name -> proto.QuestionType
	24, // 1: proto.UpdateQuestionRequest.type:type_name -> proto.QuestionType
	10, // 2: proto.GetQuestionsResponse.questions:type_name -> proto.QuestionResponse
	11, // 3: proto.QuestionsMetaResponse.meta:type_name -> proto.QuestionMeta
	24, // 4: proto.QuestionResponse.type:type_name -> proto.QuestionType
	25, // 5: proto.QuestionResponse.test_cases:type_name -> proto.CodingQuestionTestCase
	24, // 6: proto.QuestionMeta.type:type_name -> proto.QuestionType
	26, // 7: proto.UpsertTestCasesRequest.test_cases:type_name -> proto.UpsertTestCase
	15, // 8: proto.GetCategoriesResponse.categories:type_name -> proto.CategoryResponse
	22, // 9: proto.GetCodingQuestionInputDefinitionsResponse.input_definitions:type_name -> proto.InputDefinition
	27, // 10: proto.InputDefinition.type:type_name -> proto.ParameterType
	23, // 11: proto.InputDefinition.items:type_name -> proto.ParameterItem
	27, // 12: proto.ParameterItem.type:type_name -> proto.ParameterType
	0,  // 13: proto.Question.CreateQuestion:input_type -> proto.CreateQuestionRequest
	2,  // 14: proto.Question.UpdateQuestion:input_type -> proto.UpdateQuestionRequest
	4,  // 15: proto.Question.GetQuestionsByIds:input_type -> proto.QuestionIdsRequest
	7,  // 16: proto.Question.GetQuestionsByHashes:input_type -> proto.QuestionHashesRequest
	4,  // 17: proto.Question.GetQuestionsMetaByIds:input_type -> proto.QuestionIdsRequest
	7,  // 18: proto.Question.GetQuestionsMetaByHashes:input_type -> proto.QuestionHashesRequest
	7,  // 19: proto.Question.GetQuestionIdsByHashes:input_type -> proto.QuestionHashesRequest
	4,  // 20: proto.Question.GetQuestionHashesByIds:input_type -> proto.QuestionIdsRequest
	4,  // 21: proto.Question.IncQuestionPaperIndegreeByIds:input_type -> proto.QuestionIdsRequest
	4,  // 22: proto.Question.DecQuestionPaperIndegreeByIds:input_type -> proto.QuestionIdsRequest
	4,  // 23: proto.Question.IncQuestionExamIndegreeByIds:input_type -> proto.QuestionIdsRequest
	4,  // 24: proto.Question.DecQuestionExamIndegreeByIds:input_type -> proto.QuestionIdsRequest
	13, // 25: proto.Question.UpsertTestCases:input_type -> proto.UpsertTestCasesRequest
	12, // 26: proto.Question.GetBoilerplate:input_type -> proto.GetBoilerplateRequest
	17, // 27: proto.Question.CreateCategory:input_type -> proto.CreateCategoryRequest
	14, // 28: proto.Question.GetCategoriesByIds:input_type -> proto.CategoryIdsRequest
	18, // 29: proto.Question.UpdateCategoryName:input_type -> proto.UpdateCategoryRequest
	20, // 30: proto.Question.GetCodingQuestionInputDefinitions:input_type -> proto.GetCodingQuestionInputDefinitionsRequest
	1,  // 31: proto.Question.CreateQuestion:output_type -> proto.CreateQuestionResponse
	3,  // 32: proto.Question.UpdateQuestion:output_type -> proto.UpdateQuestionResponse
	5,  // 33: proto.Question.GetQuestionsByIds:output_type -> proto.GetQuestionsResponse
	5,  // 34: proto.Question.GetQuestionsByHashes:output_type -> proto.GetQuestionsResponse
	6,  // 35: proto.Question.GetQuestionsMetaByIds:output_type -> proto.QuestionsMetaResponse
	6,  // 36: proto.Question.GetQuestionsMetaByHashes:output_type -> proto.QuestionsMetaResponse
	8,  // 37: proto.Question.GetQuestionIdsByHashes:output_type -> proto.GetQuestionIdsByHashesResponse
	9,  // 38: proto.Question.GetQuestionHashesByIds:output_type -> proto.GetQuestionHashesByIdsResponse
	28, // 39: proto.Question.IncQuestionPaperIndegreeByIds:output_type -> google.protobuf.Empty
	28, // 40: proto.Question.DecQuestionPaperIndegreeByIds:output_type -> google.protobuf.Empty
	28, // 41: proto.Question.IncQuestionExamIndegreeByIds:output_type -> google.protobuf.Empty
	28, // 42: proto.Question.DecQuestionExamIndegreeByIds:output_type -> google.protobuf.Empty
	28, // 43: proto.Question.UpsertTestCases:output_type -> google.protobuf.Empty
	29, // 44: proto.Question.GetBoilerplate:output_type -> proto.BoilerplateResponse
	15, // 45: proto.Question.CreateCategory:output_type -> proto.CategoryResponse
	16, // 46: proto.Question.GetCategoriesByIds:output_type -> proto.GetCategoriesResponse
	19, // 47: proto.Question.UpdateCategoryName:output_type -> proto.UpdateCategoryResponse
	21, // 48: proto.Question.GetCodingQuestionInputDefinitions:output_type -> proto.GetCodingQuestionInputDefinitionsResponse
	31, // [31:49] is the sub-list for method output_type
	13, // [13:31] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_question_proto_init() }
func file_question_proto_init() {
	if File_question_proto != nil {
		return
	}
	file_common_proto_init()
	file_question_proto_msgTypes[2].OneofWrappers = []any{}
	file_question_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_question_proto_rawDesc), len(file_question_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_question_proto_goTypes,
		DependencyIndexes: file_question_proto_depIdxs,
		MessageInfos:      file_question_proto_msgTypes,
	}.Build()
	File_question_proto = out.File
	file_question_proto_goTypes = nil
	file_question_proto_depIdxs = nil
}
