{{- if and .Values.externalSecrets.enabled .Values.auth.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-externalsecret
  labels:
    app: auth
    component: externalsecret
    tier: backend
    environment: {{ .Values.global.environment }}
spec:
  refreshPolicy: Periodic
  refreshInterval: 2h
  secretStoreRef:
    name: {{ .Values.externalSecrets.vault.name }}
    kind: ClusterSecretStore
  target:
    name: auth-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: auth
        property: jwt-secret-key
    - secretKey: AUTH_DB_ADDR
      remoteRef:
        key: auth
        property: db-addr
    - secretKey: AUTH_DB_USER
      remoteRef:
        key: auth
        property: db-user
    - secretKey: AUTH_DB_PASS
      remoteRef:
        key: auth
        property: db-pass
    - secretKey: AUTH_DB_NAME
      remoteRef:
        key: auth
        property: db-name
{{- end }}
