{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
  labels:
    app: client
    component: frontend
    tier: frontend
    environment: {{ .Values.global.environment }}
data:
  {{- range $key, $value := .Values.frontend.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
