apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
    component: frontend
    tier: frontend
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
      component: frontend
      tier: frontend
      environment: development
  template:
    metadata:
      labels:
        app: client
        component: frontend
        tier: frontend
        environment: development
    spec:
      containers:
        - name: client
          image: pariksha_frontend
          envFrom:
            - configMapRef:
                name: client-config
          ports:
            - containerPort: 3000
          imagePullPolicy: Never
