apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client
    component: frontend
    tier: frontend
    environment: development
spec:
  type: ClusterIP
  ports:
    - name: entrypoint
      port: 3000
      targetPort: 3000
  selector:
    app: client
    component: frontend
    tier: frontend
    environment: development
