// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: common/proto/mail.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MailService_SendVerificationMail_FullMethodName         = "/proto.MailService/SendVerificationMail"
	MailService_SendLoginOtpMail_FullMethodName             = "/proto.MailService/SendLoginOtpMail"
	MailService_SendForgotPasswordMail_FullMethodName       = "/proto.MailService/SendForgotPasswordMail"
	MailService_SendResetPasswordSuccessMail_FullMethodName = "/proto.MailService/SendResetPasswordSuccessMail"
)

// MailServiceClient is the client API for MailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MailServiceClient interface {
	SendVerificationMail(ctx context.Context, in *SendVerificationMailRequest, opts ...grpc.CallOption) (*MailResponse, error)
	SendLoginOtpMail(ctx context.Context, in *SendLoginOtpMailRequest, opts ...grpc.CallOption) (*MailResponse, error)
	SendForgotPasswordMail(ctx context.Context, in *SendForgotPasswordMailRequest, opts ...grpc.CallOption) (*MailResponse, error)
	SendResetPasswordSuccessMail(ctx context.Context, in *SendResetPasswordSuccessMailRequest, opts ...grpc.CallOption) (*MailResponse, error)
}

type mailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMailServiceClient(cc grpc.ClientConnInterface) MailServiceClient {
	return &mailServiceClient{cc}
}

func (c *mailServiceClient) SendVerificationMail(ctx context.Context, in *SendVerificationMailRequest, opts ...grpc.CallOption) (*MailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MailResponse)
	err := c.cc.Invoke(ctx, MailService_SendVerificationMail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) SendLoginOtpMail(ctx context.Context, in *SendLoginOtpMailRequest, opts ...grpc.CallOption) (*MailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MailResponse)
	err := c.cc.Invoke(ctx, MailService_SendLoginOtpMail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) SendForgotPasswordMail(ctx context.Context, in *SendForgotPasswordMailRequest, opts ...grpc.CallOption) (*MailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MailResponse)
	err := c.cc.Invoke(ctx, MailService_SendForgotPasswordMail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) SendResetPasswordSuccessMail(ctx context.Context, in *SendResetPasswordSuccessMailRequest, opts ...grpc.CallOption) (*MailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MailResponse)
	err := c.cc.Invoke(ctx, MailService_SendResetPasswordSuccessMail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailServiceServer is the server API for MailService service.
// All implementations must embed UnimplementedMailServiceServer
// for forward compatibility.
type MailServiceServer interface {
	SendVerificationMail(context.Context, *SendVerificationMailRequest) (*MailResponse, error)
	SendLoginOtpMail(context.Context, *SendLoginOtpMailRequest) (*MailResponse, error)
	SendForgotPasswordMail(context.Context, *SendForgotPasswordMailRequest) (*MailResponse, error)
	SendResetPasswordSuccessMail(context.Context, *SendResetPasswordSuccessMailRequest) (*MailResponse, error)
	mustEmbedUnimplementedMailServiceServer()
}

// UnimplementedMailServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMailServiceServer struct{}

func (UnimplementedMailServiceServer) SendVerificationMail(context.Context, *SendVerificationMailRequest) (*MailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendVerificationMail not implemented")
}
func (UnimplementedMailServiceServer) SendLoginOtpMail(context.Context, *SendLoginOtpMailRequest) (*MailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLoginOtpMail not implemented")
}
func (UnimplementedMailServiceServer) SendForgotPasswordMail(context.Context, *SendForgotPasswordMailRequest) (*MailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendForgotPasswordMail not implemented")
}
func (UnimplementedMailServiceServer) SendResetPasswordSuccessMail(context.Context, *SendResetPasswordSuccessMailRequest) (*MailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendResetPasswordSuccessMail not implemented")
}
func (UnimplementedMailServiceServer) mustEmbedUnimplementedMailServiceServer() {}
func (UnimplementedMailServiceServer) testEmbeddedByValue()                     {}

// UnsafeMailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailServiceServer will
// result in compilation errors.
type UnsafeMailServiceServer interface {
	mustEmbedUnimplementedMailServiceServer()
}

func RegisterMailServiceServer(s grpc.ServiceRegistrar, srv MailServiceServer) {
	// If the following call pancis, it indicates UnimplementedMailServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MailService_ServiceDesc, srv)
}

func _MailService_SendVerificationMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendVerificationMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendVerificationMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailService_SendVerificationMail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendVerificationMail(ctx, req.(*SendVerificationMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_SendLoginOtpMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLoginOtpMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendLoginOtpMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailService_SendLoginOtpMail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendLoginOtpMail(ctx, req.(*SendLoginOtpMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_SendForgotPasswordMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendForgotPasswordMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendForgotPasswordMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailService_SendForgotPasswordMail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendForgotPasswordMail(ctx, req.(*SendForgotPasswordMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_SendResetPasswordSuccessMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendResetPasswordSuccessMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendResetPasswordSuccessMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailService_SendResetPasswordSuccessMail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendResetPasswordSuccessMail(ctx, req.(*SendResetPasswordSuccessMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MailService_ServiceDesc is the grpc.ServiceDesc for MailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MailService",
	HandlerType: (*MailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendVerificationMail",
			Handler:    _MailService_SendVerificationMail_Handler,
		},
		{
			MethodName: "SendLoginOtpMail",
			Handler:    _MailService_SendLoginOtpMail_Handler,
		},
		{
			MethodName: "SendForgotPasswordMail",
			Handler:    _MailService_SendForgotPasswordMail_Handler,
		},
		{
			MethodName: "SendResetPasswordSuccessMail",
			Handler:    _MailService_SendResetPasswordSuccessMail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/proto/mail.proto",
}
