{{- if .Values.vault.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault
  labels:
    app: vault
    component: storage
    tier: backend
    environment: {{ .Values.global.environment }}
rules:
  # Token reviewer auth
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
  # Token review
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
{{- end }}
