{{- if .Values.vault.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth
  namespace: {{ .Release.Namespace }}
  labels:
    app: auth
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paper
  namespace: {{ .Release.Namespace }}
  labels:
    app: paper
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: question
  namespace: {{ .Release.Namespace }}
  labels:
    app: question
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: exam
  namespace: {{ .Release.Namespace }}
  labels:
    app: exam
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: engine
  namespace: {{ .Release.Namespace }}
  labels:
    app: engine
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: gateway
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
{{- end }}
