apiVersion: v1
kind: ConfigMap
metadata:
  name: question-config
  labels:
    app: question
    component: config
    tier: backend
    environment: development
data:
  GO_ENV: "development"
  QUESTION_SERVER_PORT: "4000"

  QUESTION_DB_HOST: "external-question-db-service"
  QUESTION_DB_NAME: "db_pariksha_questions"
  QUESTION_DB_PORT: "6040"
  QUESTION_DB_SSLMODE: "disable"
