{{- if .Values.question.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: question-config
  labels:
    app: question
    component: config
    tier: backend
    environment: {{ .Values.global.environment }}
data:
  GO_ENV: {{ .Values.global.environment }}

  {{- range $key, $value := .Values.question.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
