{{- if .Values.question.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-deployment
  labels:
    app: question
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
spec:
  replicas: {{ .Values.question.replicaCount }}
  selector:
    matchLabels:
      app: question
      component: api
      tier: backend
      environment: {{ .Values.global.environment }}
  template:
    metadata:
      labels:
        app: question
        component: api
        tier: backend
        environment: {{ .Values.global.environment }}
    spec:
      containers:
        - name: question
          image: {{ .Values.question.image.repository }}:{{ .Values.question.image.tag }}
          envFrom:
            - configMapRef:
                name: question-config
            - secretRef:
                name: question-secret
          ports:
            - containerPort: {{ .Values.question.service.targetPort }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          {{- with .Values.question.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.question.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.question.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.question.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
