{{- if and .Values.externalSecrets.enabled .Values.question.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: question-externalsecret
  labels:
    app: question
    component: externalsecret
    tier: backend
    environment: {{ .Values.global.environment }}
spec:
  refreshPolicy: Periodic
  refreshInterval: 2h
  secretStoreRef:
    name: {{ .Values.externalSecrets.vault.name }}
    kind: ClusterSecretStore
  target:
    name: question-secret
    creationPolicy: Owner
  data:
    - secretKey: QUESTION_DB_USER
      remoteRef:
        key: question
        property: db-user
    - secretKey: QUESTION_DB_PASS
      remoteRef:
        key: question
        property: db-pass
    - secretKey: QUESTION_DB_ADDR
      remoteRef:
        key: question
        property: db-addr
    - secretKey: EXAM_API_TOKEN
      remoteRef:
        key: question
        property: exam-api-token
    - secretKey: PAPER_API_TOKEN
      remoteRef:
        key: question
        property: paper-api-token
    - secretKey: ENGINE_API_TOKEN
      remoteRef:
        key: question
        property: engine-api-token
{{- end }}
