apiVersion: v1
kind: Secret
metadata:
  name: question-secret
  labels:
    app: question
    component: secrets
    tier: backend
    environment: development
type: Opaque
stringData:
  QUESTION_DB_USER: "postgres"
  QUESTION_DB_PASS: "postgres"

  EXAM_API_TOKEN: "very-very-top-secret-exam-api-token"
  PAPER_API_TOKEN: "very-very-top-secret-paper-api-token"
  ENGINE_API_TOKEN: "very-very-top-secret-engine-api-token"
