{{- if .Values.question.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: question-service
  labels:
    app: question
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
spec:
  type: {{ .Values.question.service.type }}
  ports:
    - port: {{ .Values.question.service.port }}
      targetPort: {{ .Values.question.service.targetPort }}
  selector:
    app: question
    component: api
    tier: backend
    environment: {{ .Values.global.environment }}
{{- end }}
