package constants

const StatusInvalidToken = 498

const (
	DEFAULT_API_PORT                 string = "4000"
	DEFAULT_OTP_EXPIRES_IN_MINUTES   string = "15"
	DEFAULT_SESSION_EXPIRES_IN_HOURS string = "24"
	DEFAULT_SESSION_COOKIE_NAME      string = "token"
)

const (
	VERIFICATION_OTP_LENGTH  int = 6
	VERIFICATION_HASH_LENGTH int = 10
)

const (
	PAPER_OWNERSHIP_TYPE_OWNER  string = "OWNER"
	PAPER_OWNERSHIP_TYPE_SHARED string = "SHARED"
)

const (
	QUESTION_TYPE_MCQ   string = "MCQ"
	QUESTION_TYPE_SHORT string = "SHORT"
	QUESTION_TYPE_LONG  string = "LONG"
)

const (
	EXAM_TYPE_OPEN   string = "OPEN"
	EXAM_TYPE_INVITE string = "INVITE"
)

const (
	PARTICIPANT_STATUS_UNATTENDED = 0
	PARTICIPANT_STATUS_INVITED    = 1
	PARTICIPANT_STATUS_STARTED    = 2
	PARTICIPANT_STATUS_ENDED      = 3
)

const (
	OTP_PURPOSE_SIGNUP = 1
	OTP_PURPOSE_LOGIN  = 2
)
