apiVersion: v1
kind: Service
metadata:
  name: external-question-db-service
  labels:
    app: question
    component: api
    tier: database
    environment: development
spec:
  type: ExternalName
  externalName: host.docker.internal
